DROP TABLE DIM_CCW_ICD_CONDITIONS CASCADE CONSTRAINTS;

CREATE TABLE DIM_CCW_ICD_CONDITIONS
(
  COMPLICATION      VARCHAR2(1000 BYTE),
  REF_PERIOD_YEARS  NUMBER,
  ICD_CODE          VARCHAR2(1000 BYTE),
  DX_ORDER          VARCHAR2(1000 BYTE),
  ICD               NUMBER,
  EXCL_FIELD        VARCHAR2(1000 BYTE)
);
