DROP TABLE CHOICEBI.DIM_QUALITY_MEASURE_THRESHOLD CASCADE CONSTRAINTS;

CREATE TABLE CHOICEBI.DIM_QUALITY_MEASURE_THRESHOLD
(
  MSR_ID           NUMBER,
  MEASURE_SHORT    VARCHAR2(100 BYTE),
  YEAR_ID          NUMBER,
  TARGET           NUMBER,
  PERCENTILE_50TH  NUMBER,
  PERCENTILE_75TH  NUMBER,
  PERCENTILE_90TH  NUMBER,
  IS_FINAL         NUMBER
);


GRANT SELECT ON CHOICEBI.DIM_QUALITY_MEASURE_THRESHOLD TO MSTRSTG WITH GRANT OPTION;

DROP TABLE CHOICEBI.DIM_QUALITY_MEASURES CASCADE CONSTRAINTS;

CREATE TABLE CHOICEBI.DIM_QUALITY_MEASURES
(
  MSR_ID          NUMBER,
  MSR_GRP_1       VARCHAR2(400 BYTE),
  MSR_GRP_2       VARCHAR2(400 BYTE),
  MSR_TYPE        VARCHAR2(400 BYTE),
  MEASURE#        NUMBER,
  MEASURE_NAME    VARCHAR2(400 BYTE),
  EFF_START_DATE  DATE,
  EFF_END_DATE    DATE,
  SOURCE          VARCHAR2(100 BYTE),
  DEFINATION      VARCHAR2(4000 BYTE),
  NUMERATOR       VARCHAR2(4000 BYTE),
  DENOMINATOR     VARCHAR2(4000 BYTE),
  EXCLUSIONS      VARCHAR2(4000 BYTE),
  COMMENTS        VARCHAR2(4000 BYTE),
  UAS_VARIABLE    VARCHAR2(4000 BYTE),
  MSR_TOKEN       VARCHAR2(100 BYTE)
);

GRANT SELECT ON CHOICEBI.DIM_QUALITY_MEASURES TO MSTRSTG WITH GRANT OPTION;

DROP TABLE CHOICEBI.DIM_QUALITY_MEASURE_CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE CHOICEBI.DIM_QUALITY_MEASURE_CATEGORY
(
  QUAL_CATEGORY_ID    NUMBER,
  QUAL_CATEGORY_DESC  VARCHAR2(300 BYTE)
);


GRANT SELECT ON CHOICEBI.DIM_QUALITY_MEASURE_CATEGORY TO MSTRSTG WITH GRANT OPTION;

DROP TABLE CHOICEBI.DIM_QUALITY_MEASURE_CAT_MAPING CASCADE CONSTRAINTS;

CREATE TABLE CHOICEBI.DIM_QUALITY_MEASURE_CAT_MAPING
(
  MSR_ID            NUMBER,
  MSR_TOKEN         VARCHAR2(100 BYTE),
  QUAL_CATEGORY_ID  NUMBER,
  YEAR_ID           NUMBER
);


GRANT SELECT ON CHOICEBI.DIM_QUALITY_MEASURE_CAT_MAPING TO MSTRSTG WITH GRANT OPTION;

