DROP TABLE DIM_CCW_ICD_CODES CASCADE CONSTRAINTS;

CREATE TABLE DIM_CCW_ICD_CODES
(
  CODE               VARCHAR2(200 BYTE),
  SHORT_DESCRIPTION  VARCHAR2(100 BYTE),
  LONG_DESCRIPTION   VARCHAR2(400 BYTE),
  ICD                VARCHAR2(2000 BYTE)
);

