--DROP TABLE CHOICEBI.F_PAID_HRS_BY_SOURCE CASCADE CONSTRAINTS;

DROP TABLE CHOICEBI.F_PAID_HRS_BY_SOURCE CASCADE CONSTRAINTS;

CREATE TABLE CHOICEBI.F_PAID_HRS_BY_SOURCE
(
    LOB_ID VARCHAR2 (20),
    LINE_OF_BUSINESS VARCHAR2 (20),
    CLAIM_SOURCE     VARCHAR2 (20),
    MONTH_ID         VARCHAR2 (10),
    MRN              VARCHAR2 (100),
    SUBSCRIBER_ID    VARCHAR2 (20),
    CASE_NUM         VARCHAR2 (100),
    SERVICE_DATE     DATE,
    PAY_DATE         DATE,
    INVOICE_NO       VARCHAR2 (20),
    PAY_TWICE_DAILY  NUMBER ,
    PAY_SEQUENCE     NUMBER ,
    PAY_CYCLE_ID     VARCHAR2 (10),
    PAY_PROVIDER_ID  VARCHAR2 (10),
    PAY_TYPE_PAYMENT VARCHAR2 (2),
    PAID_HOURS       NUMBER ,
    PAID_HOURS_HE    NUMBER ,
    PAY_AMOUNT       NUMBER ,
    PRPR_NAME        VARCHAR2 (400),
    PRPR_MCTR_TYPE   VARCHAR2 (40),
    SESE_ID          VARCHAR2 (40),
    SEDS_DESC        VARCHAR2 (400),
    IS_ACTIVE        VARCHAR2(10),
    COUNTY_CODE     VARCHAR2(14 BYTE),
    BOROUGH         VARCHAR2(10 BYTE),
    JOB_RUN_ID       NUMBER,
    SYS_UPD_TS       DATE  DEFAULT SYSDATE
)
NOLOGGING
NOPARALLEL
PARTITION BY LIST (LINE_OF_BUSINESS) 
(
     PARTITION SOURCE_MLTC VALUES ('MLTC'),
     PARTITION SOURCE_FIDA VALUES ('FIDA'),
     PARTITION SOURCE_SH VALUES ('SH'),
     PARTITION SOURCE_MA VALUES ('MA'),
     PARTITION SOURCE_NULL VALUES (NULL),
     PARTITION SOURCE_OTHERS VALUES (DEFAULT)
);

CREATE INDEX CHOICEBI.IDX_F_PAID_HRS ON CHOICEBI.F_PAID_HRS_BY_SOURCE
(LOB_ID, LINE_OF_BUSINESS, CLAIM_SOURCE, SERVICE_DATE, MRN, SUBSCRIBER_ID)
NOLOGGING
NOPARALLEL;

GRANT SELECT ON CHOICEBI.F_PAID_HRS_BY_SOURCE to MSTRSTG;
GRANT SELECT ON CHOICEBI.F_PAID_HRS_BY_SOURCE to RIPUL_P;

DROP TABLE CHOICEBI.FACT_MEMBER_PAID_HRS_BY_DAY CASCADE CONSTRAINTS;

CREATE TABLE CHOICEBI.FACT_MEMBER_PAID_HRS_BY_DAY
(
    THE_DATE          DATE,
    MONTH_ID          NUMBER,
    LOB_ID            NUMBER,
    MRN               NUMBER,
    SUBSCRIBER_ID     VARCHAR2(14),
    ORDERED_DAY       NUMBER,
    ORDERED_DAY_HE    NUMBER,
    PAID_HOURS        NUMBER,
    PAID_HOURS_HE     NUMBER,
    COUNTY_CODE       VARCHAR2(10),
    BOROUGH           VARCHAR2(10),
    IS_ACTIVE         NUMBER,
    LINE_OF_BUSINESS  VARCHAR2(20),
    OPS_HRS_DAY       NUMBER,
    AUTH_HRS_DAY      NUMBER,
    AUTH_HRS_DAY_HE   NUMBER,
	TPPVE_HRS_DAY 	  NUMBER,
	CHG_HRS_DAY 	  NUMBER,
	TMG_HRS_DAY 	  NUMBER,
	TMG_HRS_DAY_HE	  NUMBER,
    JOB_RUN_ID        NUMBER,
    SYS_UPD_TS        DATE  DEFAULT SYSDATE    
)
NOLOGGING
NOPARALLEL
PARTITION BY LIST (LINE_OF_BUSINESS) 
     (
     PARTITION SOURCE_MLTC VALUES ('MLTC'),
     PARTITION SOURCE_FIDA VALUES ('FIDA'),
     PARTITION SOURCE_SH VALUES ('SH'),
     PARTITION SOURCE_MA VALUES ('MA'),
     PARTITION SOURCE_NULL VALUES (NULL),
     PARTITION SOURCE_OTHERS VALUES (DEFAULT)
     );

CREATE INDEX CHOICEBI.FMPD_PKEY_I ON CHOICEBI.FACT_MEMBER_PAID_HRS_BY_DAY
(LOB_ID,LINE_OF_BUSINESS,THE_DATE, MONTH_ID, MRN, SUBSCRIBER_ID, IS_ACTIVE)
NOLOGGING
NOPARALLEL;

GRANT SELECT ON CHOICEBI.FACT_MEMBER_PAID_HRS_BY_DAY TO RIPUL_P;
GRANT SELECT ON CHOICEBI.FACT_MEMBER_PAID_HRS_BY_DAY TO MSTRSTG;
