DROP TABLE CHOICEBI.F_REASSESSMENT_ORDER_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE CHOICEBI.F_REASSESSMENT_ORDER_HISTORY
(
  PATIENT_ID                     NUMBER NOT NULL,
  SUBSCRIBER_ID                  VARCHAR2(1000),
  LINE_OF_BUSINESS               VARCHAR2 (40),
  LOB_ID                         NUMBER,  
  MEDICAID_NUM1                  VARCHAR2(200),
  MRNTEXT                        VARCHAR2(200),
  MRN                            NUMBER,
  CURRENT_STAFF_FIRST_NAME       VARCHAR2(50),
  CURRENT_STAFF_LAST_NAME        VARCHAR2(50),
  VENDOR_NAME                    VARCHAR2(1000),
  ASSIGNED_TO_VENDOR_ON          DATE,
  REASSESSMENT_LIST_MONTH        DATE,
  PLAN_DESC                      VARCHAR2(4000),
  PLAN_NAME                      VARCHAR2(1000),
  PLAN_START_DATE                DATE,
  PLAN_END_DATE                  DATE,
  PROGRAM_NAME                   VARCHAR2(1000),
  PROGRAM_START_DATE             DATE,
  PROGRAM_END_DATE               DATE,
  ASSESSMENTDATE                 DATE,
  PSP_SCPT_ACTIVITY_STATUS       VARCHAR2(50),
  PSP_SCPT_FORM_ACTIVITY_STATUS  VARCHAR2(100),
  PSP_START_DATE                 DATE,
  PSP_END_DATE                   DATE,
  PSP_APPROVED_UNITS             VARCHAR2(100),
  PSP_APPROVED_UNITS_NUM         NUMBER,
  PSP_APPROVED_UNITS_INVALID     NUMBER,
  ATSP_DATE                      DATE,
  UNAVAILABLE_IND                NUMBER,
  ALL_DOCS_COMPLETED             NUMBER,
  ALL_DOCS_NOSNF                 NUMBER,
  UNAVAILABLE_IND_SVC            NUMBER,
  SVCPLAN_LATEUAS                NUMBER,
  SVC_CREATED_ON                 DATE,
  SVCSTAFF_FIRST_NAME            VARCHAR2(100),
  SVCSTAFF_LAST_NAME             VARCHAR2(100),
  SVC_FROM_DATE                  DATE,
  SVC_TO_DATE                    DATE,
  AUTH_CLOSED_SEQ1               NUMBER,
  AUTH_CLOSED_SEQ2               NUMBER,
  AUTH_CLOSED                    NUMBER,
  AUTHS_SUMMED                   NUMBER,
  SVC_LOB_ID                     NUMBER,
  SUM_REQ_UNITS                  NUMBER,
  SUM_APPROVED_UNITS             NUMBER,
  SVC_UNIT_TYPE_ID               NUMBER,
  SERVICE_STATUS_ID              NUMBER,
  SERVICE_STATUS                 VARCHAR2(100),
  AUTH_NO                        NUMBER,
  AUTH_CLASS_ID                  NUMBER,
  SUM_HOURS                      NUMBER,
  SUM_DAYS                       NUMBER,
  WEEKS                          NUMBER,
  SUM_HRS_X_DAYS                 NUMBER,
  PCW_APP_UNITS                  NUMBER,
  PCW_REC_UNITS                  NUMBER,
  PCW_CUR_UNITS                  NUMBER,
  AUTH_ID                        VARCHAR2(100),
  AUTH_PRIORITY_ID               NUMBER,
  AUTH_PRIORITY                  VARCHAR2(100),
  AUTH_NOTI_DATE                 DATE,
  AUTH_FROM_DATE                 DATE,
  AUTH_STATUS_ID                 NUMBER,
  AUTH_STATUS                    VARCHAR2(100),
  AUTH_STATUS_REASON_ID          NUMBER,
  AUTH_STATUS_REASON_NAME        VARCHAR2(100),
  AUTH_CREATED_ON                DATE,
  DECISION_STATUS                VARCHAR2(100),
  DECISION_AUTH_NOTI_DATE        DATE,
  DECISION_CREATED_ON            DATE,
  DECISION_UPDATED_ON            DATE,
  SVCPLAN_CREATED                NUMBER,
  SVCPLAN_CREATED_PRMR_COMPLETE  NUMBER,
  SVCPLAN_CREATED_PSPHRS_OK      NUMBER,
  SVCPLAN_CLOSED                 NUMBER,
  SVCPLAN_CLOSED_PRMR_COMPLETE   NUMBER,
  SVCPLAN_CLOSED_PSPHRS_OK       NUMBER,
  HHA_VARIANCE_DATE              DATE,
  HHA_VARIANCE_STATUS            VARCHAR2(300),
  HHA_VARIANCE_STATUS_DATE       DATE,
  CONTRACTADMINT_REQ_DATE        DATE,
  OPS_UPDATED_DATE               DATE,
  OPS_COMMENTS                   VARCHAR2(4000),
  HHA_VARIANCE_ACTIVITY          NUMBER,
  CONTRACTADMIN_REQ_ACTIVITY     NUMBER,
  OPS_UPDATED_ACTIVITY           NUMBER,
  ATSPSPLIT1                     NUMBER,
  ATSPSPLIT2                     NUMBER,
  WKHRS_M1SPLIT1                 NUMBER,
  WKHRS_M1SPLIT2                 NUMBER,
  WKHRS_M2SPLIT1                 NUMBER,
  WKHRS_M2SPLIT2                 NUMBER,
  WKHRS_M3SPLIT1                 NUMBER,
  WKHRS_M3SPLIT2                 NUMBER,
  WKHRS1SPLIT1                   NUMBER,
  WKHRS1SPLIT2                   NUMBER,
  WKHRS2SPLIT1                   NUMBER,
  WKHRS2SPLIT2                   NUMBER,
  UMEFFWKHRSSPLIT1               NUMBER,
  UMEFFWKHRSSPLIT2               NUMBER,
  UMEFFWKHRS1SPLIT1              NUMBER,
  UMEFFWKHRS1SPLIT2              NUMBER,
  ATSP_DT_HRS                    NUMBER,
  WKHRS_M1                       NUMBER,
  WKHRS_M2                       NUMBER,
  WKHRS_M3                       NUMBER,
  WKHRS1                         NUMBER,
  WKHRS2                         NUMBER,
  UMEFFWKHRS                     NUMBER,
  UMEFFWKHRS1                    NUMBER,
  BASELINE_HRS                   NUMBER,
  ENDPOINT_HRS                   NUMBER,
  PRMRCAT                        VARCHAR(40),
  PRMR_REDUCTION_HRS             NUMBER,
  UMCAT                          VARCHAR(40),
  UM_REDUCTION_HRS               NUMBER,
  JOB_RUN_ID                     NUMBER,
  SYS_UPD_TS                     DATE  DEFAULT SYSDATE    
)
NOPARALLEL;

ALTER TABLE CHOICEBI.F_REASSESSMENT_ORDER_HISTORY ADD CONSTRAINT PK_F_REASS_ORD_HIST PRIMARY KEY (LINE_OF_BUSINESS, SUBSCRIBER_ID, REASSESSMENT_LIST_MONTH, VENDOR_NAME);

GRANT SELECT ON CHOICEBI.F_REASSESSMENT_ORDER_HISTORY TO MSTRSTG;
GRANT SELECT ON CHOICEBI.F_REASSESSMENT_ORDER_HISTORY TO RIPUL_P;