DROP TABLE F_STATIC_MA_RISK_SCORE;

CREATE TABLE F_STATIC_MA_RISK_SCORE
(
    MONTH_ID    NUMBER,
    LOB_ID      VARCHAR2(10),
    PBP_ID      VARCHAR2(10),
    RISK_SCORE  NUMBER
);
GRANT select, insert, update on F_STATIC_MA_RISK_SCORE to ROC_RO; 

GRANT select, insert, update on F_STATIC_MA_RISK_SCORE to ROC_RO;
