DROP TABLE CHOICEBI.FACT_MEMBER_ENROLL_DISENROLL CASCADE CONSTRAINTS;

CREATE TABLE CHOICEBI.FACT_MEMBER_ENROLL_DISENROLL
(
  MEMBER_ID             NUMBER,
  SUBSCRIBER_ID         VARCHAR2(9 BYTE),
  DL_ENRL_SK            NUMBER,
  DL_ENROLL_ID          NUMBER,
  DL_LOB_ID             NUMBER,
  PRODUCT_ID            VARCHAR2(10 BYTE),
  PRODUCT_NAME          VARCHAR2(70 BYTE),
  ENROLLMENT_START_DT   DATE,
  ENROLLMENT_END_DT     DATE,
  CHOICE_PERSPECTIVE    VARCHAR2(6 BYTE),
  CHOICE_PERS_START_DT  DATE,
  CHOICE_PERS_END_DT    DATE,
  MA_PERSPECTIVE        VARCHAR2(20 BYTE),
  MA_PERS_START_DT      DATE,
  MA_PERS_END_DT        DATE,
  MLTC_PERSPECTIVE      VARCHAR2(20 BYTE),
  MLTC_PERS_START_DT    DATE,
  MLTC_PERS_END_DT      DATE,
  FIVE_LOB_PERSPECTIVE  VARCHAR2(20 BYTE),
  FIVE_LOB_START_DT     DATE,
  FIVE_LOB_END_DT       DATE,
  PRODUCT_PERSPECTIVE   VARCHAR2(20 BYTE),
  PRODUCT_START_DT      DATE,
  PRODUCT_END_DT        DATE,
  TRANSFER_FROM         VARCHAR2(400 BYTE),
  TRANSFER_TO           VARCHAR2(400 BYTE),
  FROM_SAME             NUMBER,
  TO_SAME               NUMBER
);


GRANT SELECT ON CHOICEBI.FACT_MEMBER_ENROLL_DISENROLL TO MSTRSTG;

GRANT SELECT ON CHOICEBI.FACT_MEMBER_ENROLL_DISENROLL TO ROC_RO;
