DROP TABLE FACT_PCSP_MATRIX_DATA 

CREATE TABLE FACT_PCSP_MATRIX_DATA
(
    DL_LOB_ID          NUMBER,
    MEMBER_ID          NUMBER,
    SUBSCRIBER_ID      VARCHAR2 (9),
    PRODUCT_NAME       VARCHAR2 (100),
    ENROLLMENT_DATE    DATE,
    DISENROLLMENT_DATE DATE,
    ACTIVE_IND         NUMBER,
    CARE_MANAGER_NAME  VARCHAR2 (400),
    PCSP_CATEGORY      VARCHAR2 (50),
    DOCUMENT_ID        NUMBER (20),
    DOCUMENT           VARCHAR2 (2000),
    DOCUMENT_TYPE      VARCHAR2 (200),
    PCSP_CREATED_BY    VARCHAR2 (400),
    PCSP_CREATED_ON    DATE,
    PCSP_SEQ           NUMBER,
    PSP_DATE           DATE,
    BUSINESS_DAYS      NUMBER,
    PSP_CATEGORY       VARCHAR2 (100),
    ASSESSMENTDATE     DATE,
    ENROLL_ASSESS_SEQ  NUMBER,
    ENROLL_FLAG        NUMBER(1)
);