CREATE TABLE FACT_MEMBER_MONTH_CCW  
(
    MEMBER_ID                      NUMBER,
    SUBSCRIBER_ID                  VARCHAR2(10),
    MONTH_ID                       NUMBER,
    YEAR_ID                        NUMBER,
    ACQUIRED_HYPOTHYROIDISM        NUMBER ,
    ACUTE_MYOCARDIAL_INFARCTION    NUMBER ,
    ALZHEIMERS                     NUMBER ,
    ALZHEIMERS_SENILE_DEMENTIA     NUMBER ,
    ANEMIA                         NUMBER ,
    ASTHMA                         NUMBER ,
    ATRIAL_FIBRILLATION            NUMBER ,
    BENIGN_PROSTATIC_HYPERPLASIA   NUMBER ,
    CATARACT                       NUMBER ,
    CHRONIC_KIDNEY                 NUMBER ,
    CHRONIC_OBSTR_PULMONARY        NUMBER ,
    DEPRESSION                     NUMBER ,
    DIABETES                       NUMBER ,
    GLAUCOMA                       NUMBER ,
    HEART_FAILURE                  NUMBER ,
    HIP_PELVIC_FRACTURE            NUMBER ,
    HYPERLIPIDEMIA                 NUMBER ,
    HYPERTENSION                   NUMBER ,
    ISCHEMIC_HEART                 NUMBER ,
    OSTEOPOROSIS                   NUMBER ,
    RHEUMATOID_ARTHRITIS_OSTEOARTH NUMBER ,
    STROKE_TRANSIENT_ISCHEMIC_ATT  NUMBER ,
    F_M_BREAST_CANCER              NUMBER ,
    COLORECTAL_CANCER              NUMBER ,
    PROSTATE_CANCER                NUMBER ,
    LUNG_CANCER                    NUMBER ,
    ENDOMETRIAL_CANCER             NUMBER 
)