drop table fact_hha_ltp_data

create table fact_hha_ltp_data
(
DAY_DATE            DATE
,CHOICE_WEEK_ID      NUMBER
,MONTH_ID            NUMBER
,QUARTER_ID          NUMBER
,MEMBER_ID           NUMBER
,SUBSCRIBER_ID       VARCHAR2 (200)
,MRN                 NUMBER
,DL_LOB_ID           NUMBER
,DL_PLAN_SK          NUMBER
,DL_ASSESS_SK        NUMBER
,PRODUCT_ID          VARCHAR2 (20)
,PROGRAM             VARCHAR2 (10)
,GROUP_ID            VARCHAR2 (8)
,SUBGROUP_ID         VARCHAR2 (4)
,ASSESSMENTDATE      DATE
,LEVELOFCARESCORE    NUMBER (3)
,TOOL_SRC_SYS        VARCHAR2 (50)
,TOOL_ID             NUMBER
,TOOL_HOURS_WEEK     NUMBER
,TOOL_HOURS_DAY      NUMBER
,SCRIPT_RUN_LOG_ID   NUMBER
,PSP_DATE            DATE
,PSP_HOURS_WEEK      NUMBER
,PSP_HOURS_DAY       NUMBER
,AUTH_HOURS_WEEK     NUMBER
,AUTH_HOURS_DAY      NUMBER
,OPS_HOURS_DAY       NUMBER
,TPPVE_HHA_HOURS_DAY NUMBER
,TPPVE_HHA_AMT_DAY   NUMBER
,TMG_HHA_HOURS_DAY   NUMBER
,TMG_HHA_AMT_DAY     NUMBER
,CLAIM_HHA_HOURS_DAY NUMBER
,CLAIM_HHA_AMT_DAY   NUMBER
,SNF_AUTH_ID         VARCHAR2 (500)
,SNF_AUTH_TYPE_NAME  VARCHAR2 (1000)
,SNF_HOURS_DAY       NUMBER
,SNF_AMT_DAY         NUMBER
,LTP_AUTH_IND        NUMBER
,LTP_PRODUCT_ID_IND  NUMBER
,LTP_IND             NUMBER
,  CRTE_USR_ID                  VARCHAR2(16 BYTE) DEFAULT sys_context('USERENV', 'OS_USER'),
  CRTE_TS                      DATE             DEFAULT SYSDATE,
  UPDT_USR_ID                  VARCHAR2(16 BYTE) DEFAULT sys_context('USERENV', 'OS_USER'),
  UPDT_TS                      DATE             DEFAULT SYSDATE
)




GRANT SELECT ON FACT_HHA_LTP_DATA TO CHOICEBI_RO;

GRANT SELECT ON FACT_HHA_LTP_DATA TO DIONNE_L;

GRANT SELECT ON FACT_HHA_LTP_DATA TO LINKADM;

GRANT SELECT ON FACT_HHA_LTP_DATA TO MSTRSTG;

GRANT SELECT ON FACT_HHA_LTP_DATA TO RESEARCH;

GRANT SELECT ON FACT_HHA_LTP_DATA TO ROC_RO;

GRANT SELECT ON FACT_HHA_LTP_DATA TO SF_CHOICE;
