DROP TABLE CHOICEBI.FACT_CARE_MANAGER_MONTHLY_CALL CASCADE CONSTRAINTS;

CREATE TABLE CHOICEBI.FACT_CARE_MANAGER_MONTHLY_CALL
(
  SUBSCRIBER_ID             VARCHAR2(9 BYTE),
  DL_LOB_ID                 NUMBER,
  COUNTY                    VARCHAR2(20 BYTE),
  MONTH_ID                  NUMBER,
  DL_MEMBER_SK              NUMBER,
  MEMBER_ID                 NUMBER,
  DL_PLAN_SK                NUMBER,
  UNIQUE_ID                 VARCHAR2(200 BYTE),
  SCRIPT_RUN_LOG_ID         NUMBER(19),
  SCRIPT_RUN_LOG_DETAIL_ID  NUMBER(19),
  CREATED_ON                DATE,
  START_DATE                DATE,
  END_DATE                  DATE,
  CM_MONTH_ID               VARCHAR2(6 BYTE),
  SCRIPT_ID                 NUMBER(19),
  SCRIPT_NAME               VARCHAR2(4000 BYTE),
  QUESTION_ID               NUMBER(19),
  QUESTION                  VARCHAR2(4000 BYTE),
  QUESTION_RESPONSE_ID      NUMBER(19),
  QUESTION_OPTION_ID        NUMBER(19),
  OPTION_VALUE              VARCHAR2(4000 BYTE),
  SUB_OPTION_ID             NUMBER(19),
  SUB_OPTION_VALUE          VARCHAR2(4000 BYTE),
  SUCCESSFUL_IND            NUMBER,
  ELIG_SCRIPT_MONTH_SEQ     NUMBER,
  CONTACTED_N               NUMBER,
  CONTACTED_SUCCESSFUL_N    NUMBER,
  CONTACTED_UNSUCCESSFUL_N  NUMBER,
  NOTCONTACTED_N            NUMBER
);


GRANT SELECT ON CHOICEBI.FACT_CARE_MANAGER_MONTHLY_CALL TO MSTRSTG;
