DROP TABLE CHOICEBI.FACT_IP_READMISSION_DATA CASCADE CONSTRAINTS;

CREATE TABLE CHOICEBI.FACT_IP_READMISSION_DATA
(
  SRC                   VARCHAR2(10 BYTE),
  MONTH_ID              NUMBER,
  SUBSCRIBER_ID         VARCHAR2(10 BYTE),
  MEMBER_ID             NUMBER,
  DL_LOB_ID             NUMBER,
  DL_PLAN_SK            NUMBER,
  CM_SK_ID              NUMBER,
  DL_ASSESS_SK          NUMBER,
  DL_MEMBER_ADDRESS_SK  NUMBER,
  CLHP_STAMENT_FR_DT    DATE,
  CLHP_STAMENT_TO_DT    DATE,
  TOT_PAID              NUMBER,
  MATERN_FLG            NUMBER,
  DENOM                 NUMBER,
  READMIT               NUMBER,
  PRPR_ID               VARCHAR2(50 BYTE),
  PRPR_NAME             VARCHAR2(200 BYTE),
  LOS                   NUMBER,
  SYS_UPD_TS            DATE
);


GRANT SELECT ON CHOICEBI.FACT_IP_READMISSION_DATA TO MSTRSTG;