DROP TABLE FACT_MA_PREMRISK_UAS_HCC_LONG;

CREATE TABLE FACT_MA_PREMRISK_UAS_HCC_LONG AS
SELECT DISTINCT
    A.RECORD_ID DL_ASSESS_SK, 
    A.ASSESSMENTDATE, 
    A.MEDICAIDNUMBER1 AS MEDICAID_NUM, 
    REPLACE(A.CODE, '.', '') AS ICD_CODE, 
    A.DESCRIPTION AS DESCRIPTION, 
    B.ESRD_V21, 
    B.AGEDIS_V22, 
    B.AGEDIS_V23,
    B.AGEDIS_V24, 
    B.RXHCC_V05, 
    B.ESRD_V21_IND, 
    B.AGEDIS_V22_IND, 
    B.AGEDIS_V23_IND, 
    B.AGEDIS_V24_IND,
    B.RXHCC_V05_IND
FROM DW_OWNER.UAS_ASSES_DISEASE A
LEFT JOIN DIM_MA_PREMRISK_ICD_TO_HCC B ON REPLACE(A.CODE, '.', '') = B.ICD_CODE;

GRANT SELECT ON FACT_MA_PREMRISK_UAS_HCC_LONG TO MSTRSTG;

GRANT SELECT ON FACT_MA_PREMRISK_UAS_HCC_LONG TO LINKADM;

GRANT SELECT ON FACT_MA_PREMRISK_UAS_HCC_LONG TO LINKADM2;

GRANT SELECT ON FACT_MA_PREMRISK_UAS_HCC_LONG TO ROC_RO;

GRANT SELECT ON FACT_MA_PREMRISK_UAS_HCC_LONG TO ROC_RO2;

GRANT SELECT ON FACT_MA_PREMRISK_UAS_HCC_LONG TO SF_CHOICE;