DROP TABLE CHOICEBI.JAN2016_COUNTS CASCADE CONSTRAINTS;

CREATE TABLE CHOICEBI.JAN2016_COUNTS
(
  REASSESSMENT_LIST_MONTH  DATE,
  TOTAL_MBRS               NUMBER,
  AVAILABLE_FOR_REASSESS   NUMBER,
  ALL_DOCS_COMPLETED       NUMBER,
  ALL_DOCS_NO_SNF          NUMBER,
  NOBASEOPS_PSPINVALID     NUMBER,
  PRMR_REC_DECREASE        NUMBER,
  PRMR_REC_SAME            NUMBER,
  PRMR_REC_INCREASE        NUMBER,
  INVALID_PSP_HRS          NUMBER,
  AVAILABLE_FOR_SVCPLAN    NUMBER,
  SVCPLAN_CREATED_TOTAL    NUMBER,
  ALLDOCS_SVCPLAN_CREATED  NUMBER,
  NOBASEOPS                NUMBER,
  UM_DECREASE              NUMBER,
  UM_SAME                  NUMBER,
  UM_INCREASE              NUMBER,
  COMPLETE_INFO            NUMBER
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


Insert into JAN2016_COUNTS
   (REASSESSMENT_LIST_MONTH, TOTAL_MBRS, AVAILABLE_FOR_REASSESS, ALL_DOCS_COMPLETED, ALL_DOCS_NO_SNF, 
    NOBASEOPS_PSPINVALID, PRMR_REC_DECREASE, PRMR_REC_SAME, PRMR_REC_INCREASE, INVALID_PSP_HRS, 
    AVAILABLE_FOR_SVCPLAN, SVCPLAN_CREATED_TOTAL, ALLDOCS_SVCPLAN_CREATED, NOBASEOPS, UM_DECREASE, 
    UM_SAME, UM_INCREASE, COMPLETE_INFO)
Values
   (TO_DATE('01/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 2114, 2051, 1600, 1600, 
    281, 147, 1085, 87, 0, 1554, 1414, 1409, 111, 48, 1200, 50, 1268);
COMMIT;


DROP TABLE CHOICEBI.JAN2016_HRS CASCADE CONSTRAINTS;

CREATE TABLE CHOICEBI.JAN2016_HRS
(
  REASSESSMENT_LIST_MONTH  DATE,
  MEMBERS                  NUMBER,
  BASELINE_HRS             NUMBER,
  PRMR_REDUCTION_HRS       NUMBER,
  UM_REDUCTION_HRS         NUMBER,
  ENDPOINT_HRS             NUMBER,
  PRMR_DECR_MBRS           NUMBER,
  PRMR_SAME_MBRS           NUMBER,
  PRMR_INCR_MBRS           NUMBER,
  PRMR_DECR_HRS            NUMBER,
  PRMR_SAME_HRS            NUMBER,
  PRMR_INCR_HRS            NUMBER,
  PRMR_DECR_BASE_HRS       NUMBER,
  PRMR_SAME_BASE_HRS       NUMBER,
  PRMR_INCR_BASE_HRS       NUMBER,
  UM_DECR_MBRS             NUMBER,
  UM_SAME_MBRS             NUMBER,
  UM_INCR_MBRS             NUMBER,
  UM_DECR_HRS              NUMBER,
  UM_SAME_HRS              NUMBER,
  UM_INCR_HRS              NUMBER,
  UM_DECR_BASE_HRS         NUMBER,
  UM_SAME_BASE_HRS         NUMBER,
  UM_INCR_BASE_HRS         NUMBER
)
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Insert into JAN2016_HRS
   (REASSESSMENT_LIST_MONTH, MEMBERS, BASELINE_HRS, PRMR_REDUCTION_HRS, UM_REDUCTION_HRS, 
    ENDPOINT_HRS, PRMR_DECR_MBRS, PRMR_SAME_MBRS, PRMR_INCR_MBRS, PRMR_DECR_HRS, 
    PRMR_SAME_HRS, PRMR_INCR_HRS, PRMR_DECR_BASE_HRS, PRMR_SAME_BASE_HRS, PRMR_INCR_BASE_HRS, 
    UM_DECR_MBRS, UM_SAME_MBRS, UM_INCR_MBRS, UM_DECR_HRS, UM_SAME_HRS, 
    UM_INCR_HRS, UM_DECR_BASE_HRS, UM_SAME_BASE_HRS, UM_INCR_BASE_HRS)
Values
   (TO_DATE('01/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1268, 52931, -838, 383, 53053, 143, 1045, 80, -1868, 0, 1030, 6791, 43263, 2877, 48, 1172, 48, -560, 0, 943, 2109, 48622, 2200);
COMMIT;
