DROP TABLE CHOICEBI.LU_SQL CASCADE CONSTRAINTS;

CREATE TABLE CHOICEBI.LU_SQL
(
  JOB_GROUP         VARCHAR2(400),
  DESCRIPTION       VARCHAR2(400),
  TABLE_NAME        VARCHAR2(400),
  SQL_TRUNCATE_STMT CLOB,
  SQL_INSERT_STMT   CLOB,
  SQL_GATHER_STAT   CLOB
);


--DROP MATERIALIZED VIEW CHOICEBI.MV_OUTPATIENT_MATRIX_DATA PRESERVE TABLE;

