drop table otc ;

create table OTC  
(   
    HEALTH_PLAN_ID  VARCHAR2(400),
    PLAN_ID         VARCHAR2(400),
    MEMBER_NO       VARCHAR2(400),
    CARD_NUMBER     VARCHAR2(400),
    TRANSACTION_NO  VARCHAR2(400),
    TRANSACTION_DATE    DATE,
    TRANSACTION_TYPE    VARCHAR2(400),
    TRANSACTION_AMOUNT  number(38,3),
    REMAINING_BALANCE   number(38,3),
    DESCRIPTION     VARCHAR2(400),
    MERCHANT_NAME   VARCHAR2(400),
    MERCHANT_ADDRESS    VARCHAR2(400),
    MERCHANT_CITY   VARCHAR2(400),
    MERCHANT_STATE  VARCHAR2(400),
    MERCHANT_ZIP    VARCHAR2(400),
    MERCHANT_ID     VARCHAR2(400),
    TERMINAL_ID     VARCHAR2(400),
    LOCATION_ID     VARCHAR2(400),
    MERCHANT_REF_NO VARCHAR2(400),
    HEALTH_PLAN_REF_NO  VARCHAR2(400),
    RESPONSE_CODE   VARCHAR2(400),
    RESPONSE_MESSAGE    VARCHAR2(400),
    ORIGINAL_AUTH   VARCHAR2(400), 
    AMOUNT          number(38,3),
    REPORT_CATEGORY VARCHAR2(400),
    PERIOD_COVERED_DATE date,
    INVOICE_NUMBER  VARCHAR2(400),
    RESERVED1       VARCHAR2(400),
    MERCHANT_COUNTY VARCHAR2(400),
    RESERVED3       VARCHAR2(400)
)
;
GRANT SELECT ON CHOICEBI.OTC TO DW_OWNER;

GRANT SELECT ON CHOICEBI.OTC TO MSTRSTG;

GRANT SELECT ON CHOICEBI.OTC TO ROC_RO;
