DROP TABLE TEMP_PARA_ORDER_MBR;

CREATE --GLOBAL TEMPORARY 
table TEMP_PARA_ORDER_MBR 
(
    PARA_ORD_MRN       NUMBER ,
    PARA_CASE_NBR      NUMBER ,
    PARA_CASE_SEQ      NUMBER ,
    PARA_ORD_PROG      VARCHAR2 (3),
    PARA_ORD_CHOICE    NUMBER ,
    PARA_ORD_FIDA      NUMBER ,
    PARA_ORD_MLTC      NUMBER ,
    PARA_ORD_STATUS    VARCHAR2 (2),
    PARA_ORD_SERVICE   NUMBER ,
    PARA_ORD_ENTRY_DTE DATE,
    PARA_REQ_START_DTE DATE,
    ORDER_END          DATE,
    SCHED_WK_BEG_DATE  DATE,
    SCHED_WK_END_DATE  DATE,
    SEQ_NO_DESC        NUMBER ,
    SUMHOURS_LV_WK     NUMBER ,
    SCHED_SATURDAY_LV  NUMBER ,
    SCHED_SUNDAY_LV    NUMBER ,
    SCHED_MONDAY_LV    NUMBER ,
    SCHED_TUESDAY_LV   NUMBER ,
    SCHED_WEDNESDAY_LV NUMBER ,
    SCHED_THURSDAY_LV  NUMBER ,
    SCHED_FRIDAY_LV    NUMBER 
)
--ON COMMIT PRESERVE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;



GRANT SELECT ON CHOICEBI.TEMP_PARA_ORDER_MBR TO RIPUL_P;
GRANT SELECT ON CHOICEBI.TEMP_PARA_ORDER_MBR TO MSTRSTG;