DROP TABLE TEMP_AUTHS_MBR;

CREATE --GLOBAL TEMPORARY 
TABLE TEMP_AUTHS_MBR
( 
    MRN               NUMBER ,
    SBSB_ID           VARCHAR2 (9),
    UMUM_REF_ID       VARCHAR2 (9),
    UMSV_INPUT_USID   VARCHAR2 (10),
    UMSV_INPUT_DT     DATE,
    UMSV_PRPR_ID_REQ  VARCHAR2 (12),
    UMSV_RECD_DT      DATE,
    UMSV_FROM_DT      DATE,
    UMSV_TO_DT        DATE,
    IPCD_ID           VARCHAR2 (7),
    UMSV_UNITS_ALLOW  NUMBER ,
    AUTH_DAYS         NUMBER ,
    AUTH_UNITS_DAY    NUMBER ,
    AUTH_UNITS_HE     NUMBER ,
    AUTH_UNITS_DAY_HE NUMBER ,
    THE_DATE          DATE,
    DOW               VARCHAR2 (3)
)
--ON COMMIT PRESERVE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


GRANT SELECT ON CHOICEBI.TEMP_AUTHS_MBR TO RIPUL_P;
GRANT SELECT ON CHOICEBI.TEMP_AUTHS_MBR TO MSTRSTG;
