DROP TABLE TEMP_TMG_CLAIMS;
 
CREATE --GLOBAL TEMPORARY 
TABLE TEMP_TMG_CLAIMS
(
SBSB_ID          VARCHAR2 (9),
CLCL_ID          VARCHAR2 (12),
CLCL_CUR_STS     VARCHAR2 (2),
PAY_DATE         DATE,
CLCL_TOT_PAYABLE NUMBER, 
PRPR_NAME        VARCHAR2 (55),
PRPR_MCTR_TYPE   VARCHAR2 (4),
CDML_SEQ_NO      NUMBER (5),
SESE_ID          VARCHAR2 (4),
SEDS_DESC        VARCHAR2 (70),
SERVICE_DATE     DATE,
CDML_CHG_AMT     NUMBER, 
CDML_ALLOW       NUMBER ,
CDML_PAID_AMT    NUMBER ,
IPCD_ID          VARCHAR2 (7),
IPCD_DESC        VARCHAR2 (175),
UNITS            NUMBER ,
UNITS_CONVERTED  NUMBER 
)
--ON COMMIT PRESERVE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;




GRANT SELECT ON CHOICEBI.TEMP_TMG_CLAIMS TO RIPUL_P;
GRANT SELECT ON CHOICEBI.TEMP_TMG_CLAIMS TO MSTRSTG;