DROP VIEW V_HHA_ZUNO2_RAW_DISENROLL_SRCE_IND;

CREATE OR REPLACE VIEW V_HHA_ZUNO2_RAW_DISENROLL_SRCE_IND
(
    MEMBER_ID,
    SUBSCRIBER_ID,
    DL_LOB_ID,
    PRODUCT_ID,
    DL_PLAN_SK,
    PRODUCT_NAME,
    LOB,
    LTP_IND,
    MONTH_ID,
    ENROLLMENT_DATE,
    DISENROLLMENT_DATE,
    ACTIVE_IND,
    DISENROLLED_FLAG,
    MONTHS_DISENROLLED,
    REGION_NAME,
    REGION,
    COUNTY,
    RECORD_ID,
    UAS_DATE,
    UAS_NFLOC_SCORE,
    RISK_SCORE,
    ORDERED_AUTHED_HRS_MONTH,
    AUTHED_HRS_MONTH,
    PAID_HRS_MONTH,
    MONTH_DURATION,
    ORDERED_AUTHED_HRS_MONTH_STD30,
    AUTHED_HRS_MONTH_STD30,
    PAID_HRS_MONTH_STD30,
    DISENROLL_MONTH_ID,
    SOURCE_IND
) AS
    SELECT /*+ use_hash(A B C M)) MATERIALIZE*/
          A.MEMBER_ID,
           A.SUBSCRIBER_ID,
           A.DL_LOB_ID,
           A.PRODUCT_ID,
           A.DL_PLAN_SK,
           A.PRODUCT_NAME,
           CASE
               WHEN A.PRODUCT_NAME = 'VNSNY CHOICE MLTC' THEN '2-MLTC'
               WHEN A.PRODUCT_NAME = 'VNSNY CHOICE FIDA COMPLETE (MEDICARE-MEDICAID PLAN)' THEN '4-FIDA'
               WHEN A.PRODUCT_NAME = 'VNSNY CHOICE TOTAL (HMO SNP)' THEN '3-MAP'
           END
               AS LOB --, A.LINE_OF_BUSINESS as lob
                     ,
           CASE WHEN A.SUBGROUP_ID BETWEEN 2000 AND 2007 AND A.DL_LOB_ID = 4 THEN 1 ELSE C.LTP_IND END AS LTP_IND --, 0 as ltp_ind
                                                                                                                 ,
           TO_NUMBER(TO_CHAR( ADD_MONTHS( TO_DATE( A.MONTH_ID, 'YYYYMM'), +1), 'YYYYMM')) MONTH_ID --, A.MONTH_ID
                                                                                                  ,
           A.ENROLLMENT_DATE,
           A.DISENROLLMENT_DATE,
           CASE WHEN A.DISENROLLMENT_DATE = '31dec2199' THEN 1 ELSE 0 END AS ACTIVE_IND,
           A.DISENROLLED_FLAG disenrolled_flag,
           MONTHS_BETWEEN( TO_DATE( TO_CHAR( A.DISENROLLMENT_DATE, 'YYYYMM'), 'YYYYMM'), TO_DATE( A.MONTH_ID, 'yyyymm')) + 1 AS MONTHS_DISENROLLED,
           A.REGION_NAME,
           CASE
               WHEN A.REGION_NAME = 'NEW YORK METRO' THEN '2-REGION 1-NYC'
               WHEN A.REGION_NAME = 'MID-HUDSON/NORTHERN' THEN '3-REGION 2-MH/N'
               WHEN A.REGION_NAME = 'NORTHEAST/WESTERN' THEN '4-REGION 3-NE/W'
               WHEN A.REGION_NAME = 'REST OF NY STATE' THEN '5-REGION 4-ROS'
           END
               AS REGION,
           A.COUNTY,
           A.UAS_RECORD_ID AS RECORD_ID,
           UAS_DATE,
           UAS_NFLOC_SCORE,
           --B.RISK_SCORE,
           RISK_SCORE,
           NVL(ROUND( NVL(C.ORDERED_HHA_HOURS_MONTH, C.AUTH_HOURS_MONTH), 1), 0) AS ORDERED_AUTHED_HRS_MONTH,
           NVL(ROUND( C.AUTH_HOURS_MONTH, 1), 0) AS AUTHED_HRS_MONTH,
           NVL(C.PAID_HHA_HOURS_MONTH, 0) AS PAID_HRS_MONTH,
           M.MONTH_DURATION,
           NVL(ROUND( NVL(C.ORDERED_HHA_HOURS_MONTH / M.MONTH_DURATION * 30, C.AUTH_HOURS_MONTH / M.MONTH_DURATION * 30), 1), 0) AS ORDERED_AUTHED_HRS_MONTH_STD30,
           NVL(ROUND( C.AUTH_HOURS_MONTH / M.MONTH_DURATION * 30, 1), 0) AS AUTHED_HRS_MONTH_STD30,
           NVL(C.PAID_HHA_HOURS_MONTH / M.MONTH_DURATION * 30, 0) AS PAID_HRS_MONTH_STD30,
           TO_CHAR( ADD_MONTHS( TO_DATE( A.MONTH_ID, 'YYYYMM'), +1), 'YYYYMM') DISENROLL_MONTH_ID,
           CASE WHEN uh.subscriber_id IS NOT NULL THEN 3 WHEN gn.subscriber_id IS NOT NULL THEN 2 WHEN ics_ind = 1 THEN 1 ELSE 0 END AS source_ind
    FROM   CHOICEBI.FACT_MEMBER_MONTH A
           LEFT OUTER JOIN dim_guildnet_members gn ON (gn.subscriber_id = a.subscriber_id)
           LEFT OUTER JOIN CHOICEBI.v_hha_zuno2_uhc_members uh ON (uh.subscriber_id = a.subscriber_id)
           --LEFT JOIN CHOICEBI.UAS_RISK_SCORE B ON (A.UAS_RECORD_ID = B.RECORD_ID AND B.MERCER_DOC_YEAR = '2017')
           LEFT JOIN CHOICEBI.FACT_HHA_LTP_MONTHLY_DATA C ON (A.MEMBER_ID = C.MEMBER_ID AND A.MONTH_ID = C.MONTH_ID)
           LEFT JOIN MSTRSTG.LU_MONTH M ON (M.MONTH_ID = A.MONTH_ID)
    WHERE  A.DL_LOB_ID IN (2, 4, 5) AND A.PROGRAM IN ('MLTC', 'FIDA') AND A.MONTH_ID >= 201701 AND (CASE WHEN A.SUBGROUP_ID BETWEEN 2000 AND 2007 AND A.DL_LOB_ID = 4 THEN 1 ELSE C.LTP_IND END) = 0;


GRANT SELECT ON V_HHA_ZUNO2_RAW_DISENROLL_SRCE_IND TO CHOICEBI_RO;

GRANT SELECT ON V_HHA_ZUNO2_RAW_DISENROLL_SRCE_IND TO CHOICEBI_RO_NEW;

GRANT SELECT ON V_HHA_ZUNO2_RAW_DISENROLL_SRCE_IND TO LINKADM;

GRANT SELECT ON V_HHA_ZUNO2_RAW_DISENROLL_SRCE_IND TO LINKADM2;

GRANT SELECT ON V_HHA_ZUNO2_RAW_DISENROLL_SRCE_IND TO ROC_RO;

GRANT SELECT ON V_HHA_ZUNO2_RAW_DISENROLL_SRCE_IND TO ROC_RO2;
