DROP TABLE CHOICEBI.XRUN CASCADE CONSTRAINTS;

CREATE TABLE CHOICEBI.XRUN
(
  RID        NUMBER,
  START_DTM  DATE,
  END_DTM    DATE,
  MSG        VARCHAR2(255 BYTE)
)
RESULT_CACHE (MODE DEFAULT)
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT SELECT ON CHOICEBI.XRUN TO KUNLE_G;
GRANT SELECT ON CHOICEBI.XRUN TO MSTRSTG;
GRANT SELECT ON CHOICEBI.XRUN TO RIPUL_P;
GRANT SELECT ON CHOICEBI.XRUN TO MSTRSTG;
