SELECT DISTINCT 
PATIENT_ID, 1001 MEASURE_ID, --CHART_NUMBER, FIRSTNAME,LASTNAME, PRG_START_DATE, PRG_END_DATE, PRG_DAYS,
CASE  WHEN EVENT_DATE BETWEEN INDEX_DISCHARGE_DATE and INDEX_DISCHARGE_DATE + 10 THEN 10011
      WHEN EVENT_DATE BETWEEN INDEX_DISCHARGE_DATE+11 and INDEX_DISCHARGE_DATE + 30  THEN 10012
      WHEN EVENT_DATE > INDEX_DISCHARGE_DATE + 30 OR (current_date < PRG_END_DATE and EVENT_DATE is null)  THEN 10013
      WHEN (current_date > PRG_END_DATE and EVENT_DATE is null)  OR (EVENT_DATE < INDEX_DISCHARGE_DATE ) THEN 10014
END AS sub_measure_id,
1 AS FLAG,
CASE  WHEN EVENT_DATE BETWEEN INDEX_DISCHARGE_DATE and INDEX_DISCHARGE_DATE + 10 THEN 10
      WHEN EVENT_DATE BETWEEN INDEX_DISCHARGE_DATE+11 and INDEX_DISCHARGE_DATE + 30 THEN 60
      WHEN EVENT_DATE > INDEX_DISCHARGE_DATE + 30 OR (current_date < PRG_END_DATE and EVENT_DATE is null) THEN 70
      WHEN (current_date > PRG_END_DATE and EVENT_DATE is null)  OR (EVENT_DATE < INDEX_DISCHARGE_DATE ) THEN 90
END AS sub_measure_id_1,
TRUNC(EVENT_DATE) AS THE_DATE,
'MD_APT_DATE' date_type
,PAYOR_ID,PAYOR, INDEX_DISCHARGE_DATE AS discharge_date
FROM 
(SELECT DEN.*, NUM.*,NVL(NUM.EVENT_DATE, TO_DATE('11991231', 'YYYYMMDD')) CHK_DATE, row_number() over(partition by PATIENT_ID, DEN.EPISODE_ID ORDER BY NVL(NUM.EVENT_DATE, TO_DATE('11991231', 'YYYYMMDD')) ASC) RN
FROM 
(SELECT distinct C.PRIMARY_CIN VPIN, 
C.CLIENT_ID AS PATIENT_ID,
C.CHART_NUMBER,
C.FIRSTNAME,
C.LASTNAME,
C.DOB,
CA.ORG_NAME,
CA.PROGRAM_NAME AS PRG_NAME,
CASE WHEN CHHP.HEALTH_PLAN_ID IS NULL THEN HP.HEALTH_PLAN ELSE CHHP.HEALTH_PLAN_ID END AS PAYOR_ID, 
CASE WHEN CHHP.HEALTH_PLAN_CODE IS NULL THEN hp.HEALTH_PLAN_NAME ELSE  CHHP.HEALTH_PLAN_CODE END  AS PAYOR,
CE.CLIENT_STATUS, CE.CLIENT_STATUS_DESC,
TRUNC(CA.START_DATE) AS PRG_START_DATE, 
TRUNC(CA.END_DATE) AS PRG_ACTUAL_END_DATE, 
TRUNC(CA.START_DATE) +59 AS PRG_END_DATE,
TRUNC(CA.START_DATE) +59 -TRUNC(CA.START_DATE) AS PRG_DAYS,
CE.ID AS EPISODE_ID,
TRUNC(CE.START_DATE) AS EPI_START_DATE, 
TRUNC(CE.END_DATE) AS EPI_END_DATE,
CLIENT_HSPTL_CERT.CERTIFICATION AS AUTHORIZATION_ID,
CASE WHEN ch.DISCHARGE_DATE IS NULL THEN ch.ANTICIPATED_DISCHARGE_DATE ELSE ch.DISCHARGE_DATE END AS INDEX_DISCHARGE_DATE,
HALLMARK_EVENT_ID,
CHE.RECORD_ORIGIN
FROM CLIENT  C
JOIN CLIENT_EPISODES ce ON ce.CLIENT_ID = c.CLIENT_ID
JOIN CLIENT_HALLMARK_EVENT che ON che.EPISODE_ID = ce.ID
JOIN CLIENT_HOSPITALIZATION ch ON ch.CLIENT_HALLMARK_EVENT_ID = che.ID
JOIN V_CLIENT_ASSIGNMENT ca ON ca.EPISODE_ID = ce.ID
JOIN NTST.CLIENT_HSPTL_CERT  ON CH.ID = CLIENT_HSPTL_CERT.CLIENT_HOSPITALIZATION_ID
LEFT JOIN CLIENT_HSPTL_HEALTH_PLAN CHHP ON CHHP.CLIENT_HOSPITALIZATION_ID = CH.ID 
LEFT JOIN client_elig_health_plan hp on c.client_id = HP.client_id AND hp.HEALTH_PLAN_NAME LIKE '%PA'
WHERE CA.PROGRAM_ID = 402
AND upper(trim(CHE.RECORD_ORIGIN)) = 'HEALTH PLAN'
AND CLIENT_STATUS IN (335, 337)
AND che.HALLMARK_EVENT_ID = 1274
AND NVL (DISCHARGE_DATE, ANTICIPATED_DISCHARGE_DATE) <=  SYSDATE - 30
--AND C.CHART_NUMBER IN ( 1750, 2973, 687)
)den
LEFT JOIN 
(
SELECT C.CLIENT_ID, CE.ID AS EPISODE_ID, CHE.EVENT_DATE
--,row_number() over(partition by C.CLIENT_ID, CE.ID ORDER BY CHE.EVENT_DATE ASC) RN
FROM CLIENT  C
JOIN CLIENT_EPISODES ce ON ce.CLIENT_ID = c.CLIENT_ID
JOIN CLIENT_HALLMARK_EVENT che ON che.EPISODE_ID = ce.ID
WHERE CLIENT_STATUS IN (335, 337)
AND che.HALLMARK_EVENT_ID = 1273
--AND C.CHART_NUMBER IN ( 1750, 2973, 687)
)num
ON den.PATIENT_ID = num.CLIENT_ID AND den.EPISODE_ID = num.EPISODE_ID
--AND RN=1
AND EVENT_DATE >= INDEX_DISCHARGE_DATE
)
WHERE RN=1
