CREATE MATERIALIZED VIEW DIM_UAS_MSR
BUILD IMMEDIATE
REFRESH FORCE
NEXT TRUNC(SYSDATE) + 1    
WITH PRIMARY KEY
AS 
select 'RES_HISTORY_ACUTE_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_ACUTE_CA a union all
select 'RES_HISTORY_CORRECT_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_CORRECT_CA a union all
select 'RES_HISTORY_HOMELES_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_HOMELES_CA a union all
select 'RES_HISTORY_EDUCATION' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_EDUCATION a union all
select 'RES_HISTORY_ATTENDANCE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_ATTENDANCE a union all
select 'RES_EMPLY_STATUS' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_EMPLY_STATUS a union all
select 'RES_HISTORY_EMPLY_ARR' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_EMPLY_ARR a union all
select 'RES_HISTORY_STRUC' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_STRUC a union all
select 'RES_HISTORY_VOLUNTEER' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_VOLUNTEER a union all
select 'RES_HISTORY_DAY_PROGRM' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_DAY_PROGRM a union all
select 'LIFESTYLE_SUB_SOCIAL' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_LIFESTYLE_SUB_SOCIAL a union all
select 'WEIGHT_LOSS' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_WEIGHT_LOSS a union all
select 'DEHYDRATED' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_DEHYDRATED a union all
select 'FLUID_INTAKE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_FLUID_INTAKE a union all
select 'FLUID_OUTPUT' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_FLUID_OUTPUT a union all
select 'NUTRITIONAL_INTAKE_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_NUTRITIONAL_INTAKE_CA a union all
select 'MEDS_REQUIRED_MEDS_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_MEDS_REQUIRED_MEDS_CA a union all
select 'DRUG_ALLERGY_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_DRUG_ALLERGY_CA a union all
select 'TX_BLOOD_PRESSURE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_TX_BLOOD_PRESSURE a union all
select 'TX_COLONOSCOPY' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_TX_COLONOSCOPY a union all
select 'TX_DENTAL' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_TX_DENTAL a union all
select 'TX_EYE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_TX_EYE a union all
select 'TX_HEARING' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_TX_HEARING a union all
select 'TX_INFLUENZA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_TX_INFLUENZA a union all
select 'TX_MAMMOGRAM' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_TX_MAMMOGRAM a union all
select 'TX_PNEUMOVAX' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_TX_PNEUMOVAX a union all
select 'CLINIC_IMPROPER' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_IMPROPER a union all
select 'CLINIC_INJURY' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_INJURY a union all
select 'CLINIC_RESPIRATORY' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_RESPIRATORY a union all
select 'CLINIC_WOUND' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_WOUND a union all
select 'CLINIC_HYPO' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_HYPO a union all
select 'CLINIC_GI' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_GI a union all
select 'CLINIC_EXACERBATION' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_EXACERBATION a union all
select 'CLINIC_MYOCARDIAL' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_MYOCARDIAL a union all
select 'CLINIC_CHEMOTHERAPY' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_CHEMOTHERAPY a union all
select 'CLINIC_SCHEDULED' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_SCHEDULED a union all
select 'CLINIC_URINARY' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_URINARY a union all
select 'CLINIC_IV' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_IV a union all
select 'CLINIC_THROMBOSIS' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_THROMBOSIS a union all
select 'CLINIC_UNCONTROLD_PAIN' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_UNCONTROLD_PAIN a union all
select 'CLINIC_PSYCHOTIC' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_PSYCHOTIC a union all
select 'CLINIC_OTHER' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_OTHER a union all
select 'CLINIC_UNKNOWN' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CLINIC_UNKNOWN a union all
select 'ER_IMPROPER' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ER_IMPROPER a union all
select 'ER_NAUSEA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ER_NAUSEA a union all
select 'FALLS' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_FALLS a union all
select 'RECENT_FALLS' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RECENT_FALLS a union all
select 'FALLS_MEDICAL' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_FALLS_MEDICAL a union all
select 'PROBLEM_DIZZINESS_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PROBLEM_DIZZINESS_CA a union all
select 'PROBLEM_UNSTEADY_GAIT' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PROBLEM_UNSTEADY_GAIT a union all
select 'PROBLEM_CHEST_PAIN' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PROBLEM_CHEST_PAIN a union all
select 'PROBLEM_ABNORMAL_THOUG' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PROBLEM_ABNORMAL_THOUG a union all
select 'PROBLEM_DELUSIONS_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PROBLEM_DELUSIONS_CA a union all
select 'PROBLEM_HALLUCINATN_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PROBLEM_HALLUCINATN_CA a union all
select 'PROBLEM_ACID_REFLUX_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PROBLEM_ACID_REFLUX_CA a union all
select 'PROBLEM_CONSTIPATN_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PROBLEM_CONSTIPATN_CA a union all
select 'PROBLEM_DIARRHEA_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PROBLEM_DIARRHEA_CA a union all
select 'PROBLEM_VOMITING_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PROBLEM_VOMITING_CA a union all
select 'PROBLEM_DIFFICULT_SLEP' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PROBLEM_DIFFICULT_SLEP a union all
select 'PROBLEM_EXCESS_SLEEP' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PROBLEM_EXCESS_SLEEP a union all
select 'DYSPNEA_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_DYSPNEA_CA a union all
select 'FATIGUE_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_FATIGUE_CA a union all
select 'PAIN_FREQUENCY_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PAIN_FREQUENCY_CA a union all
select 'PAIN_INTENSITY_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PAIN_INTENSITY_CA a union all
select 'PAIN_CONSISTENCY_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PAIN_CONSISTENCY_CA a union all
select 'PAIN_BREAKTHROUGH' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PAIN_BREAKTHROUGH a union all
select 'PAIN_CONTROL_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PAIN_CONTROL_CA a union all
select 'INSTABILITY_PATTERN_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_INSTABILITY_PATTERN_CA a union all
select 'INSTABILITY_ACUTE_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_INSTABILITY_ACUTE_CA a union all
select 'SELF_RATED_HEALTH' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_SELF_RATED_HEALTH a union all
select 'LIFESTYLE_SMOKES' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_LIFESTYLE_SMOKES a union all
select 'LIFESTYLE_SMOKES_SAFEL' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_LIFESTYLE_SMOKES_SAFEL a union all
select 'LIFESTYLE_CHEWS_TOBACC' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_LIFESTYLE_CHEWS_TOBACC a union all
select 'LIFESTYLE_ALCOHOL_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_LIFESTYLE_ALCOHOL_CA a union all
select 'LIFESTYLE_SUBSTANCE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_LIFESTYLE_SUBSTANCE a union all
select 'LIFESTYLE_SUB_CRITICSM' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_LIFESTYLE_SUB_CRITICSM a union all
select 'LIFESTYLE_SUB_GUILT' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_LIFESTYLE_SUB_GUILT a union all
select 'LIFESTYLE_SUB_MORNING' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_LIFESTYLE_SUB_MORNING a union all
select 'IADL_CAPACITY_TRANSPOR' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_CAPACITY_TRANSPOR a union all
select 'IADL_PERFORMANCE_EQUIP' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_PERFORMANCE_EQUIP a union all
select 'IADL_CAPACITY_EQUIP' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_CAPACITY_EQUIP a union all
select 'ADL_BATHING' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ADL_BATHING a union all
select 'ADL_HYGIENE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ADL_HYGIENE a union all
select 'ADL_DRESS_UPPER' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ADL_DRESS_UPPER a union all
select 'ADL_DRESS_LOWER' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ADL_DRESS_LOWER a union all
select 'ADL_WALKING' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ADL_WALKING a union all
select 'ADL_LOCOMOTION' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ADL_LOCOMOTION a union all
select 'ADL_TOILET_TRANSFER' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ADL_TOILET_TRANSFER a union all
select 'ADL_TOILET_USE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ADL_TOILET_USE a union all
select 'ADL_BED' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ADL_BED a union all
select 'ADL_EATING' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ADL_EATING a union all
select 'LOCOMOTION_INDOORS' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_LOCOMOTION_INDOORS a union all
select 'HOURS_EXERCISE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_HOURS_EXERCISE a union all
select 'DAYS_OUTDOORS' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_DAYS_OUTDOORS a union all
select 'ADL_STATUS_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ADL_STATUS_CA a union all
select 'ADL_STATUS_SELF_SUFF' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ADL_STATUS_SELF_SUFF a union all
select 'DRIVING_DROVE_CAR' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_DRIVING_DROVE_CAR a union all
select 'DRIVING_LIMIT_STOP' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_DRIVING_LIMIT_STOP a union all
select 'IADL_TRANSPORTATION_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_TRANSPORTATION_CA a union all
select 'BLADDER_CONTINENCE_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_BLADDER_CONTINENCE_CA a union all
select 'BOWEL_CONTINENCE_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_BOWEL_CONTINENCE_CA a union all
select 'MUSCULOSKELETAL_HIP' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_MUSCULOSKELETAL_HIP a union all
select 'MUSCULOSKELET_OTH_FRAC' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_MUSCULOSKELET_OTH_FRAC a union all
select 'NEUROLOGICAL_ALZHEIMER' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_NEUROLOGICAL_ALZHEIMER a union all
select 'NEUROLOGICAL_DEMENTIA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_NEUROLOGICAL_DEMENTIA a union all
select 'NEUROLOGICAL_STROKE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_NEUROLOGICAL_STROKE a union all
select 'CARDIAC_HEART_DISEASE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CARDIAC_HEART_DISEASE a union all
select 'CARDIAC_PULMONARY' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CARDIAC_PULMONARY a union all
select 'CARDIAC_FAILURE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CARDIAC_FAILURE a union all
select 'PSYCHIATRIC_ANXIETY' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PSYCHIATRIC_ANXIETY a union all
select 'PHYS_ORDER' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PHYS_ORDER a union all
select 'ASSESSMENT_REASON_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ASSESSMENT_REASON_CA a union all
select 'CHA_REFERRAL_SOURCE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CHA_REFERRAL_SOURCE a union all
select 'LIVING_ARRANGEMENT_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_LIVING_ARRANGEMENT_CA a union all
select 'RES_HISTORY_ADULT_CARE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_ADULT_CARE a union all
select 'RES_HISTORY_LTC_FACILT' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_LTC_FACILT a union all
select 'RES_HISTORY_MENTAL' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_MENTAL a union all
select 'RES_HISTORY_INTELLE_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_INTELLE_CA a union all
select 'RES_HISTORY_PSYCHIA_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_PSYCHIA_CA a union all
select 'RES_HISTORY_NURSING_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_NURSING_CA a union all
select 'RES_HISTORY_REHAB_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_REHAB_CA a union all
select 'RES_HISTORY_HOSPICE_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_RES_HISTORY_HOSPICE_CA a union all
select 'LONELY_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_LONELY_CA a union all
select 'SOCIAL_CHANGE_ACTIVITY' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_SOCIAL_CHANGE_ACTIVITY a union all
select 'TIME_ALONE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_TIME_ALONE a union all
select 'LIFE_STRESSORS_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_LIFE_STRESSORS_CA a union all
select 'IADL_PERFORMANCE_MEALS' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_PERFORMANCE_MEALS a union all
select 'IADL_CAPACITY_MEALS' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_CAPACITY_MEALS a union all
select 'IADL_PERFORMANCE_HOUSW' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_PERFORMANCE_HOUSW a union all
select 'IADL_CAPACITY_HOUSEWRK' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_CAPACITY_HOUSEWRK a union all
select 'IADL_PERFORMANCE_FINAN' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_PERFORMANCE_FINAN a union all
select 'IADL_CAPACITY_FINANCES' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_CAPACITY_FINANCES a union all
select 'IADL_PERFORMANCE_MEDS' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_PERFORMANCE_MEDS a union all
select 'IADL_CAPACITY_MEDS' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_CAPACITY_MEDS a union all
select 'IADL_PERFORMANCE_PHONE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_PERFORMANCE_PHONE a union all
select 'IADL_CAPACITY_PHONE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_CAPACITY_PHONE a union all
select 'IADL_PERFORMANCE_STAIR' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_PERFORMANCE_STAIR a union all
select 'IADL_CAPACITY_STAIRS' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_CAPACITY_STAIRS a union all
select 'IADL_PERFORMANCE_SHOP' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_PERFORMANCE_SHOP a union all
select 'IADL_CAPACITY_SHOPPING' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_CAPACITY_SHOPPING a union all
select 'IADL_PERFORMANCE_TRANS' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IADL_PERFORMANCE_TRANS a union all
select 'ER_INJURY' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ER_INJURY a union all
select 'ER_RESPIRATORY' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ER_RESPIRATORY a union all
select 'ER_WOUND' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ER_WOUND a union all
select 'ER_CARDIAC' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ER_CARDIAC a union all
select 'ER_HYPO' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ER_HYPO a union all
select 'ER_GI' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ER_GI a union all
select 'ER_OTHER' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ER_OTHER a union all
select 'ER_UNKNOWN' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ER_UNKNOWN a union all
select 'NH_THERAPY' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_NH_THERAPY a union all
select 'NH_RESPITE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_NH_RESPITE a union all
select 'NH_END_OF_LIFE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_NH_END_OF_LIFE a union all
select 'NH_PLACEMENT' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_NH_PLACEMENT a union all
select 'NH_UNSAFE' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_NH_UNSAFE a union all
select 'NH_OTHER' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_NH_OTHER a union all
select 'NH_UNKNOWN' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_NH_UNKNOWN a union all
select 'FAMILY_RELATIONSHIP_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_FAMILY_RELATIONSHIP_CA a union all
select 'FINANCES' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_FINANCES a union all
select 'TX_YESNO' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_TX_YESNO a union all
select 'PSYCHIATRIC_BIPOLAR' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PSYCHIATRIC_BIPOLAR a union all
select 'PSYCHIATRIC_DEPRESSION' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PSYCHIATRIC_DEPRESSION a union all
select 'PSYCHIATRIC_SCHIZOPHR' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PSYCHIATRIC_SCHIZOPHR a union all
select 'OTHER_CANCER_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_OTHER_CANCER_CA a union all
select 'OTHER_DIABETES_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_OTHER_DIABETES_CA a union all
select 'BEHAVIOR_SEXUAL_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_BEHAVIOR_SEXUAL_CA a union all
select 'BEHAVIOR_RESISTS_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_BEHAVIOR_RESISTS_CA a union all
select 'MOOD_INTEREST_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_MOOD_INTEREST_CA a union all
select 'MOOD_ANXIOUS_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_MOOD_ANXIOUS_CA a union all
select 'MOOD_SAD_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_MOOD_SAD_CA a union all
select 'SOCIAL_PARTICIPATION' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_SOCIAL_PARTICIPATION a union all
select 'SOCIAL_VISIT' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_SOCIAL_VISIT a union all
select 'SOCIAL_OTHER_INTERACTN' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_SOCIAL_OTHER_INTERACTN a union all
select 'SOCIAL_EXPRESS_ANGER' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_SOCIAL_EXPRESS_ANGER a union all
select 'SOCIAL_FEARFUL' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_SOCIAL_FEARFUL a union all
select 'SOCIAL_NEGLECTED' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_SOCIAL_NEGLECTED a union all
select 'MEMORY_RECALL_SHORT_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_MEMORY_RECALL_SHORT_CA a union all
select 'COGNITIVE_SKILLS_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_COGNITIVE_SKILLS_CA a union all
select 'MEMORY_RECALL_PROCE_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_MEMORY_RECALL_PROCE_CA a union all
select 'IMPAIRED_DECISION_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_IMPAIRED_DECISION_CA a union all
select 'SELF_UNDERSTOOD_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_SELF_UNDERSTOOD_CA a union all
select 'UNDERSTAND_OTHERS_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_UNDERSTAND_OTHERS_CA a union all
select 'HEARING_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_HEARING_CA a union all
select 'VISION_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_VISION_CA a union all
select 'NEGATIVE_STATEMENTS_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_NEGATIVE_STATEMENTS_CA a union all
select 'PERSISTENT_ANGER_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_PERSISTENT_ANGER_CA a union all
select 'UNREAL_FEARS_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_UNREAL_FEARS_CA a union all
select 'HEALTH_COMPLAINTS_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_HEALTH_COMPLAINTS_CA a union all
select 'ANXIOUS_COMPLAINTS_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_ANXIOUS_COMPLAINTS_CA a union all
select 'SAD_FACIAL_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_SAD_FACIAL_CA a union all
select 'CRYING_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_CRYING_CA a union all
select 'WITHDRAWAL_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_WITHDRAWAL_CA a union all
select 'REDUCED_SOCIAL_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_REDUCED_SOCIAL_CA a union all
select 'BEHAVIOR_WANDERING_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_BEHAVIOR_WANDERING_CA a union all
select 'BEHAVIOR_VERBAL_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_BEHAVIOR_VERBAL_CA a union all
select 'BEHAVIOR_PHYSICAL_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_BEHAVIOR_PHYSICAL_CA a union all
select 'BEHAVIOR_DISRUPTIVE_CA' MSR, a.ID, a.VAL from dw_owner.DIM_UAS_BEHAVIOR_DISRUPTIVE_CA a 



select * from DIM_UAS_MSR
