DROP MATERIALIZED VIEW CHOICEBI.FACT_QUALITY_RISK_MEASURES;

CREATE MATERIALIZED VIEW CHOICEBI.FACT_QUALITY_RISK_MEASURES 
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
SELECT DISTINCT B.MSR_ID,
       A.MSR_TOKEN,
       A.QIP_MONTH_ID MONTH_ID,
       A.CURRENT_PERIOD,
       A.SUBSCRIBER_ID,
       A.DL_MEMBER_SK,
       A.MEMBER_ID,
       A.DL_LOB_GRP_ID,
       A.ASSESSMENT_DATE1,
       A.ASSESSMENT_DATE2,
       A.ASSESSMENT_DATE3,
       A.ASSESSMENT_REASON1,
       A.ASSESSMENT_REASON2,
       A.ASSESSMENT_REASON3,
       A.RECORD_ID1 UAS_RECORD_ID1,
       A.RECORD_ID2 UAS_RECORD_ID2,
       A.RECORD_ID3 UAS_RECORD_ID3,
       A.ASSESSMENT_MONTH1,
       A.NEXT_DUE,
       A.NEXT_DUE_PERIOD,
       A.ONURSEORG VENDOR_ID,
       A.ONURSEORGNAME,
       A.ONURSENAME,
       A.RISK,
       A.OUTCOME,
       A.RISK_NOTE,
       A.DESIRED_OUTCOME,
       A.DL_LOB_ID,
       A.DL_ENROLL_ID,
       --A.DL_ASSESS_SK,
       --A.DL_PROV_SK,
       --A.PROVIDER_ID,
       A.DL_PLAN_SK,
       SYSDATE SYS_UPD_TS
FROM   V_QUALITY_RISK_MEASURES_LONG A
       JOIN DIM_QUALITY_MEASURES B
           ON (UPPER(B.MSR_TOKEN) = UPPER(A.MSR_TOKEN));


COMMENT ON MATERIALIZED VIEW CHOICEBI.FACT_QUALITY_RISK_MEASURES IS 'snapshot table for snapshot CHOICEBI.FACT_QUALITY_RISK_MEASURES';

GRANT SELECT ON CHOICEBI.FACT_QUALITY_RISK_MEASURES TO MSTRSTG WITH GRANT OPTION;
