DROP materialized VIEW MV_GC_VENDOR_TID_MAPPING;

CREATE MATERIALIZED VIEW MV_GC_VENDOR_TID_MAPPING AS              
SELECT DISTINCT ONURSEORG
    , ONURSEORGNAME
    , CASE WHEN UPPER(ONURSEORGNAME) LIKE '%PREMIER%' THEN '123456'
            WHEN UPPER(ONURSEORGNAME) LIKE '%GREATER NEW YORK%' THEN '26-3440689'
            WHEN UPPER(ONURSEORGNAME) LIKE '%UNLIMITED%' THEN '132808207'
            WHEN UPPER(ONURSEORGNAME) LIKE '%VNS%' OR ONURSEORGNAME='Visiting Nurse Service of New York Home Care' THEN '13-3951057'
            WHEN UPPER(ONURSEORGNAME) LIKE '%HCR%' THEN '16-1108008'
            WHEN UPPER(ONURSEORGNAME) LIKE '%VNA%' 
                    OR ONURSEORGNAME='Visiting Nursing Association Of Western New York Chha'
                    OR ONURSEORGNAME='Visiting Nursing Association Of@western New York Chha'
                     THEN '161491203'
     END AS TAX_ID   
FROM DW_OWNER.UAS_PAT_ASSESSMENTS 
GROUP BY ONURSEORG, ONURSEORGNAME  


GRANT SELECT ON MV_GC_VENDOR_TID_MAPPING TO MSTRSTG;

GRANT SELECT ON MV_GC_VENDOR_TID_MAPPING TO ROC_RO;

