DROP MATERIALIZED VIEW V_AUTH_DATA1;

CREATE MATERIALIZED VIEW V_AUTH_DATA1
BUILD IMMEDIATE
REFRESH FORCE
NEXT TRUNC(SYSDATE) + 1.25  
WITH PRIMARY KEY
AS
select /*+ bypass_recursive_check */* from v_authdata;
           
GRANT SELECT ON V_AUTH_DATA1 TO CHOICEBI_RO;

GRANT SELECT ON V_AUTH_DATA1 TO CHOICEBI_RO_NEW;

GRANT SELECT ON V_AUTH_DATA1 TO MICHAEL_K;

GRANT SELECT ON V_AUTH_DATA1 TO MSTRSTG;

GRANT SELECT ON V_AUTH_DATA1 TO MSTRSTG2;

GRANT SELECT ON V_AUTH_DATA1 TO ROC_RO;

GRANT SELECT ON V_AUTH_DATA1 TO ROC_RO2;

GRANT SELECT ON V_AUTH_DATA1 TO SF_CHOICE;

select * from v_auth_data