DROP MATERIALIZED VIEW CHOICEBI.V_FMM

CREATE MATERIALIZED VIEW CHOICEBI.V_FMM (DATA_SOURCE,MRN,MONTH_ID,PROGRAM,BOROUGH,COUNTY_CODE,STAFF_ID,MEDICAID_NUM,MEDICARE_NUM,SUBSCRIBER_ID,BENEFIT_REGION,UAS_DATE,UAS_NFLOC_SCORE,DC_REASON,DISENROLL_DISP,FLAG,CASE_NBR,STATE_CODE,ENROLLMENT_DATE,DISENROLLMENT_DATE,ENROLLED_FLAG,DISENROLLED_FLAG,LINE_OF_BUSINESS,PROVIDER_ID,PROVIDER_NAME,MONTH,SSN,LAST_NAME,FIRST_NAME,DATE_OF_BIRTH,SEX,COUNTY,HIGHEST_CASE_NUMBER,LOB_ID,UAS_RECORD_ID,REFERRAL_DATE,MANDATORY_ENROLLMENT,DISENROLL_RSN_DESC,PRODUCT_ID,PRODUCT_NAME,PLAN_ID,PLAN_DESC,DL_MEMBER_SK,MEMBER_ID,DL_PMPM_ENR_SK,DL_ENROLL_ID,DL_ENRL_SK,DL_LOB_ID,DL_PLAN_SK,PROV_SK_ID,CM_SK_ID,ASSESSMENT_SK_ID,DL_LOB_GRP_ID)
BUILD IMMEDIATE
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
AS 
WITH D_LOB_GROUP AS
         (SELECT 1 DL_LOB_GRP_ID, 'MA' LOB_GRP_DESC FROM DUAL
          UNION ALL
          SELECT 2, 'MLTC' DL_LOB_ID FROM DUAL
          UNION ALL
          SELECT 3, 'SH' DL_LOB_ID FROM DUAL
          UNION ALL
          SELECT 4, 'FIDA' DL_LOB_ID FROM DUAL),
     REF_LOB_GROUP_MAPPING AS
         (SELECT 1 DL_LOB_GRP_ID, 1 DL_LOB_ID FROM DUAL
          UNION ALL
          SELECT 1 DL_LOB_GRP_ID, 5 DL_LOB_ID FROM DUAL
          UNION ALL
          SELECT 2, 2 DL_LOB_ID FROM DUAL
          UNION ALL
          --SELECT 2, 5 DL_LOB_ID FROM DUAL UNION ALL
          SELECT 3, 3 DL_LOB_ID FROM DUAL
          UNION ALL
          SELECT 4, 4 DL_LOB_ID FROM DUAL),
     V_REF_PLAN AS
         (SELECT D.DL_LOB_GRP_ID, E.LOB_GRP_DESC, B.*
          FROM   CHOICE.REF_PLAN@DL_CHOICE B
                 JOIN CHOICE.REF_LOB@DL_CHOICE C ON (C.DL_LOB_ID = B.DL_LOB_ID)
                 JOIN REF_LOB_GROUP_MAPPING D ON (C.DL_LOB_ID = D.DL_LOB_ID)
                 JOIN D_LOB_GROUP E ON (E.DL_LOB_GRP_ID = D.DL_LOB_GRP_ID))
SELECT /*+ driving_site(a)  cardinality(A 400000) cardinality(b 60000000) cardinality(c 60000000)   cardinality(d 60000000)  cardinality(e 60000000) cardinality(f 60000000) no_merge */
      'CHOICEDM' DATA_SOURCE,
       MRN,
       REPORTING_MONTH MONTH_ID,
       PLAN_PACKAGE PROGRAM,
       BOROUGH,
       COUNTY_CODE,
       --NULL TEAM,
       H.MEMBER_ID STAFF_ID,
       MEDICAID_NUMBER MEDICAID_NUM,
       HICN MEDICARE_NUM,
       SUBSCRIBER_ID,
       C.BENEFIT_REGION,
       ASSESSMENTDATE UAS_DATE,
       LEVELOFCARESCORE UAS_NFLOC_SCORE,
       --NULL REFERRAL_SOURCE,
       DISENROLL_RSN_CODE DC_REASON,
       DISENROLL_RSN_DESC DISENROLL_DISP,
       --NULL AGE,
       1 FLAG,
       CASE_NBR,
       STATE STATE_CODE,
       ENROLLMENT_START_DT ENROLLMENT_DATE,
       ENROLLMENT_END_DT DISENROLLMENT_DATE,
       NEW_ENR_IND ENROLLED_FLAG,
       NEW_DISENR_IND DISENROLLED_FLAG,
       LOB_GRP_DESC LINE_OF_BUSINESS,
       PROVIDER_ID,
       PCP_NAME PROVIDER_NAME,
       REPORTING_MONTH MONTH,
       SSN,
       D.LAST_NAME,
       D.FIRST_NAME,
       DOB DATE_OF_BIRTH,
       SEX_CODE SEX,
       COUNTY,
       TO_CHAR(CASE_NBR) HIGHEST_CASE_NUMBER,
       A.dl_LOB_ID LOB_ID,
       A.ASSESSMENT_SK_ID UAS_RECORD_ID,
       REFERRAL_DATE,
       MANDATORY_ENROLLMENT,
       -- DISENROLLMENT_MONTH,
       c.DISENROLL_RSN_DESC,
       b.product_id,
       PRODUCT_NAME,
       b.PLAN_ID,
       PLAN_DESC,
       A.DL_MEMBER_SK,
       D.MEMBER_ID,
       A.DL_PMPM_ENR_SK,
       A.DL_ENROLL_ID,
       A.DL_ENRL_SK,
       A.DL_LOB_ID,
       A.DL_PLAN_SK,
       A.PROV_SK_ID,
       A.CM_SK_ID,
       A.ASSESSMENT_SK_ID,
       DL_LOB_GRP_ID
FROM   CHOICE.FCT_PMPM_ENROLLMENT@DL_CHOICE A
       LEFT JOIN V_REF_PLAN B ON (A.DL_PLAN_SK = B.DL_PLAN_SK)
       LEFT JOIN CHOICE.DIM_MEMBER_ENROLLMENT@DL_CHOICE C
           ON (    A.DL_ENRL_SK = C.DL_ENRL_SK --AND C.DL_ACTIVE_REC_IND = 'Y'
           )
       LEFT JOIN CHOICE.DIM_MEMBER@DL_CHOICE D
           ON (    A.DL_MEMBER_SK = D.DL_MEMBER_SK
               ) -- AND D.DL_ACTIVE_REC_IND = 'Y' Removed condition to include all members
       LEFT JOIN CHOICE.DIM_MEMBER_ADDRESS@DL_CHOICE E
           ON (    D.MEMBER_ID = E.MEMBER_ID
               AND E.DL_ACTIVE_REC_IND = 'Y'
               AND ADDRESS_TYPE = 'H')
       LEFT JOIN CHOICE.DIM_MEMBER_ASSESSMENTS@DL_CHOICE F
           ON (F.DL_ASSESS_SK = A.ASSESSMENT_SK_ID)
       LEFT JOIN CHOICE.DIM_MEMBER_PRIMARY_PROVIDER@DL_CHOICE G
           ON (    G.DL_PROV_SK = A.PROV_SK_ID
               --AND G.DL_ACTIVE_REC_IND = 'Y'
               )
       LEFT JOIN CHOICE.DIM_MEMBER_CARE_MANAGER@DL_CHOICE H
           ON (    H.CM_SK_ID = A.CM_SK_ID
               --AND H.DL_ACTIVE_REC_IND = 'Y'
               )
WHERE  AS_OF_MONTH_DT =
           (SELECT  /*+ driving_site(a)  cardinality(A 400000) no_merge */ MAX(AS_OF_MONTH_DT) FROM CHOICE.FCT_PMPM_ENROLLMENT@DL_CHOICE)


COMMENT ON MATERIALIZED VIEW CHOICEBI.V_FMM IS 'snapshot table for snapshot CHOICEBI.V_FMM';

GRANT SELECT ON CHOICEBI.V_FMM TO CHOICE;

GRANT SELECT ON CHOICEBI.V_FMM TO CHOICE_RO;

GRANT SELECT ON CHOICEBI.V_FMM TO RIPUL_P;
