DROP materialized view VW_PATIENT_RISK_CURRENT

create materialized view VW_PATIENT_RISK_CURRENT
REFRESH START WITH SYSDATE
NEXT trunc(SYSDATE) + 1  
as
SELECT
    D.UNIQUE_ID SUBSCRIBER_ID, 
    R.PATIENT_RISK_ID, 
    R.PATIENT_ID, 
    R.RISK_TYPE_ID, 
    R.RISK_SCORE, 
    R.CD_WEIGHT, 
    R.CD_SCORE, 
    R.LABEL, 
    R.CREATED_ON, 
    R.RISK_CATEGORY_ID, 
    R.STANDARD_INTERCEPT, 
    R.DEMO_INTERCEPT, 
    R.DIOGNSIS_INTERCEPT, 
    R.LOB_ID, IS_PRIMARY, 
    R.CREATED_BY, 
    R.UPDATED_BY, 
    R.UPDATED_ON, 
    R.DELETED_BY, 
    R.DELETED_ON, 
    R.JOB_RUN_ID, 
    R.SYS_UPD_TS
FROM CMGC.PATIENT_RISK R
JOIN (SELECT PATIENT_ID, MAX (PATIENT_RISK_ID) PATIENT_RISK_ID FROM CMGC.PATIENT_RISK GROUP BY PATIENT_ID) C ON R.PATIENT_ID = C.PATIENT_ID AND R.PATIENT_RISK_ID = C.PATIENT_RISK_ID
JOIN (select    distinct a11.PATIENT_ID  PATIENT_ID, a11.UNIQUE_ID  UNIQUE_ID from CMGC.PATIENT_DETAILS    a11) D on (R.PATIENT_ID = D.PATIENT_ID)

grant select on VW_PATIENT_RISK_CURRENT to mstrstg;

