SELECT 
    A.LINE_OF_BUSINESS, 
    A.MONTH_ID, 
    A.CHOICECNT, 
    B.FMMCNT, 
    A.CHOICECNT - B.FMMCNT DELTA 
FROM 
    (SELECT LINE_OF_BUSINESS, MONTH_ID, COUNT(*) CHOICECNT FROM V_DM_FACT_MEMBER_MONTH WHERE LINE_OF_BUSINESS IN ('MLTC','FIDA') GROUP BY LINE_OF_BUSINESS, MONTH_ID) A, 
    (SELECT LINE_OF_BUSINESS, MONTH_ID, COUNT(*) FMMCNT FROM MSTRSTG.FACT_MEMBER_MONTH WHERE LINE_OF_BUSINESS IN ('MLTC','FIDA') GROUP BY LINE_OF_BUSINESS, MONTH_ID) B
WHERE 
    A.LINE_OF_BUSINESS = B.LINE_OF_BUSINESS AND 
    A.MONTH_ID = B.MONTH_ID
ORDER BY 
    1,2;
--43863


CREATE OR REPLACE VIEW V_DM_FACT_MEMBER_MONTH AS
SELECT 
    'CHOICEDM' SOURCE,
    MRN,
    REPORTING_MONTH MONTH_ID,
    NULL PROGRAM,
    BOROUGH,
    COUNTY COUNTY_CODE,
    NULL TEAM,
    NULL STAFF_ID,
    MEDICAID_NUMBER MEDICAID_NUM,
    HICN MEDICARE_NUM,
    SUBSCRIBER_ID,
    C.BENEFIT_REGION,
    NULL UAS_DATE,
    ASSESS_NFLOC_SCORE UAS_NFLOC_SCORE,
    NULL REFERRAL_SOURCE,
    DISENROLL_RSN_CODE DC_REASON,
    DISENROLL_RSN_DESC DISENROLL_DISP,
    NULL AGE,
    1 FLAG,
    CASE_NBR,
    STATE STATE_CODE,
    ENROLLMENT_START_DT ENROLLMENT_DATE,
    ENROLLMENT_END_DT DISENROLLMENT_DATE,
    NEW_ENR_IND ENROLLED_FLAG,
    NEW_DISENR_IND DISENROLLED_FLAG,
    NULL PROJECTED,
    B.LOB LINE_OF_BUSINESS,
    NULL STATE_CASE_NUM,
    PROVIDER_ID,
    PCP_NAME PROVIDER_NAME,
    NULL MEDICAID_PRIOR_PLAN_ID,
    NULL MEDICAID_PRIOR_PLAN,
    NULL MEDICARE_PRIOR_PLAN,
    A.ENROLLMENT_STATUS STATUS,
    NULL PREVIOUSPLANEFFDATE,
    NULL MEDICAREAEFFDATE,
    NULL MEDICAREBEFFDATE,
    NULL PROGRAM_TERM_DT,
    REPORTING_MONTH MONTH,
    SSN,
    D.LAST_NAME,
    D.FIRST_NAME,
    DOB DATE_OF_BIRTH,
    SEX_CODE SEX,
    COUNTY,
    TO_CHAR(CASE_NBR) HIGHEST_CASE_NUMBER,
    NULL DISENROLLMENT_MONTH,
    B.CLASS_ID LOB_ID,
    A.ASSESSMENT_SK_ID UAS_RECORD_ID,
    NULL REFERRAL_DATE
FROM 
              CHOICE.FCT_PMPM_ENROLLMENT@DL_CHOICE A
    LEFT JOIN CHOICE.REF_PLAN@DL_CHOICE B ON (A.DL_PLAN_SK = B.DL_PLAN_SK )  
    LEFT JOIN CHOICE.DIM_MEMBER_ENROLLMENT@DL_CHOICE C ON (A.DL_ENRL_SK = C.DL_ENRL_SK AND C.DL_ACTIVE_REC_IND = 'Y')
    LEFT JOIN CHOICE.DIM_MEMBER@DL_CHOICE D ON (A.DL_MEMBER_SK = D.DL_MEMBER_SK AND D.DL_ACTIVE_REC_IND = 'Y' )
    LEFT JOIN CHOICE.DIM_MEMBER_ADDRESS@DL_CHOICE E ON (D.MEMBER_ID = E.MEMBER_ID AND E.DL_ACTIVE_REC_IND = 'Y' AND  ADDRESS_TYPE = 'H')
    LEFT JOIN CHOICE.DIM_MEMBER_ASSESSMENTS@DL_CHOICE F ON (F.DL_ASSESS_SK = A.ASSESSMENT_SK_ID)
    LEFT JOIN CHOICE.DIM_MEMBER_PRIMARY_PROVIDER@DL_CHOICE G ON (G.DL_PROV_SK = A.PROV_SK_ID AND G.DL_ACTIVE_REC_IND = 'Y')
    LEFT JOIN CHOICE.DIM_MEMBER_CARE_MANAGER@DL_CHOICE H ON (H.CM_SK_ID  = A.CM_SK_ID AND H.DL_ACTIVE_REC_IND = 'Y')
WHERE
    --REPORTING_MONTH = TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMM')) --AND B.CLASS_ID IN (2000,4000)    AND SUBSCRIBER_ID NOT LIKE 'V7%'
    AS_OF_MONTH_DT = TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMM'))