DROP VIEW DIM_MEMBER_DISENROLLMENT_AGG;

CREATE OR REPLACE VIEW DIM_MEMBER_DISENROLLMENT_AGG
(
    DISENROLLMENT_DT,
    DL_LOB_ID,
    MEMBER_ID,
    SUBSCRIBER_ID,
    HICN,
    LAST_NAME,
    FIRST_NAME,
    LOB,
    PROGRAM,
    DISENROLMENT_REASON_CODE,
    DISENROLL_RSN_DESC,
    DECEASED_DT,
    DISENROLL_RSN_TYPE
) AS
    SELECT   LAST_DAY(TO_DATE( TO_CHAR( A.ENROLLMENT_END_DT, 'YYYYMM') || '01', 'YYYYMMDD')) + 1 Disenrollment_Dt,
             DL_LOB_ID,
             B.MEMBER_ID,
             E.SUBSCRIBER_ID,
             B.HICN HICN,
             B.LAST_NAME,
             B.FIRST_NAME,
             A.LOB,
             A.PROGRAM,
             SUBSTR( LISTAGG( A.DISENROLL_RSN_CODE, ',') WITHIN GROUP (ORDER BY B.MEMBER_ID, B.HICN, TO_NUMBER(A.DISENROLL_RSN_CODE)), 1, 50) AS DISENROLMENT_REASON_CODE,
             SUBSTR( LISTAGG( D.DISENROLL_RSN_DESC, ',') WITHIN GROUP (ORDER BY B.MEMBER_ID, B.HICN, TO_NUMBER(A.DISENROLL_RSN_CODE)), 1, 50) AS DISENROLL_RSN_DESC,
             MIN(CASE WHEN A.DISENROLL_RSN_CODE IN ('90', '92') THEN A.ENROLLMENT_END_DT ELSE NULL END) DECEASED_DT,
             MIN(A.DISENROLL_RSN_TYPE) AS DISENROLL_RSN_TYPE
    FROM     choice.DIM_Member_disenrollment@dlake A
             INNER JOIN (SELECT *
                         FROM   CHOICE.DIM_MEMBER@dlake
                         WHERE  DL_ACTIVE_REC_IND = 'Y') B
                 ON A.member_id = B.member_id
             INNER JOIN choice.DIM_Member_enrollment@dlake E ON A.DL_ENRL_SK = E.DL_ENRL_SK
             LEFT JOIN CHOICE.REF_DISENROLLMENT_REASON@dlake D ON A.REF_DISENROLLMENT_RSN_SK = D.REF_DISENROLLMENT_RSN_SK
    WHERE    A.PROGRAM IN ('MA', 'FIDA') AND A.LOB IN ('MA', 'FIDA', 'MA AND MLTC','MAP') AND A.DL_ACTIVE_REC_IND = 'Y' AND A.NEXT_TRR_DT IS NULL
    GROUP BY DL_LOB_ID,
             B.MEMBER_ID,
             E.SUBSCRIBER_ID,
             B.HICN,
             B.LAST_NAME,
             B.FIRST_NAME,
             TO_CHAR( A.ENROLLMENT_END_DT, 'YYYYMM'),
             A.LOB,
             A.PROGRAM
    UNION
    SELECT LAST_DAY(TO_DATE( TO_CHAR( A.ENROLLMENT_END_DT, 'YYYYMM') || '01', 'YYYYMMDD')) + 1 Disenrollment_Dt,
           DL_LOB_ID,
           B.MEMBER_ID,
           E.SUBSCRIBER_ID,
           B.HICN HICN,
           B.LAST_NAME,
           B.FIRST_NAME,
           A.LOB,
           A.PROGRAM,
           A.DISENROLL_RSN_CODE AS DISENROLMENT_REASON_CODE,
           D.DISENROLL_RSN_DESC AS DISENROLL_RSN_DESC,
           CASE WHEN A.DISENROLL_RSN_CODE = 'DIED99' THEN A.ENROLLMENT_END_DT ELSE NULL END DECEASED_DT,
           D.DISENROLL_REASON_TYPE AS DISENROLL_RSN_TYPE
    FROM   choice.DIM_Member_disenrollment@dlake A
           INNER JOIN (SELECT *
                       FROM   CHOICE.DIM_MEMBER@dlake
                       WHERE  DL_ACTIVE_REC_IND = 'Y') B
               ON A.member_id = B.member_id
           INNER JOIN choice.DIM_Member_enrollment@dlake E ON A.DL_ENRL_SK = E.DL_ENRL_SK
           LEFT JOIN CHOICE.REF_DISENROLLMENT_REASON@dlake D ON A.REF_DISENROLLMENT_RSN_SK = D.REF_DISENROLLMENT_RSN_SK
    WHERE  A.PROGRAM IN ('MLTC') AND A.LOB IN ('MA AND MLTC','MAP', 'MLTC') AND A.DL_ACTIVE_REC_IND = 'Y' AND A.NEXT_TRR_DT IS NULL
    UNION
    SELECT LAST_DAY(TO_DATE( TO_CHAR( A.ENROLLMENT_END_DT, 'YYYYMM') || '01', 'YYYYMMDD')) + 1 Disenrollment_Dt,
           DL_LOB_ID,
           B.MEMBER_ID,
           E.SUBSCRIBER_ID,
           B.HICN HICN,
           B.LAST_NAME,
           B.FIRST_NAME,
           A.LOB,
           A.PROGRAM,
           A.DISENROLL_RSN_CODE AS DISENROLMENT_REASON_CODE,
           D.DISENROLL_RSN_DESC AS DISENROLL_RSN_DESC,
           CASE WHEN D.DISENROLL_RSN_DESC = 'DECEASED-TEST' THEN A.ENROLLMENT_END_DT ELSE NULL END DECEASED_DT,
           D.DISENROLL_REASON_TYPE AS DISENROLL_RSN_TYPE
    FROM   choice.DIM_Member_disenrollment@dlake A
           INNER JOIN (SELECT *
                       FROM   CHOICE.DIM_MEMBER@dlake
                       WHERE  DL_ACTIVE_REC_IND = 'Y') B
               ON A.member_id = B.member_id
           INNER JOIN choice.DIM_Member_enrollment@dlake E ON A.DL_ENRL_SK = E.DL_ENRL_SK
           LEFT JOIN CHOICE.REF_DISENROLLMENT_REASON@dlake D ON A.REF_DISENROLLMENT_RSN_SK = D.REF_DISENROLLMENT_RSN_SK
    WHERE  A.PROGRAM IN ('SH') AND A.LOB IN ('SH') AND A.DL_ACTIVE_REC_IND = 'Y' AND A.NEXT_TRR_DT IS NULL;


GRANT SELECT ON DIM_MEMBER_DISENROLLMENT_AGG TO MICHAEL_K;
