DROP VIEW CHOICEBI.DIM_PROVIDER;

CREATE OR REPLACE FORCE VIEW CHOICEBI.DIM_PROVIDER
AS
    SELECT /*+ driving_site(a) */
*    FROM   CHOICE.DIM_PROVIDER@DLAKE a;


GRANT SELECT ON CHOICEBI.DIM_PROVIDER TO MSTRSTG;