DROP VIEW FACT_MEMBER_ENROLL_PROD_AGG;

CREATE OR REPLACE VIEW FACT_MEMBER_ENROLL_PROD_AGG
(
    DL_LOB_ID_CEDL,
    DL_LOB_ID,
    DL_PLAN_SK,
    MEMBER_ID,
    SUBSCRIBER_ID,
    PRODUCT_ID,
    PRODUCT_NAME,
    ENROLLMENT_DATE,
    ENROLL_MONTH_ID,
    ENROLLMENT_FLAG
) AS
    SELECT a.DL_LOB_ID DL_LOB_ID_CEDL,
           CASE WHEN c.PROGRAM = 'MA' THEN 1 WHEN c.PROGRAM = 'MLTC' THEN 2 WHEN c.PROGRAM = 'SH' THEN 3 WHEN c.PROGRAM = 'FIDA' THEN 4 ELSE 0 END DL_LOB_ID,
           a.DL_PLAN_SK,
           a.MEMBER_ID,
           a.SUBSCRIBER_ID,
           a.PRODUCT_ID,
           a.PRODUCT_NAME,
           a.ENROLLMENT_START_DT ENROLLMENT_DATE,
           TO_CHAR( a.ENROLLMENT_START_DT, 'YYYYMM') ENROLL_MONTH_ID,
           1 ENROLLMENT_FLAG
    FROM   CHOICEBI.FACT_MEMBER_ENROLL_DISENROLL a, MSTRSTG.D_REF_PLAN c
    WHERE  ENROLLMENT_START_DT = PRODUCT_START_DT AND A.DL_PLAN_SK = c.DL_PLAN_SK


GRANT SELECT ON FACT_MEMBER_ENROLL_PROD_AGG TO MSTRSTG;
