DROP VIEW CHOICEBI.FACT_MEMBER_ENROLL_DETAIL;

CREATE OR REPLACE FORCE VIEW CHOICEBI.FACT_MEMBER_ENROLL_DETAIL
(
    DL_LOB_ID,
    ENROLLMENT_MONTH_ID,
    MEMBER_ID,
    SUBSCRIBER_ID,
    PRODUCT_ID,
    ENROLLMENT_DATE,
    ENROLLMENT_FLAG
) AS
    SELECT   DL_LOB_ID,
             TO_NUMBER(TO_CHAR(PRODUCT_START_DT, 'YYYYMM')) ENROLLMENT_MONTH_ID,
             MEMBER_ID,
             SUBSCRIBER_ID,
             PRODUCT_ID,
             PRODUCT_START_DT ENROLLMENT_DATE,
             1 ENROLLMENT_FLAG
    FROM     FACT_MEMBER_ENROLL_DISENROLL
    GROUP BY DL_LOB_ID,
             TO_NUMBER(TO_CHAR(PRODUCT_START_DT, 'YYYYMM')),
             MEMBER_ID,
             SUBSCRIBER_ID,
             PRODUCT_ID,
             PRODUCT_START_DT;


GRANT SELECT ON CHOICEBI.FACT_MEMBER_ENROLL_DETAIL TO MSTRSTG;
