DROP VIEW REF_MEMBER_DELEGATED_CM;

CREATE OR REPLACE VIEW REF_MEMBER_DELEGATED_CM
(
    DL_DELEGATED_CM_SK,
    DELEGATED_CM_DESC,
    DL_JOB_RUN_ID,
    DL_CRT_TS,
    DL_UPD_TS
) AS
    SELECT 
           "DELEGATED_CM_SK",
           "DELEGATED_CM_DESC",
           NULL "DL_JOB_RUN_ID",
           NULL "DL_CRT_TS",
           NULL "DL_UPD_TS"
    FROM   CHOICE.REF_MEMBER_DELEGATED_CM@dlake
    group by DELEGATED_CM_SK, DELEGATED_CM_DESC;


GRANT SELECT ON REF_MEMBER_DELEGATED_CM TO LINKADM;

GRANT SELECT ON REF_MEMBER_DELEGATED_CM TO MSTRSTG;

GRANT SELECT ON REF_MEMBER_DELEGATED_CM TO MSTRSTG2;

GRANT SELECT ON REF_MEMBER_DELEGATED_CM TO ROC_RO;



select * from REF_MEMBER_DELEGATED_CM