--create view 
create or replace view UAS_STD as   
WITH 
 UAS_SEC_A_BIN_TBL AS (SELECT A.RECORD_ID ,  A.PHYSORDER AS PHYSORDER_B,  A.GOALSMET AS GOALSMET_B,  A.RESHISTORYADULTCARE AS RESHISTORYADULTCARE_B,  A.RESHISTORYLTCFACILITY AS RESHISTORYLTCFACILITY_B,  A.RESHISTORYMENTAL AS RESHISTORYMENTAL_B,  A.RESHISTORYINTELLECTUAL AS RESHISTORYINTELLECTUAL_B,  A.RESHISTORYPSYCHIATRIC AS RESHISTORYPSYCHIATRIC_B,  A.RESHISTORYNURSINGHOME AS RESHISTORYNURSINGHOME_B,  A.RESHISTORYREHAB AS RESHISTORYREHAB_B,  A.RESHISTORYHOSPICE AS RESHISTORYHOSPICE_B,  A.RESHISTORYACUTE AS RESHISTORYACUTE_B,  A.RESHISTORYCORRECTIONAL AS RESHISTORYCORRECTIONAL_B,  A.RESHISTORYHOMELESS AS RESHISTORYHOMELESS_B,  A.RESHISTORYATTENDANCE AS RESHISTORYATTENDANCE_B,  A.RESHISTORYSTRUC AS RESHISTORYSTRUC_B,  A.RESHISTORYVOLUNTEERISM AS RESHISTORYVOLUNTEERISM_B,  A.RESHISTORYDAYPROGRAM AS RESHISTORYDAYPROGRAM_B, DECODE(A.LIVINGARRANGEMENT, 1, 1, NULL, NULL, 0) AS LIVINGARRANGEMENT_B FROM DW_OWNER.UAS_COMMUNITYHEALTH A)
,UAS_SEC_A_FCT_TBL AS (SELECT A.RECORD_ID , A1.DESCRIPTION AS ASSESSMENTREASON_F, A2.DESCRIPTION AS CHAREFERRALSOURCE_F, A3.DESCRIPTION AS RESIDENCEASSESSMENT_F, A4.DESCRIPTION AS LIVINGARRANGEMENT_F, A5.DESCRIPTION AS RESHISTORYEMPLYARR_F , DECODE(A.RESHISTORYEDUCATION, 8, NULL, A.RESHISTORYEDUCATION) AS RESHISTORYEDUCATION_O , CASE WHEN A.RESHISTORYEDUCATION = 8 OR A.RESHISTORYEDUCATION IS NULL THEN '8 - Unknown / No Selection' ELSE A.RESHISTORYEDUCATION || ' - ' ||A6.DESCRIPTION END AS RESHISTORYEDUCATION_F , CASE WHEN A.RESEMPLYSTATUS IS NULL THEN '99 - No Selection' ELSE A.RESEMPLYSTATUS || ' - ' || A7.DESCRIPTION END AS RESEMPLYSTATUS_F, DECODE(A.RESHISTORYSTRUC, 0, 'No', 1, 'Yes', 'No Selection') AS RESHISTORYSTRUC_F, DECODE(A.RESHISTORYVOLUNTEERISM, 0, 'No', 1, 'Yes', 'No Selection') AS RESHISTORYVOLUNTEERISM_F , DECODE(A.RESHISTORYDAYPROGRAM, 0, 'No', 1, 'Yes', 'No Selection') AS RESHISTORYDAYPROGRAM_F FROM DW_OWNER.UAS_COMMUNITYHEALTH A  LEFT JOIN DW_OWNER.DIM_U_ASSESSMENT_REASON A1 ON (COALESCE(TO_CHAR(A.ASSESSMENTREASON), 'XX')  = COALESCE(A1.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_U_REFERRAL_SOURCE_XF A2 ON (COALESCE(TO_CHAR(A.CHAREFERRALSOURCE), 'XX')  = COALESCE(A2.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_U_RES_LIV_STATUS A3 ON (COALESCE(TO_CHAR(A.RESIDENCEASSESSMENT), 'XX')  = COALESCE(A3.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_U_LIVING_ARRANGE A4 ON (COALESCE(TO_CHAR(A.LIVINGARRANGEMENT), 'XX')  = COALESCE(A4.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_U_RES_HISTORY_EMPLY_ARR A5 ON (COALESCE(TO_CHAR(A.RESHISTORYEMPLYARR), 'XX')  = COALESCE(A5.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_U_RES_HISTORY_EDUCATION A6 ON (COALESCE(TO_CHAR(A.RESHISTORYEDUCATION), 'XX')  = COALESCE(A6.ID, 'XX'))  LEFT JOIN DW_OWNER.DIM_U_RES_EMPLY_STATUS A7 ON (COALESCE(TO_CHAR(A.RESEMPLYSTATUS), 'XX')  = COALESCE(A7.ID, 'XX')))
,UAS_SEC_C1_TBL  AS (SELECT A.RECORD_ID , A.SELFUNDERSTOOD AS SELFUNDERSTOOD_O , CASE WHEN A.SELFUNDERSTOOD IS NULL THEN  '99 - No Selection' ELSE A.SELFUNDERSTOOD ||  ' - '  || TRIM(REGEXP_SUBSTR(C1.DESCRIPTION,'[^-]+',1,1)) END AS SELFUNDERSTOOD_F, A.UNDERSTANDOTHERS AS UNDERSTANDOTHERS_O , CASE WHEN A.UNDERSTANDOTHERS IS NULL THEN  '99 - No Selection' ELSE A.UNDERSTANDOTHERS ||  ' - '  || TRIM(REGEXP_SUBSTR(C2.DESCRIPTION,'[^-]+',1,1)) END AS UNDERSTANDOTHERS_F, A.HEARING AS HEARING_O , CASE WHEN A.HEARING IS NULL THEN  '99 - No Selection' ELSE A.HEARING ||  ' - '  || TRIM(REGEXP_SUBSTR(C3.DESCRIPTION,'[^-]+',1,1)) END AS HEARING_F, A.VISION AS VISION_O , CASE WHEN A.VISION IS NULL THEN  '99 - No Selection' ELSE A.VISION ||  ' - '  || TRIM(REGEXP_SUBSTR(C4.DESCRIPTION,'[^-]+',1,1)) END AS VISION_F FROM DW_OWNER.UAS_COMMUNITYHEALTH A  LEFT JOIN DW_OWNER.DIM_U_SELF_UNDERSTOOD C1 ON (COALESCE(TO_CHAR(A.SELFUNDERSTOOD), 'XX')  = COALESCE(C1.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_U_UNDERSTAND_OTHERS C2 ON (COALESCE(TO_CHAR(A.UNDERSTANDOTHERS), 'XX')  = COALESCE(C2.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_U_HEARING_XF C3 ON (COALESCE(TO_CHAR(A.HEARING), 'XX')  = COALESCE(C3.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_U_VISION C4 ON (COALESCE(TO_CHAR(A.VISION), 'XX')  = COALESCE(C4.ID, 'XX')))
,UAS_SEC_D1_TBL  AS (SELECT A.RECORD_ID , DECODE(A.NEGATIVESTATEMENTS, 8, NULL, A.NEGATIVESTATEMENTS) AS NEGATIVESTATEMENTS_O , CASE WHEN A.NEGATIVESTATEMENTS IS NULL THEN  '99 - No Selection' ELSE A.NEGATIVESTATEMENTS ||  ' - '  || D1.VAL END AS NEGATIVESTATEMENTS_F , DECODE(A.NEGATIVESTATEMENTS,0,0,NULL,NULL,1) AS NEGATIVESTATEMENTS_B, DECODE(A.PERSISTENTANGER, 8, NULL, A.PERSISTENTANGER) AS PERSISTENTANGER_O , CASE WHEN A.PERSISTENTANGER IS NULL THEN  '99 - No Selection' ELSE A.PERSISTENTANGER ||  ' - '  || D2.VAL END AS PERSISTENTANGER_F , DECODE(A.PERSISTENTANGER,0,0,NULL,NULL,1) AS PERSISTENTANGER_B, DECODE(A.UNREALFEARS, 8, NULL, A.UNREALFEARS) AS UNREALFEARS_O , CASE WHEN A.UNREALFEARS IS NULL THEN  '99 - No Selection' ELSE A.UNREALFEARS ||  ' - '  || D3.VAL END AS UNREALFEARS_F , DECODE(A.UNREALFEARS,0,0,NULL,NULL,1) AS UNREALFEARS_B, DECODE(A.HEALTHCOMPLAINTS, 8, NULL, A.HEALTHCOMPLAINTS) AS HEALTHCOMPLAINTS_O , CASE WHEN A.HEALTHCOMPLAINTS IS NULL THEN  '99 - No Selection' ELSE A.HEALTHCOMPLAINTS ||  ' - '  || D4.VAL END AS HEALTHCOMPLAINTS_F , DECODE(A.HEALTHCOMPLAINTS,0,0,NULL,NULL,1) AS HEALTHCOMPLAINTS_B, DECODE(A.ANXIOUSCOMPLAINTS, 8, NULL, A.ANXIOUSCOMPLAINTS) AS ANXIOUSCOMPLAINTS_O , CASE WHEN A.ANXIOUSCOMPLAINTS IS NULL THEN  '99 - No Selection' ELSE A.ANXIOUSCOMPLAINTS ||  ' - '  || D5.VAL END AS ANXIOUSCOMPLAINTS_F , DECODE(A.ANXIOUSCOMPLAINTS,0,0,NULL,NULL,1) AS ANXIOUSCOMPLAINTS_B, DECODE(A.SADFACIAL, 8, NULL, A.SADFACIAL) AS SADFACIAL_O , CASE WHEN A.SADFACIAL IS NULL THEN  '99 - No Selection' ELSE A.SADFACIAL ||  ' - '  || D6.VAL END AS SADFACIAL_F , DECODE(A.SADFACIAL,0,0,NULL,NULL,1) AS SADFACIAL_B, DECODE(A.CRYING, 8, NULL, A.CRYING) AS CRYING_O , CASE WHEN A.CRYING IS NULL THEN  '99 - No Selection' ELSE A.CRYING ||  ' - '  || D7.VAL END AS CRYING_F , DECODE(A.CRYING,0,0,NULL,NULL,1) AS CRYING_B, DECODE(A.WITHDRAWAL, 8, NULL, A.WITHDRAWAL) AS WITHDRAWAL_O , CASE WHEN A.WITHDRAWAL IS NULL THEN  '99 - No Selection' ELSE A.WITHDRAWAL ||  ' - '  || D8.VAL END AS WITHDRAWAL_F , DECODE(A.WITHDRAWAL,0,0,NULL,NULL,1) AS WITHDRAWAL_B, DECODE(A.REDUCEDSOCIAL, 8, NULL, A.REDUCEDSOCIAL) AS REDUCEDSOCIAL_O , CASE WHEN A.REDUCEDSOCIAL IS NULL THEN  '99 - No Selection' ELSE A.REDUCEDSOCIAL ||  ' - '  || D9.VAL END AS REDUCEDSOCIAL_F , DECODE(A.REDUCEDSOCIAL,0,0,NULL,NULL,1) AS REDUCEDSOCIAL_B, DECODE(A.BEHAVIORWANDERING, 8, NULL, A.BEHAVIORWANDERING) AS BEHAVIORWANDERING_O , CASE WHEN A.BEHAVIORWANDERING IS NULL THEN  '99 - No Selection' ELSE A.BEHAVIORWANDERING ||  ' - '  || D10.VAL END AS BEHAVIORWANDERING_F , DECODE(A.BEHAVIORWANDERING,0,0,NULL,NULL,1) AS BEHAVIORWANDERING_B, DECODE(A.BEHAVIORVERBAL, 8, NULL, A.BEHAVIORVERBAL) AS BEHAVIORVERBAL_O , CASE WHEN A.BEHAVIORVERBAL IS NULL THEN  '99 - No Selection' ELSE A.BEHAVIORVERBAL ||  ' - '  || D11.VAL END AS BEHAVIORVERBAL_F , DECODE(A.BEHAVIORVERBAL,0,0,NULL,NULL,1) AS BEHAVIORVERBAL_B, DECODE(A.BEHAVIORPHYSICAL, 8, NULL, A.BEHAVIORPHYSICAL) AS BEHAVIORPHYSICAL_O , CASE WHEN A.BEHAVIORPHYSICAL IS NULL THEN  '99 - No Selection' ELSE A.BEHAVIORPHYSICAL ||  ' - '  || D12.VAL END AS BEHAVIORPHYSICAL_F , DECODE(A.BEHAVIORPHYSICAL,0,0,NULL,NULL,1) AS BEHAVIORPHYSICAL_B, DECODE(A.BEHAVIORDISRUPTIVE, 8, NULL, A.BEHAVIORDISRUPTIVE) AS BEHAVIORDISRUPTIVE_O , CASE WHEN A.BEHAVIORDISRUPTIVE IS NULL THEN  '99 - No Selection' ELSE A.BEHAVIORDISRUPTIVE ||  ' - '  || D13.VAL END AS BEHAVIORDISRUPTIVE_F , DECODE(A.BEHAVIORDISRUPTIVE,0,0,NULL,NULL,1) AS BEHAVIORDISRUPTIVE_B, DECODE(A.BEHAVIORSEXUAL, 8, NULL, A.BEHAVIORSEXUAL) AS BEHAVIORSEXUAL_O , CASE WHEN A.BEHAVIORSEXUAL IS NULL THEN  '99 - No Selection' ELSE A.BEHAVIORSEXUAL ||  ' - '  || D14.VAL END AS BEHAVIORSEXUAL_F , DECODE(A.BEHAVIORSEXUAL,0,0,NULL,NULL,1) AS BEHAVIORSEXUAL_B, DECODE(A.BEHAVIORRESISTS, 8, NULL, A.BEHAVIORRESISTS) AS BEHAVIORRESISTS_O , CASE WHEN A.BEHAVIORRESISTS IS NULL THEN  '99 - No Selection' ELSE A.BEHAVIORRESISTS ||  ' - '  || D15.VAL END AS BEHAVIORRESISTS_F , DECODE(A.BEHAVIORRESISTS,0,0,NULL,NULL,1) AS BEHAVIORRESISTS_B FROM DW_OWNER.UAS_COMMUNITYHEALTH A  LEFT JOIN DW_OWNER.DIM_UAS_NEGATIVE_STATEMENTS_CA D1 ON (COALESCE(TO_CHAR(A.NEGATIVESTATEMENTS), 'XX')  = COALESCE(D1.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PERSISTENT_ANGER_CA D2 ON (COALESCE(TO_CHAR(A.PERSISTENTANGER), 'XX')  = COALESCE(D2.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_UNREAL_FEARS_CA D3 ON (COALESCE(TO_CHAR(A.UNREALFEARS), 'XX')  = COALESCE(D3.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_HEALTH_COMPLAINTS_CA D4 ON (COALESCE(TO_CHAR(A.HEALTHCOMPLAINTS), 'XX')  = COALESCE(D4.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_ANXIOUS_COMPLAINTS_CA D5 ON (COALESCE(TO_CHAR(A.ANXIOUSCOMPLAINTS), 'XX')  = COALESCE(D5.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_SAD_FACIAL_CA D6 ON (COALESCE(TO_CHAR(A.SADFACIAL), 'XX')  = COALESCE(D6.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_CRYING_CA D7 ON (COALESCE(TO_CHAR(A.CRYING), 'XX')  = COALESCE(D7.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_WITHDRAWAL_CA D8 ON (COALESCE(TO_CHAR(A.WITHDRAWAL), 'XX')  = COALESCE(D8.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_REDUCED_SOCIAL_CA D9 ON (COALESCE(TO_CHAR(A.REDUCEDSOCIAL), 'XX')  = COALESCE(D9.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_BEHAVIOR_WANDERING_CA D10 ON (COALESCE(TO_CHAR(A.BEHAVIORWANDERING), 'XX')  = COALESCE(D10.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_BEHAVIOR_VERBAL_CA D11 ON (COALESCE(TO_CHAR(A.BEHAVIORVERBAL), 'XX')  = COALESCE(D11.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_BEHAVIOR_PHYSICAL_CA D12 ON (COALESCE(TO_CHAR(A.BEHAVIORPHYSICAL), 'XX')  = COALESCE(D12.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_BEHAVIOR_DISRUPTIVE_CA D13 ON (COALESCE(TO_CHAR(A.BEHAVIORDISRUPTIVE), 'XX')  = COALESCE(D13.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_BEHAVIOR_SEXUAL_CA D14 ON (COALESCE(TO_CHAR(A.BEHAVIORSEXUAL), 'XX')  = COALESCE(D14.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_BEHAVIOR_RESISTS_CA D15 ON (COALESCE(TO_CHAR(A.BEHAVIORRESISTS), 'XX')  = COALESCE(D15.ID, 'XX')))
,UAS_SEC_D2_TBL  AS (SELECT A.RECORD_ID , DECODE(A.MOODINTEREST, 8, NULL, A.MOODINTEREST) AS MOODINTEREST_O , CASE WHEN A.MOODINTEREST IS NULL THEN  '99 - No Selection' ELSE A.MOODINTEREST ||  ' - '  || D1.VAL END AS MOODINTEREST_F , DECODE(A.MOODINTEREST,0,0,1,0, 2,1,3,1,8,NULL,A.MOODINTEREST) AS MOODINTEREST_B, DECODE(A.MOODANXIOUS, 8, NULL, A.MOODANXIOUS) AS MOODANXIOUS_O , CASE WHEN A.MOODANXIOUS IS NULL THEN  '99 - No Selection' ELSE A.MOODANXIOUS ||  ' - '  || D2.VAL END AS MOODANXIOUS_F , DECODE(A.MOODANXIOUS,0,0,1,0, 2,1,3,1,8,NULL,A.MOODANXIOUS) AS MOODANXIOUS_B, DECODE(A.MOODSAD, 8, NULL, A.MOODSAD) AS MOODSAD_O , CASE WHEN A.MOODSAD IS NULL THEN  '99 - No Selection' ELSE A.MOODSAD ||  ' - '  || D3.VAL END AS MOODSAD_F , DECODE(A.MOODSAD,0,0,1,0, 2,1,3,1,8,NULL,A.MOODSAD) AS MOODSAD_B FROM DW_OWNER.UAS_COMMUNITYHEALTH A  LEFT JOIN DW_OWNER.DIM_UAS_MOOD_INTEREST_CA D1 ON (COALESCE(TO_CHAR(A.MOODINTEREST), 'XX')  = COALESCE(D1.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_MOOD_ANXIOUS_CA D2 ON (COALESCE(TO_CHAR(A.MOODANXIOUS), 'XX')  = COALESCE(D2.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_MOOD_SAD_CA D3 ON (COALESCE(TO_CHAR(A.MOODSAD), 'XX')  = COALESCE(D3.ID, 'XX')))
,UAS_SEC_E1_TBL   AS (SELECT A.RECORD_ID ,  DECODE(A.SOCIALPARTICIPATION, 8, NULL, A.SOCIALPARTICIPATION) AS SOCIALPARTICIPATION_O ,  CASE WHEN A.SOCIALPARTICIPATION IS NULL THEN '99 - No Selection' ELSE A.SOCIALPARTICIPATION || ' - ' || E1.VAL END AS SOCIALPARTICIPATION_F , DECODE(A.SOCIALPARTICIPATION,0,0,8,NULL, NULL,NULL,1) AS SOCIALPARTICIPATION_B,  DECODE(A.SOCIALVISIT, 8, NULL, A.SOCIALVISIT) AS SOCIALVISIT_O ,  CASE WHEN A.SOCIALVISIT IS NULL THEN '99 - No Selection' ELSE A.SOCIALVISIT || ' - ' || E2.VAL END AS SOCIALVISIT_F , DECODE(A.SOCIALVISIT,0,0,8,NULL, NULL,NULL,1) AS SOCIALVISIT_B,  DECODE(A.SOCIALOTHERINTERACTION, 8, NULL, A.SOCIALOTHERINTERACTION) AS SOCIALOTHERINTERACTION_O ,  CASE WHEN A.SOCIALOTHERINTERACTION IS NULL THEN '99 - No Selection' ELSE A.SOCIALOTHERINTERACTION || ' - ' || E3.VAL END AS SOCIALOTHERINTERACTION_F , DECODE(A.SOCIALOTHERINTERACTION,0,0,8,NULL, NULL,NULL,1) AS SOCIALOTHERINTERACTION_B,  DECODE(A.SOCIALEXPRESSANGER, 8, NULL, A.SOCIALEXPRESSANGER) AS SOCIALEXPRESSANGER_O ,  CASE WHEN A.SOCIALEXPRESSANGER IS NULL THEN '99 - No Selection' ELSE A.SOCIALEXPRESSANGER || ' - ' || E4.VAL END AS SOCIALEXPRESSANGER_F , DECODE(A.SOCIALEXPRESSANGER,0,0,8,NULL, NULL,NULL,1) AS SOCIALEXPRESSANGER_B,  DECODE(A.SOCIALFEARFUL, 8, NULL, A.SOCIALFEARFUL) AS SOCIALFEARFUL_O ,  CASE WHEN A.SOCIALFEARFUL IS NULL THEN '99 - No Selection' ELSE A.SOCIALFEARFUL || ' - ' || E5.VAL END AS SOCIALFEARFUL_F , DECODE(A.SOCIALFEARFUL,0,0,8,NULL, NULL,NULL,1) AS SOCIALFEARFUL_B,  DECODE(A.SOCIALNEGLECTED, 8, NULL, A.SOCIALNEGLECTED) AS SOCIALNEGLECTED_O ,  CASE WHEN A.SOCIALNEGLECTED IS NULL THEN '99 - No Selection' ELSE A.SOCIALNEGLECTED || ' - ' || E6.VAL END AS SOCIALNEGLECTED_F , DECODE(A.SOCIALNEGLECTED,0,0,8,NULL, NULL,NULL,1) AS SOCIALNEGLECTED_B FROM DW_OWNER.UAS_COMMUNITYHEALTH A  LEFT JOIN DW_OWNER.DIM_UAS_SOCIAL_PARTICIPATION E1 ON (COALESCE(TO_CHAR(A.SOCIALPARTICIPATION), 'XX')  = COALESCE(E1.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_SOCIAL_VISIT E2 ON (COALESCE(TO_CHAR(A.SOCIALVISIT), 'XX')  = COALESCE(E2.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_SOCIAL_OTHER_INTERACTN E3 ON (COALESCE(TO_CHAR(A.SOCIALOTHERINTERACTION), 'XX')  = COALESCE(E3.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_SOCIAL_EXPRESS_ANGER E4 ON (COALESCE(TO_CHAR(A.SOCIALEXPRESSANGER), 'XX')  = COALESCE(E4.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_SOCIAL_FEARFUL E5 ON (COALESCE(TO_CHAR(A.SOCIALFEARFUL), 'XX')  = COALESCE(E5.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_SOCIAL_NEGLECTED E6 ON (COALESCE(TO_CHAR(A.SOCIALNEGLECTED), 'XX')  = COALESCE(E6.ID, 'XX')))
,UAS_SEC_F1_TBL   AS (SELECT A.RECORD_ID  ,  DECODE(A.IADLPERFORMANCEMEALS, 8, NULL, A.IADLPERFORMANCEMEALS) AS IADLPERFORMANCEMEALS_O ,  CASE WHEN A.IADLPERFORMANCEMEALS IS NULL THEN '99 - No Selection' ELSE A.IADLPERFORMANCEMEALS|| ' - ' ||TRIM(REGEXP_SUBSTR(F1.VAL,'[^-]+',1,1)) END AS IADLPERFORMANCEMEALS_F ,  DECODE(A.IADLCAPACITYMEALS, 8, NULL, A.IADLCAPACITYMEALS) AS IADLCAPACITYMEALS_O ,  CASE WHEN A.IADLCAPACITYMEALS IS NULL THEN '99 - No Selection' ELSE A.IADLCAPACITYMEALS|| ' - ' ||TRIM(REGEXP_SUBSTR(F2.VAL,'[^-]+',1,1)) END AS IADLCAPACITYMEALS_F ,  DECODE(A.IADLPERFORMANCEHOUSEWORK, 8, NULL, A.IADLPERFORMANCEHOUSEWORK) AS IADLPERFORMANCEHOUSEWORK_O ,  CASE WHEN A.IADLPERFORMANCEHOUSEWORK IS NULL THEN '99 - No Selection' ELSE A.IADLPERFORMANCEHOUSEWORK|| ' - ' ||TRIM(REGEXP_SUBSTR(F3.VAL,'[^-]+',1,1)) END AS IADLPERFORMANCEHOUSEWORK_F ,  DECODE(A.IADLCAPACITYHOUSEWORK, 8, NULL, A.IADLCAPACITYHOUSEWORK) AS IADLCAPACITYHOUSEWORK_O ,  CASE WHEN A.IADLCAPACITYHOUSEWORK IS NULL THEN '99 - No Selection' ELSE A.IADLCAPACITYHOUSEWORK|| ' - ' ||TRIM(REGEXP_SUBSTR(F4.VAL,'[^-]+',1,1)) END AS IADLCAPACITYHOUSEWORK_F ,  DECODE(A.IADLPERFORMANCEFINANCES, 8, NULL, A.IADLPERFORMANCEFINANCES) AS IADLPERFORMANCEFINANCES_O ,  CASE WHEN A.IADLPERFORMANCEFINANCES IS NULL THEN '99 - No Selection' ELSE A.IADLPERFORMANCEFINANCES|| ' - ' ||TRIM(REGEXP_SUBSTR(F5.VAL,'[^-]+',1,1)) END AS IADLPERFORMANCEFINANCES_F ,  DECODE(A.IADLCAPACITYFINANCES, 8, NULL, A.IADLCAPACITYFINANCES) AS IADLCAPACITYFINANCES_O ,  CASE WHEN A.IADLCAPACITYFINANCES IS NULL THEN '99 - No Selection' ELSE A.IADLCAPACITYFINANCES|| ' - ' ||TRIM(REGEXP_SUBSTR(F6.VAL,'[^-]+',1,1)) END AS IADLCAPACITYFINANCES_F ,  DECODE(A.IADLPERFORMANCEMEDS, 8, NULL, A.IADLPERFORMANCEMEDS) AS IADLPERFORMANCEMEDS_O ,  CASE WHEN A.IADLPERFORMANCEMEDS IS NULL THEN '99 - No Selection' ELSE A.IADLPERFORMANCEMEDS|| ' - ' ||TRIM(REGEXP_SUBSTR(F7.VAL,'[^-]+',1,1)) END AS IADLPERFORMANCEMEDS_F ,  DECODE(A.IADLCAPACITYMEDS, 8, NULL, A.IADLCAPACITYMEDS) AS IADLCAPACITYMEDS_O ,  CASE WHEN A.IADLCAPACITYMEDS IS NULL THEN '99 - No Selection' ELSE A.IADLCAPACITYMEDS|| ' - ' ||TRIM(REGEXP_SUBSTR(F8.VAL,'[^-]+',1,1)) END AS IADLCAPACITYMEDS_F ,  DECODE(A.IADLPERFORMANCEPHONE, 8, NULL, A.IADLPERFORMANCEPHONE) AS IADLPERFORMANCEPHONE_O ,  CASE WHEN A.IADLPERFORMANCEPHONE IS NULL THEN '99 - No Selection' ELSE A.IADLPERFORMANCEPHONE|| ' - ' ||TRIM(REGEXP_SUBSTR(F9.VAL,'[^-]+',1,1)) END AS IADLPERFORMANCEPHONE_F ,  DECODE(A.IADLCAPACITYPHONE, 8, NULL, A.IADLCAPACITYPHONE) AS IADLCAPACITYPHONE_O ,  CASE WHEN A.IADLCAPACITYPHONE IS NULL THEN '99 - No Selection' ELSE A.IADLCAPACITYPHONE|| ' - ' ||TRIM(REGEXP_SUBSTR(F10.VAL,'[^-]+',1,1)) END AS IADLCAPACITYPHONE_F ,  DECODE(A.IADLPERFORMANCESTAIRS, 8, NULL, A.IADLPERFORMANCESTAIRS) AS IADLPERFORMANCESTAIRS_O ,  CASE WHEN A.IADLPERFORMANCESTAIRS IS NULL THEN '99 - No Selection' ELSE A.IADLPERFORMANCESTAIRS|| ' - ' ||TRIM(REGEXP_SUBSTR(F11.VAL,'[^-]+',1,1)) END AS IADLPERFORMANCESTAIRS_F ,  DECODE(A.IADLCAPACITYSTAIRS, 8, NULL, A.IADLCAPACITYSTAIRS) AS IADLCAPACITYSTAIRS_O ,  CASE WHEN A.IADLCAPACITYSTAIRS IS NULL THEN '99 - No Selection' ELSE A.IADLCAPACITYSTAIRS|| ' - ' ||TRIM(REGEXP_SUBSTR(F12.VAL,'[^-]+',1,1)) END AS IADLCAPACITYSTAIRS_F ,  DECODE(A.IADLPERFORMANCESHOPPING, 8, NULL, A.IADLPERFORMANCESHOPPING) AS IADLPERFORMANCESHOPPING_O ,  CASE WHEN A.IADLPERFORMANCESHOPPING IS NULL THEN '99 - No Selection' ELSE A.IADLPERFORMANCESHOPPING|| ' - ' ||TRIM(REGEXP_SUBSTR(F13.VAL,'[^-]+',1,1)) END AS IADLPERFORMANCESHOPPING_F ,  DECODE(A.IADLCAPACITYSHOPPING, 8, NULL, A.IADLCAPACITYSHOPPING) AS IADLCAPACITYSHOPPING_O ,  CASE WHEN A.IADLCAPACITYSHOPPING IS NULL THEN '99 - No Selection' ELSE A.IADLCAPACITYSHOPPING|| ' - ' ||TRIM(REGEXP_SUBSTR(F14.VAL,'[^-]+',1,1)) END AS IADLCAPACITYSHOPPING_F ,  DECODE(A.IADLPERFORMANCETRANSPORT, 8, NULL, A.IADLPERFORMANCETRANSPORT) AS IADLPERFORMANCETRANSPORT_O ,  CASE WHEN A.IADLPERFORMANCETRANSPORT IS NULL THEN '99 - No Selection' ELSE A.IADLPERFORMANCETRANSPORT|| ' - ' ||TRIM(REGEXP_SUBSTR(F15.VAL,'[^-]+',1,1)) END AS IADLPERFORMANCETRANSPORT_F ,  DECODE(A.IADLCAPACITYTRANSPORT, 8, NULL, A.IADLCAPACITYTRANSPORT) AS IADLCAPACITYTRANSPORT_O ,  CASE WHEN A.IADLCAPACITYTRANSPORT IS NULL THEN '99 - No Selection' ELSE A.IADLCAPACITYTRANSPORT|| ' - ' ||TRIM(REGEXP_SUBSTR(F16.VAL,'[^-]+',1,1)) END AS IADLCAPACITYTRANSPORT_F ,  DECODE(A.IADLPERFORMANCEEQUIP, 8, NULL, A.IADLPERFORMANCEEQUIP) AS IADLPERFORMANCEEQUIP_O ,  CASE WHEN A.IADLPERFORMANCEEQUIP IS NULL THEN '99 - No Selection' ELSE A.IADLPERFORMANCEEQUIP|| ' - ' ||TRIM(REGEXP_SUBSTR(F17.VAL,'[^-]+',1,1)) END AS IADLPERFORMANCEEQUIP_F ,  DECODE(A.IADLCAPACITYEQUIP, 8, NULL, A.IADLCAPACITYEQUIP) AS IADLCAPACITYEQUIP_O ,  CASE WHEN A.IADLCAPACITYEQUIP IS NULL THEN '99 - No Selection' ELSE A.IADLCAPACITYEQUIP|| ' - ' ||TRIM(REGEXP_SUBSTR(F18.VAL,'[^-]+',1,1)) END AS IADLCAPACITYEQUIP_F FROM DW_OWNER.UAS_COMMUNITYHEALTH A  LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F1 ON (COALESCE(TO_CHAR(A.IADLPERFORMANCEMEALS), 'XX')  = COALESCE(F1.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F2 ON (COALESCE(TO_CHAR(A.IADLCAPACITYMEALS), 'XX')  = COALESCE(F2.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F3 ON (COALESCE(TO_CHAR(A.IADLPERFORMANCEHOUSEWORK), 'XX')  = COALESCE(F3.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F4 ON (COALESCE(TO_CHAR(A.IADLCAPACITYHOUSEWORK), 'XX')  = COALESCE(F4.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F5 ON (COALESCE(TO_CHAR(A.IADLPERFORMANCEFINANCES), 'XX')  = COALESCE(F5.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F6 ON (COALESCE(TO_CHAR(A.IADLCAPACITYFINANCES), 'XX')  = COALESCE(F6.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F7 ON (COALESCE(TO_CHAR(A.IADLPERFORMANCEMEDS), 'XX')  = COALESCE(F7.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F8 ON (COALESCE(TO_CHAR(A.IADLCAPACITYMEDS), 'XX')  = COALESCE(F8.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F9 ON (COALESCE(TO_CHAR(A.IADLPERFORMANCEPHONE), 'XX')  = COALESCE(F9.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F10 ON (COALESCE(TO_CHAR(A.IADLCAPACITYPHONE), 'XX')  = COALESCE(F10.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F11 ON (COALESCE(TO_CHAR(A.IADLPERFORMANCESTAIRS), 'XX')  = COALESCE(F11.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F12 ON (COALESCE(TO_CHAR(A.IADLCAPACITYSTAIRS), 'XX')  = COALESCE(F12.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F13 ON (COALESCE(TO_CHAR(A.IADLPERFORMANCESHOPPING), 'XX')  = COALESCE(F13.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F14 ON (COALESCE(TO_CHAR(A.IADLCAPACITYSHOPPING), 'XX')  = COALESCE(F14.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F15 ON (COALESCE(TO_CHAR(A.IADLPERFORMANCETRANSPORT), 'XX')  = COALESCE(F15.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F16 ON (COALESCE(TO_CHAR(A.IADLCAPACITYTRANSPORT), 'XX')  = COALESCE(F16.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F17 ON (COALESCE(TO_CHAR(A.IADLPERFORMANCEEQUIP), 'XX')  = COALESCE(F17.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_IADL_PERFORMANCE_MEALS F18 ON (COALESCE(TO_CHAR(A.IADLCAPACITYEQUIP), 'XX')  = COALESCE(F18.ID, 'XX')))
,UAS_SEC_F2_TBL AS (SELECT A.RECORD_ID  ,  DECODE(A.ADLBATHING, 8, NULL, A.ADLBATHING) AS ADLBATHING_O ,  CASE WHEN A.ADLBATHING IS NULL THEN '99 - No Selection' ELSE A.ADLBATHING|| ' - ' ||TRIM(REGEXP_SUBSTR(F1.VAL,'[^-]+',1,1)) END AS ADLBATHING_F ,  DECODE(A.ADLHYGIENE, 8, NULL, A.ADLHYGIENE) AS ADLHYGIENE_O ,  CASE WHEN A.ADLHYGIENE IS NULL THEN '99 - No Selection' ELSE A.ADLHYGIENE|| ' - ' ||TRIM(REGEXP_SUBSTR(F2.VAL,'[^-]+',1,1)) END AS ADLHYGIENE_F ,  DECODE(A.ADLDRESSUPPER, 8, NULL, A.ADLDRESSUPPER) AS ADLDRESSUPPER_O ,  CASE WHEN A.ADLDRESSUPPER IS NULL THEN '99 - No Selection' ELSE A.ADLDRESSUPPER|| ' - ' ||TRIM(REGEXP_SUBSTR(F3.VAL,'[^-]+',1,1)) END AS ADLDRESSUPPER_F ,  DECODE(A.ADLDRESSLOWER, 8, NULL, A.ADLDRESSLOWER) AS ADLDRESSLOWER_O ,  CASE WHEN A.ADLDRESSLOWER IS NULL THEN '99 - No Selection' ELSE A.ADLDRESSLOWER|| ' - ' ||TRIM(REGEXP_SUBSTR(F4.VAL,'[^-]+',1,1)) END AS ADLDRESSLOWER_F ,  DECODE(A.ADLWALKING, 8, NULL, A.ADLWALKING) AS ADLWALKING_O ,  CASE WHEN A.ADLWALKING IS NULL THEN '99 - No Selection' ELSE A.ADLWALKING|| ' - ' ||TRIM(REGEXP_SUBSTR(F5.VAL,'[^-]+',1,1)) END AS ADLWALKING_F ,  DECODE(A.ADLLOCOMOTION, 8, NULL, A.ADLLOCOMOTION) AS ADLLOCOMOTION_O ,  CASE WHEN A.ADLLOCOMOTION IS NULL THEN '99 - No Selection' ELSE A.ADLLOCOMOTION|| ' - ' ||TRIM(REGEXP_SUBSTR(F6.VAL,'[^-]+',1,1)) END AS ADLLOCOMOTION_F ,  DECODE(A.ADLTOILETTRANSFER, 8, NULL, A.ADLTOILETTRANSFER) AS ADLTOILETTRANSFER_O ,  CASE WHEN A.ADLTOILETTRANSFER IS NULL THEN '99 - No Selection' ELSE A.ADLTOILETTRANSFER|| ' - ' ||TRIM(REGEXP_SUBSTR(F7.VAL,'[^-]+',1,1)) END AS ADLTOILETTRANSFER_F ,  DECODE(A.ADLTOILETUSE, 8, NULL, A.ADLTOILETUSE) AS ADLTOILETUSE_O ,  CASE WHEN A.ADLTOILETUSE IS NULL THEN '99 - No Selection' ELSE A.ADLTOILETUSE|| ' - ' ||TRIM(REGEXP_SUBSTR(F8.VAL,'[^-]+',1,1)) END AS ADLTOILETUSE_F ,  DECODE(A.ADLBED, 8, NULL, A.ADLBED) AS ADLBED_O ,  CASE WHEN A.ADLBED IS NULL THEN '99 - No Selection' ELSE A.ADLBED|| ' - ' ||TRIM(REGEXP_SUBSTR(F9.VAL,'[^-]+',1,1)) END AS ADLBED_F ,  DECODE(A.ADLEATING, 8, NULL, A.ADLEATING) AS ADLEATING_O ,  CASE WHEN A.ADLEATING IS NULL THEN '99 - No Selection' ELSE A.ADLEATING|| ' - ' ||TRIM(REGEXP_SUBSTR(F10.VAL,'[^-]+',1,1)) END AS ADLEATING_F FROM DW_OWNER.UAS_COMMUNITYHEALTH A  LEFT JOIN DW_OWNER.DIM_UAS_ADL_BATHING F1 ON (COALESCE(TO_CHAR(A.ADLBATHING), 'XX')  = COALESCE(F1.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_ADL_BATHING F2 ON (COALESCE(TO_CHAR(A.ADLHYGIENE), 'XX')  = COALESCE(F2.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_ADL_BATHING F3 ON (COALESCE(TO_CHAR(A.ADLDRESSUPPER), 'XX')  = COALESCE(F3.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_ADL_BATHING F4 ON (COALESCE(TO_CHAR(A.ADLDRESSLOWER), 'XX')  = COALESCE(F4.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_ADL_BATHING F5 ON (COALESCE(TO_CHAR(A.ADLWALKING), 'XX')  = COALESCE(F5.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_ADL_BATHING F6 ON (COALESCE(TO_CHAR(A.ADLLOCOMOTION), 'XX')  = COALESCE(F6.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_ADL_BATHING F7 ON (COALESCE(TO_CHAR(A.ADLTOILETTRANSFER), 'XX')  = COALESCE(F7.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_ADL_BATHING F8 ON (COALESCE(TO_CHAR(A.ADLTOILETUSE), 'XX')  = COALESCE(F8.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_ADL_BATHING F9 ON (COALESCE(TO_CHAR(A.ADLBED), 'XX')  = COALESCE(F9.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_ADL_BATHING F10 ON (COALESCE(TO_CHAR(A.ADLEATING), 'XX')  = COALESCE(F10.ID, 'XX')))
,UAS_SEC_H1_TBL  AS (SELECT A.RECORD_ID ,  A.MUSCULOSKELETALHIP AS MUSCULOSKELETALHIP_O,  CASE WHEN A.MUSCULOSKELETALHIP IS NULL THEN '99 - No Selection' ELSE A.MUSCULOSKELETALHIP|| ' - ' ||H1.VAL END AS MUSCULOSKELETALHIP_F, DECODE(A.MUSCULOSKELETALHIP,0,0,NULL,NULL,1) AS MUSCULOSKELETALHIP_B,  A.MUSCULOSKELETALOTHERFRACTURE AS MUSCULOSKELETALOTHERFRACTURE_O,  CASE WHEN A.MUSCULOSKELETALOTHERFRACTURE IS NULL THEN '99 - No Selection' ELSE A.MUSCULOSKELETALOTHERFRACTURE|| ' - ' ||H2.VAL END AS MUSCULOSKELETALOTHERFRACTURE_F, DECODE(A.MUSCULOSKELETALOTHERFRACTURE,0,0,NULL,NULL,1) AS MUSCULOSKELETALOTHERFRACTURE_B,  A.NEUROLOGICALALZHEIMERS AS NEUROLOGICALALZHEIMERS_O,  CASE WHEN A.NEUROLOGICALALZHEIMERS IS NULL THEN '99 - No Selection' ELSE A.NEUROLOGICALALZHEIMERS|| ' - ' ||H3.VAL END AS NEUROLOGICALALZHEIMERS_F, DECODE(A.NEUROLOGICALALZHEIMERS,0,0,NULL,NULL,1) AS NEUROLOGICALALZHEIMERS_B,  A.NEUROLOGICALDEMENTIA AS NEUROLOGICALDEMENTIA_O,  CASE WHEN A.NEUROLOGICALDEMENTIA IS NULL THEN '99 - No Selection' ELSE A.NEUROLOGICALDEMENTIA|| ' - ' ||H4.VAL END AS NEUROLOGICALDEMENTIA_F, DECODE(A.NEUROLOGICALDEMENTIA,0,0,NULL,NULL,1) AS NEUROLOGICALDEMENTIA_B,  A.NEUROLOGICALSTROKE AS NEUROLOGICALSTROKE_O,  CASE WHEN A.NEUROLOGICALSTROKE IS NULL THEN '99 - No Selection' ELSE A.NEUROLOGICALSTROKE|| ' - ' ||H5.VAL END AS NEUROLOGICALSTROKE_F, DECODE(A.NEUROLOGICALSTROKE,0,0,NULL,NULL,1) AS NEUROLOGICALSTROKE_B,  A.CARDIACHEARTDISEASE AS CARDIACHEARTDISEASE_O,  CASE WHEN A.CARDIACHEARTDISEASE IS NULL THEN '99 - No Selection' ELSE A.CARDIACHEARTDISEASE|| ' - ' ||H6.VAL END AS CARDIACHEARTDISEASE_F, DECODE(A.CARDIACHEARTDISEASE,0,0,NULL,NULL,1) AS CARDIACHEARTDISEASE_B,  A.CARDIACPULMONARY AS CARDIACPULMONARY_O,  CASE WHEN A.CARDIACPULMONARY IS NULL THEN '99 - No Selection' ELSE A.CARDIACPULMONARY|| ' - ' ||H7.VAL END AS CARDIACPULMONARY_F, DECODE(A.CARDIACPULMONARY,0,0,NULL,NULL,1) AS CARDIACPULMONARY_B,  A.CARDIACFAILURE AS CARDIACFAILURE_O,  CASE WHEN A.CARDIACFAILURE IS NULL THEN '99 - No Selection' ELSE A.CARDIACFAILURE|| ' - ' ||H8.VAL END AS CARDIACFAILURE_F, DECODE(A.CARDIACFAILURE,0,0,NULL,NULL,1) AS CARDIACFAILURE_B,  A.PSYCHIATRICANXIETY AS PSYCHIATRICANXIETY_O,  CASE WHEN A.PSYCHIATRICANXIETY IS NULL THEN '99 - No Selection' ELSE A.PSYCHIATRICANXIETY|| ' - ' ||H9.VAL END AS PSYCHIATRICANXIETY_F, DECODE(A.PSYCHIATRICANXIETY,0,0,NULL,NULL,1) AS PSYCHIATRICANXIETY_B,  A.PSYCHIATRICBIPOLAR AS PSYCHIATRICBIPOLAR_O,  CASE WHEN A.PSYCHIATRICBIPOLAR IS NULL THEN '99 - No Selection' ELSE A.PSYCHIATRICBIPOLAR|| ' - ' ||H10.VAL END AS PSYCHIATRICBIPOLAR_F, DECODE(A.PSYCHIATRICBIPOLAR,0,0,NULL,NULL,1) AS PSYCHIATRICBIPOLAR_B,  A.PSYCHIATRICDEPRESSION AS PSYCHIATRICDEPRESSION_O,  CASE WHEN A.PSYCHIATRICDEPRESSION IS NULL THEN '99 - No Selection' ELSE A.PSYCHIATRICDEPRESSION|| ' - ' ||H11.VAL END AS PSYCHIATRICDEPRESSION_F, DECODE(A.PSYCHIATRICDEPRESSION,0,0,NULL,NULL,1) AS PSYCHIATRICDEPRESSION_B,  A.PSYCHIATRICSCHIZOPHRENIA AS PSYCHIATRICSCHIZOPHRENIA_O,  CASE WHEN A.PSYCHIATRICSCHIZOPHRENIA IS NULL THEN '99 - No Selection' ELSE A.PSYCHIATRICSCHIZOPHRENIA|| ' - ' ||H12.VAL END AS PSYCHIATRICSCHIZOPHRENIA_F, DECODE(A.PSYCHIATRICSCHIZOPHRENIA,0,0,NULL,NULL,1) AS PSYCHIATRICSCHIZOPHRENIA_B,  A.OTHERCANCER AS OTHERCANCER_O,  CASE WHEN A.OTHERCANCER IS NULL THEN '99 - No Selection' ELSE A.OTHERCANCER|| ' - ' ||H13.VAL END AS OTHERCANCER_F, DECODE(A.OTHERCANCER,0,0,NULL,NULL,1) AS OTHERCANCER_B,  A.OTHERDIABETES AS OTHERDIABETES_O,  CASE WHEN A.OTHERDIABETES IS NULL THEN '99 - No Selection' ELSE A.OTHERDIABETES|| ' - ' ||H14.VAL END AS OTHERDIABETES_F, DECODE(A.OTHERDIABETES,0,0,NULL,NULL,1) AS OTHERDIABETES_B FROM DW_OWNER.UAS_COMMUNITYHEALTH A  LEFT JOIN DW_OWNER.DIM_UAS_MUSCULOSKELETAL_HIP H1 ON (COALESCE(TO_CHAR(A.MUSCULOSKELETALHIP), 'XX')  = COALESCE(H1.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_MUSCULOSKELETAL_HIP H2 ON (COALESCE(TO_CHAR(A.MUSCULOSKELETALOTHERFRACTURE), 'XX')  = COALESCE(H2.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_MUSCULOSKELETAL_HIP H3 ON (COALESCE(TO_CHAR(A.NEUROLOGICALALZHEIMERS), 'XX')  = COALESCE(H3.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_MUSCULOSKELETAL_HIP H4 ON (COALESCE(TO_CHAR(A.NEUROLOGICALDEMENTIA), 'XX')  = COALESCE(H4.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_MUSCULOSKELETAL_HIP H5 ON (COALESCE(TO_CHAR(A.NEUROLOGICALSTROKE), 'XX')  = COALESCE(H5.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_MUSCULOSKELETAL_HIP H6 ON (COALESCE(TO_CHAR(A.CARDIACHEARTDISEASE), 'XX')  = COALESCE(H6.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_MUSCULOSKELETAL_HIP H7 ON (COALESCE(TO_CHAR(A.CARDIACPULMONARY), 'XX')  = COALESCE(H7.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_MUSCULOSKELETAL_HIP H8 ON (COALESCE(TO_CHAR(A.CARDIACFAILURE), 'XX')  = COALESCE(H8.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_MUSCULOSKELETAL_HIP H9 ON (COALESCE(TO_CHAR(A.PSYCHIATRICANXIETY), 'XX')  = COALESCE(H9.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_MUSCULOSKELETAL_HIP H10 ON (COALESCE(TO_CHAR(A.PSYCHIATRICBIPOLAR), 'XX')  = COALESCE(H10.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_MUSCULOSKELETAL_HIP H11 ON (COALESCE(TO_CHAR(A.PSYCHIATRICDEPRESSION), 'XX')  = COALESCE(H11.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_MUSCULOSKELETAL_HIP H12 ON (COALESCE(TO_CHAR(A.PSYCHIATRICSCHIZOPHRENIA), 'XX')  = COALESCE(H12.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_MUSCULOSKELETAL_HIP H13 ON (COALESCE(TO_CHAR(A.OTHERCANCER), 'XX')  = COALESCE(H13.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_MUSCULOSKELETAL_HIP H14 ON (COALESCE(TO_CHAR(A.OTHERDIABETES), 'XX')  = COALESCE(H14.ID, 'XX')))
,UAS_SEC_I_FCT_TBL  AS (SELECT A.RECORD_ID , CASE WHEN A.FALLS IS NULL THEN '99 - No Selection' ELSE A.FALLS|| ' - ' ||I1.VAL END AS FALLS_F, CASE WHEN A.RECENTFALLS IS NULL THEN '99 - No Selection' ELSE A.RECENTFALLS|| ' - ' ||I2.VAL END AS RECENTFALLS_F, CASE WHEN A.FALLSMEDICAL IS NULL THEN '99 - No Selection' ELSE A.FALLSMEDICAL|| ' - ' ||I3.VAL END AS FALLSMEDICAL_F, CASE WHEN A.DYSPNEA IS NULL THEN '99 - No Selection' ELSE A.DYSPNEA|| ' - ' ||I4.VAL END AS DYSPNEA_F, CASE WHEN A.FATIGUE IS NULL THEN '99 - No Selection' ELSE A.FATIGUE|| ' - ' ||I5.VAL END AS FATIGUE_F, CASE WHEN A.PAINFREQUENCY IS NULL THEN '99 - No Selection' ELSE A.PAINFREQUENCY|| ' - ' ||I6.VAL END AS PAINFREQUENCY_F, CASE WHEN A.PAININTENSITY IS NULL THEN '99 - No Selection' ELSE A.PAININTENSITY|| ' - ' ||I7.VAL END AS PAININTENSITY_F, CASE WHEN A.PAINCONSISTENCY IS NULL THEN '99 - No Selection' ELSE A.PAINCONSISTENCY|| ' - ' ||I8.VAL END AS PAINCONSISTENCY_F, CASE WHEN A.PAINCONTROL IS NULL THEN '99 - No Selection' ELSE A.PAINCONTROL|| ' - ' ||I9.VAL END AS PAINCONTROL_F, CASE WHEN A.SELFRATEDHEALTH IS NULL THEN '99 - No Selection' ELSE A.SELFRATEDHEALTH|| ' - ' ||I10.VAL END AS SELFRATEDHEALTH_F, CASE WHEN A.LIFESTYLESMOKES IS NULL THEN '99 - No Selection' ELSE A.LIFESTYLESMOKES|| ' - ' ||I11.VAL END AS LIFESTYLESMOKES_F, CASE WHEN A.LIFESTYLECHEWSTOBACCO IS NULL THEN '99 - No Selection' ELSE A.LIFESTYLECHEWSTOBACCO|| ' - ' ||I12.VAL END AS LIFESTYLECHEWSTOBACCO_F, CASE WHEN A.LIFESTYLEALCOHOL IS NULL THEN '99 - No Selection' ELSE A.LIFESTYLEALCOHOL|| ' - ' ||I13.VAL END AS LIFESTYLEALCOHOL_F FROM DW_OWNER.UAS_COMMUNITYHEALTH A  LEFT JOIN DW_OWNER.DIM_UAS_FALLS I1 ON (COALESCE(TO_CHAR(A.FALLS), 'XX')  = COALESCE(I1.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_RECENT_FALLS I2 ON (COALESCE(TO_CHAR(A.RECENTFALLS), 'XX')  = COALESCE(I2.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_FALLS_MEDICAL I3 ON (COALESCE(TO_CHAR(A.FALLSMEDICAL), 'XX')  = COALESCE(I3.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_DYSPNEA_CA I4 ON (COALESCE(TO_CHAR(A.DYSPNEA), 'XX')  = COALESCE(I4.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_FATIGUE_CA I5 ON (COALESCE(TO_CHAR(A.FATIGUE), 'XX')  = COALESCE(I5.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PAIN_FREQUENCY_CA I6 ON (COALESCE(TO_CHAR(A.PAINFREQUENCY), 'XX')  = COALESCE(I6.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PAIN_INTENSITY_CA I7 ON (COALESCE(TO_CHAR(A.PAININTENSITY), 'XX')  = COALESCE(I7.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PAIN_CONSISTENCY_CA I8 ON (COALESCE(TO_CHAR(A.PAINCONSISTENCY), 'XX')  = COALESCE(I8.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PAIN_CONTROL_CA I9 ON (COALESCE(TO_CHAR(A.PAINCONTROL), 'XX')  = COALESCE(I9.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_SELF_RATED_HEALTH I10 ON (COALESCE(TO_CHAR(A.SELFRATEDHEALTH), 'XX')  = COALESCE(I10.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_LIFESTYLE_SMOKES I11 ON (COALESCE(TO_CHAR(A.LIFESTYLESMOKES), 'XX')  = COALESCE(I11.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_LIFESTYLE_CHEWS_TOBACC I12 ON (COALESCE(TO_CHAR(A.LIFESTYLECHEWSTOBACCO), 'XX')  = COALESCE(I12.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_LIFESTYLE_ALCOHOL_CA I13 ON (COALESCE(TO_CHAR(A.LIFESTYLEALCOHOL), 'XX')  = COALESCE(I13.ID, 'XX')))
,UAS_SEC_I_GRP_TBL AS (SELECT A.RECORD_ID ,  A.PROBLEMDIZZINESS AS PROBLEMDIZZINESS_O,  CASE WHEN A.PROBLEMDIZZINESS IS NULL THEN '99 - No Selection' ELSE A.PROBLEMDIZZINESS|| ' - ' ||I1.VAL END AS PROBLEMDIZZINESS_F, DECODE(A.PROBLEMDIZZINESS,0,0,NULL,NULL,1) AS PROBLEMDIZZINESS_B,  A.PROBLEMUNSTEADYGAIT AS PROBLEMUNSTEADYGAIT_O,  CASE WHEN A.PROBLEMUNSTEADYGAIT IS NULL THEN '99 - No Selection' ELSE A.PROBLEMUNSTEADYGAIT|| ' - ' ||I2.VAL END AS PROBLEMUNSTEADYGAIT_F, DECODE(A.PROBLEMUNSTEADYGAIT,0,0,NULL,NULL,1) AS PROBLEMUNSTEADYGAIT_B,  A.PROBLEMCHESTPAIN AS PROBLEMCHESTPAIN_O,  CASE WHEN A.PROBLEMCHESTPAIN IS NULL THEN '99 - No Selection' ELSE A.PROBLEMCHESTPAIN|| ' - ' ||I3.VAL END AS PROBLEMCHESTPAIN_F, DECODE(A.PROBLEMCHESTPAIN,0,0,NULL,NULL,1) AS PROBLEMCHESTPAIN_B,  A.PROBLEMABNORMALTHOUGHT AS PROBLEMABNORMALTHOUGHT_O,  CASE WHEN A.PROBLEMABNORMALTHOUGHT IS NULL THEN '99 - No Selection' ELSE A.PROBLEMABNORMALTHOUGHT|| ' - ' ||I4.VAL END AS PROBLEMABNORMALTHOUGHT_F, DECODE(A.PROBLEMABNORMALTHOUGHT,0,0,NULL,NULL,1) AS PROBLEMABNORMALTHOUGHT_B,  A.PROBLEMDELUSIONS AS PROBLEMDELUSIONS_O,  CASE WHEN A.PROBLEMDELUSIONS IS NULL THEN '99 - No Selection' ELSE A.PROBLEMDELUSIONS|| ' - ' ||I5.VAL END AS PROBLEMDELUSIONS_F, DECODE(A.PROBLEMDELUSIONS,0,0,NULL,NULL,1) AS PROBLEMDELUSIONS_B,  A.PROBLEMHALLUCINATIONS AS PROBLEMHALLUCINATIONS_O,  CASE WHEN A.PROBLEMHALLUCINATIONS IS NULL THEN '99 - No Selection' ELSE A.PROBLEMHALLUCINATIONS|| ' - ' ||I6.VAL END AS PROBLEMHALLUCINATIONS_F, DECODE(A.PROBLEMHALLUCINATIONS,0,0,NULL,NULL,1) AS PROBLEMHALLUCINATIONS_B,  A.PROBLEMACIDREFLUX AS PROBLEMACIDREFLUX_O,  CASE WHEN A.PROBLEMACIDREFLUX IS NULL THEN '99 - No Selection' ELSE A.PROBLEMACIDREFLUX|| ' - ' ||I7.VAL END AS PROBLEMACIDREFLUX_F, DECODE(A.PROBLEMACIDREFLUX,0,0,NULL,NULL,1) AS PROBLEMACIDREFLUX_B,  A.PROBLEMCONSTIPATION AS PROBLEMCONSTIPATION_O,  CASE WHEN A.PROBLEMCONSTIPATION IS NULL THEN '99 - No Selection' ELSE A.PROBLEMCONSTIPATION|| ' - ' ||I8.VAL END AS PROBLEMCONSTIPATION_F, DECODE(A.PROBLEMCONSTIPATION,0,0,NULL,NULL,1) AS PROBLEMCONSTIPATION_B,  A.PROBLEMDIARRHEA AS PROBLEMDIARRHEA_O,  CASE WHEN A.PROBLEMDIARRHEA IS NULL THEN '99 - No Selection' ELSE A.PROBLEMDIARRHEA|| ' - ' ||I9.VAL END AS PROBLEMDIARRHEA_F, DECODE(A.PROBLEMDIARRHEA,0,0,NULL,NULL,1) AS PROBLEMDIARRHEA_B,  A.PROBLEMVOMITING AS PROBLEMVOMITING_O,  CASE WHEN A.PROBLEMVOMITING IS NULL THEN '99 - No Selection' ELSE A.PROBLEMVOMITING|| ' - ' ||I10.VAL END AS PROBLEMVOMITING_F, DECODE(A.PROBLEMVOMITING,0,0,NULL,NULL,1) AS PROBLEMVOMITING_B,  A.PROBLEMDIFFICULTSLEEP AS PROBLEMDIFFICULTSLEEP_O,  CASE WHEN A.PROBLEMDIFFICULTSLEEP IS NULL THEN '99 - No Selection' ELSE A.PROBLEMDIFFICULTSLEEP|| ' - ' ||I11.VAL END AS PROBLEMDIFFICULTSLEEP_F, DECODE(A.PROBLEMDIFFICULTSLEEP,0,0,NULL,NULL,1) AS PROBLEMDIFFICULTSLEEP_B,  A.PROBLEMEXCESSSLEEP AS PROBLEMEXCESSSLEEP_O,  CASE WHEN A.PROBLEMEXCESSSLEEP IS NULL THEN '99 - No Selection' ELSE A.PROBLEMEXCESSSLEEP|| ' - ' ||I12.VAL END AS PROBLEMEXCESSSLEEP_F, DECODE(A.PROBLEMEXCESSSLEEP,0,0,NULL,NULL,1) AS PROBLEMEXCESSSLEEP_B FROM DW_OWNER.UAS_COMMUNITYHEALTH A  LEFT JOIN DW_OWNER.DIM_UAS_PROBLEM_DIZZINESS_CA I1 ON (COALESCE(TO_CHAR(A.PROBLEMDIZZINESS), 'XX')  = COALESCE(I1.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PROBLEM_DIZZINESS_CA I2 ON (COALESCE(TO_CHAR(A.PROBLEMUNSTEADYGAIT), 'XX')  = COALESCE(I2.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PROBLEM_DIZZINESS_CA I3 ON (COALESCE(TO_CHAR(A.PROBLEMCHESTPAIN), 'XX')  = COALESCE(I3.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PROBLEM_DIZZINESS_CA I4 ON (COALESCE(TO_CHAR(A.PROBLEMABNORMALTHOUGHT), 'XX')  = COALESCE(I4.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PROBLEM_DIZZINESS_CA I5 ON (COALESCE(TO_CHAR(A.PROBLEMDELUSIONS), 'XX')  = COALESCE(I5.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PROBLEM_DIZZINESS_CA I6 ON (COALESCE(TO_CHAR(A.PROBLEMHALLUCINATIONS), 'XX')  = COALESCE(I6.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PROBLEM_DIZZINESS_CA I7 ON (COALESCE(TO_CHAR(A.PROBLEMACIDREFLUX), 'XX')  = COALESCE(I7.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PROBLEM_DIZZINESS_CA I8 ON (COALESCE(TO_CHAR(A.PROBLEMCONSTIPATION), 'XX')  = COALESCE(I8.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PROBLEM_DIZZINESS_CA I9 ON (COALESCE(TO_CHAR(A.PROBLEMDIARRHEA), 'XX')  = COALESCE(I9.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PROBLEM_DIZZINESS_CA I10 ON (COALESCE(TO_CHAR(A.PROBLEMVOMITING), 'XX')  = COALESCE(I10.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PROBLEM_DIZZINESS_CA I11 ON (COALESCE(TO_CHAR(A.PROBLEMDIFFICULTSLEEP), 'XX')  = COALESCE(I11.ID, 'XX')) LEFT JOIN DW_OWNER.DIM_UAS_PROBLEM_DIZZINESS_CA I12 ON (COALESCE(TO_CHAR(A.PROBLEMEXCESSSLEEP), 'XX')  = COALESCE(I12.ID, 'XX')))
,UAS_SEC_I_ORD_TBL  AS (SELECT A.RECORD_ID ,  A.FALLS AS FALLS_O,  A.FALLSMEDICAL AS FALLSMEDICAL_O,  A.DYSPNEA AS DYSPNEA_O,  A.FATIGUE AS FATIGUE_O,  A.PAINFREQUENCY AS PAINFREQUENCY_O,  A.PAININTENSITY AS PAININTENSITY_O,  A.PAINCONSISTENCY AS PAINCONSISTENCY_O,  A.PAINCONTROL AS PAINCONTROL_O,  A.LIFESTYLEALCOHOL AS LIFESTYLEALCOHOL_O, DECODE(A.SELFRATEDHEALTH, 8, NULL, A.SELFRATEDHEALTH) AS SELFRATEDHEALTH_O FROM DW_OWNER.UAS_COMMUNITYHEALTH A)
,UAS_SEC_L_BIN_TBL  AS (SELECT A.RECORD_ID ,  A.TXBLOODPRESSURE AS TXBLOODPRESSURE_B,  A.TXCOLONOSCOPY AS TXCOLONOSCOPY_B,  A.TXDENTAL AS TXDENTAL_B,  A.TXEYE AS TXEYE_B,  A.TXHEARING AS TXHEARING_B,  A.TXINFLUENZA AS TXINFLUENZA_B,  A.TXMAMMOGRAM AS TXMAMMOGRAM_B,  A.TXPNEUMOVAX AS TXPNEUMOVAX_B,  A.CLINICIMPROPER AS CLINICIMPROPER_B,  A.CLINICINJURY AS CLINICINJURY_B,  A.CLINICRESPIRATORY AS CLINICRESPIRATORY_B,  A.CLINICWOUND AS CLINICWOUND_B,  A.CLINICHYPO AS CLINICHYPO_B,  A.CLINICGI AS CLINICGI_B,  A.CLINICEXACERBATION AS CLINICEXACERBATION_B,  A.CLINICMYOCARDIAL AS CLINICMYOCARDIAL_B,  A.CLINICCHEMOTHERAPY AS CLINICCHEMOTHERAPY_B,  A.CLINICSCHEDULED AS CLINICSCHEDULED_B,  A.CLINICURINARY AS CLINICURINARY_B,  A.CLINICIV AS CLINICIV_B,  A.CLINICTHROMBOSIS AS CLINICTHROMBOSIS_B,  A.CLINICUNCONTROLLEDPAIN AS CLINICUNCONTROLLEDPAIN_B,  A.CLINICPSYCHOTIC AS CLINICPSYCHOTIC_B,  A.CLINICOTHER AS CLINICOTHER_B,  A.CLINICUNKNOWN AS CLINICUNKNOWN_B,  A.ERIMPROPER AS ERIMPROPER_B,  A.ERNAUSEA AS ERNAUSEA_B,  A.ERINJURY AS ERINJURY_B,  A.ERRESPIRATORY AS ERRESPIRATORY_B,  A.ERWOUND AS ERWOUND_B,  A.ERCARDIAC AS ERCARDIAC_B,  A.ERHYPO AS ERHYPO_B,  A.ERGI AS ERGI_B,  A.EROTHER AS EROTHER_B,  A.ERUNKNOWN AS ERUNKNOWN_B,  A.NHTHERAPY AS NHTHERAPY_B,  A.NHRESPITE AS NHRESPITE_B,  A.NHENDOFLIFE AS NHENDOFLIFE_B,  A.NHPLACEMENT AS NHPLACEMENT_B,  A.NHUNSAFE AS NHUNSAFE_B,  A.NHOTHER AS NHOTHER_B, CASE WHEN A.TXINPATIENT >0 THEN 1 WHEN A.TXINPATIENT IS NULL THEN NULL ELSE 0 END  AS TXINPATIENT_B, CASE WHEN A.TXEMERGENCY >0 THEN 1 WHEN A.TXEMERGENCY IS NULL THEN NULL ELSE 0 END  AS TXEMERGENCY_B,  CASE WHEN A.TXPHYSICIAN >0 THEN 1 WHEN A.TXPHYSICIAN IS NULL THEN NULL ELSE 0 END  AS TXPHYSICIAN_B, CASE WHEN A.TXNURSING >0 THEN 1 WHEN A.TXNURSING IS NULL THEN NULL ELSE 0 END  AS TXNURSING_B, CASE WHEN A.NHUNKNOWN >1 THEN NULL WHEN A.NHUNKNOWN IS NULL THEN NULL ELSE A.NHUNKNOWN END AS NHUNKNOWN_B  , A.TXINPATIENT AS TXINPATIENT_C, A.TXEMERGENCY AS TXEMERGENCY_C, A.TXPHYSICIAN AS TXPHYSICIAN_C, A.TXNURSING AS TXNURSING_C FROM DW_OWNER.UAS_COMMUNITYHEALTH A)
,UAS_STD
AS
( 
SELECT 
                a.record_id
              , a.assessmentdate                
 -- Patient Info
              , months_between(a.assessmentdate, a1.dateofbirth) /12 as age_at_assessment_c
              , a1.gender
              , a1.ethnicity
              , a1.racenative
              , a1.raceasian
              , a1.raceblack
              , a1.raceislander
              , a1.racewhite
-- Section A: Intake history            
              , a_bin.physorder_b
              , a_fct.assessmentreason_f
              , a_fct.chareferralsource_f
              , a_bin.goalsmet_b
              , a_fct.residenceassessment_f
              , a_fct.livingarrangement_f
              , a_bin.livingarrangement_b as livingarrangement_alone_b
              , a_bin.reshistoryadultcare_b
              , a_bin.reshistoryltcfacility_b
              , a_bin.reshistorymental_b
              , a_bin.reshistoryintellectual_b
              , a_bin.reshistorypsychiatric_b
              , a_bin.reshistorynursinghome_b
              , a_bin.reshistoryrehab_b
              , a_bin.reshistoryhospice_b
              , a_bin.reshistoryacute_b
              , a_bin.reshistorycorrectional_b
              , a_bin.reshistoryhomeless_b
              , a_fct.reshistoryeducation_o
              , a_fct.reshistoryeducation_f
              , a_bin.reshistoryattendance_b
              , a_fct.resemplystatus_f
              , a_fct.reshistoryemplyarr_f
              , a_fct.reshistorystruc_f
              , a_bin.reshistorystruc_b
              , a_fct.reshistoryvolunteerism_f
              , a_bin.reshistoryvolunteerism_b
              , a_fct.reshistorydayprogram_f
              , a_bin.reshistorydayprogram_b
-- Section B: Cognition
              , a.cognitiveskills as cognitiveskills_o
              , case when a.cognitiveskills is null then '99 - No Selection'
                        when a.cognitiveskills = 5 then  a.cognitiveskills || ' - ' ||  trim(REGEXP_SUBSTR(b1.description,'[^,]+',1,1)) 
                        else a.cognitiveskills || ' - ' || trim(REGEXP_SUBSTR(b1.description,'[^-]+',1,1)) end as cognitiveskills_f
              , a.memoryrecallshort as memoryrecallshort_b
              , a.memoryrecallprocedural as memoryrecallprocedural_b
              , decode(a.impaireddecision, 8, null, a.impaireddecision) as impaireddecision_o
              , case when a.impaireddecision = 8 or a.impaireddecision is null then '8 - Uncertain'
                        else a.impaireddecision || ' - ' || b2.description end as impaireddecision_f
-- Section C: Communication and Vision 
              , c1.selfunderstood_o
              , c1.selfunderstood_f
              , c1.understandothers_o
              , c1.understandothers_f
              , c1.hearing_o
              , c1.hearing_f
              , c1.vision_o
              , c1.vision_f
-- Section D: Mood and behavior
              , d1.negativestatements_o
              , d1.negativestatements_f
              , d1.negativestatements_b as negativestatements_p3d_sts_b
              , d1.persistentanger_o
              , d1.persistentanger_f
              , d1.persistentanger_b as persistentanger_p3d_sts_b
              , d1.unrealfears_o
              , d1.unrealfears_f
              , d1.unrealfears_b as  unrealfears_p3d_sts_b
              , d1.healthcomplaints_o
              , d1.healthcomplaints_f
              , d1.healthcomplaints_b as healthcomplaints_p3d_sts_b
              , d1.anxiouscomplaints_o
              , d1.anxiouscomplaints_f
              , d1.anxiouscomplaints_b as anxiouscomplaints_p3d_sts_b
              , d1.sadfacial_o
              , d1.sadfacial_f
              , d1.sadfacial_b as sadfacial_p3d_sts_b
              , d1.crying_o
              , d1.crying_f
              , d1.crying_b as crying_p3d_sts_b
              , d1.withdrawal_o
              , d1.withdrawal_f
              , d1.withdrawal_b as withdrawal_p3d_sts_b
              , d1.reducedsocial_o
              , d1.reducedsocial_f
              , d1.reducedsocial_b as reducedsocial_p3d_sts_b
              , d1.behaviorwandering_o
              , d1.behaviorwandering_f
              , d1.behaviorwandering_b as behaviorwandering_p3d_sts_b
              , d1.behaviorverbal_o
              , d1.behaviorverbal_f
              , d1.behaviorverbal_b as behaviorverbal_p3d_sts_b
              , d1.behaviorphysical_o
              , d1.behaviorphysical_f
              , d1.behaviorphysical_b as behaviorphysical_p3d_sts_b
              , d1.behaviordisruptive_o
              , d1.behaviordisruptive_f
              , d1.behaviordisruptive_b as behaviordisruptive_p3d_sts_b
              , d1.behaviorsexual_o
              , d1.behaviorsexual_f
              , d1.behaviorsexual_b as behaviorsexual_p3d_sts_b
              , d1.behaviorresists_o
              , d1.behaviorresists_f
              , d1.behaviorresists_b as behaviorresists_p3d_sts_b
              , d2.moodinterest_o
              , d2.moodinterest_f
              , d2.moodinterest_b as moodinterest_p3d_sts_b
              , d2.moodanxious_o
              , d2.moodanxious_f
              , d2.moodanxious_b as moodanxious_p3d_sts_b
              , d2.moodsad_o
              , d2.moodsad_f
              , d2.moodsad_b as  moodsad_p3d_sts_b
-- Section E: Psychosocial well-being             
              , e1.socialparticipation_o
              , e1.socialparticipation_f
              , e1.socialparticipation_b as socialparticipation_sts_b
              , e1.socialvisit_o
              , e1.socialvisit_f
              , e1.socialvisit_b as socialvisit_sts_b
              , e1.socialotherinteraction_o
              , e1.socialotherinteraction_f
              , e1.socialotherinteraction_b as socialotherinteraction_sts_b
              , e1.socialexpressanger_o
              , e1.socialexpressanger_f
              , e1.socialexpressanger_b as socialexpressanger_sts_b
              , e1.socialfearful_o
              , e1.socialfearful_f
              , e1.socialfearful_b as socialfearful_sts_b
              , e1.socialneglected_o
              , e1.socialneglected_f
              , e1.socialneglected_b as socialneglected_sts_b
              , a.lonely as lonely_b
              ,  a.socialchangeactivities as socialchangeactivities_o
              ,  case when a.socialchangeactivities is null then '99 - No Selection'
                        else a.socialchangeactivities || ' - ' || e2.description end as socialchangeactivities_f
              , decode(a.socialchangeactivities,0,0,1,1,2,1, null,null) as socialchangeactivities_b  
              ,  a.timealone as timealone_o
              ,  case when a.timealone is null then '99 - No Selection'
                        else a.timealone || ' - ' || e3.val end as timealone_f
              , a.lifestressors as lifestressors_b
-- Section F: Functional Status
              , f1.iadlperformancemeals_o
              , f1.iadlperformancemeals_f
              , f1.iadlcapacitymeals_o
              , f1.iadlcapacitymeals_f
              , f1.iadlperformancehousework_o
              , f1.iadlperformancehousework_f
              , f1.iadlcapacityhousework_o
              , f1.iadlcapacityhousework_f
              , f1.iadlperformancefinances_o
              , f1.iadlperformancefinances_f
              , f1.iadlcapacityfinances_o
              , f1.iadlcapacityfinances_f
              , f1.iadlperformancemeds_o
              , f1.iadlperformancemeds_f
              , f1.iadlcapacitymeds_o
              , f1.iadlcapacitymeds_f
              , f1.iadlperformancephone_o
              , f1.iadlperformancephone_f
              , f1.iadlcapacityphone_o
              , f1.iadlcapacityphone_f
              , f1.iadlperformancestairs_o
              , f1.iadlperformancestairs_f
              , f1.iadlcapacitystairs_o
              , f1.iadlcapacitystairs_f
              , f1.iadlperformanceshopping_o
              , f1.iadlperformanceshopping_f
              , f1.iadlcapacityshopping_o
              , f1.iadlcapacityshopping_f
              , f1.iadlperformancetransport_o
              , f1.iadlperformancetransport_f
              , f1.iadlcapacitytransport_o
              , f1.iadlcapacitytransport_f
              , f1.iadlperformanceequip_o
              , f1.iadlperformanceequip_f
              , f1.iadlcapacityequip_o
              , f1.iadlcapacityequip_f
              , f2.adlbathing_o
              , f2.adlbathing_f
              , f2.adlhygiene_o
              , f2.adlhygiene_f
              , f2.adldressupper_o
              , f2.adldressupper_f
              , f2.adldresslower_o
              , f2.adldresslower_f
              , f2.adlwalking_o
              , f2.adlwalking_f
              , f2.adllocomotion_o
              , f2.adllocomotion_f
              , f2.adltoilettransfer_o
              , f2.adltoilettransfer_f
              , f2.adltoiletuse_o
              , f2.adltoiletuse_f
              , f2.adlbed_o
              , f2.adlbed_f
              , f2.adleating_o
              , f2.adleating_f
              ,  a.locomotionindoors as locomotionindoors_o
              ,  case when a.locomotionindoors is null then '99 - No Selection'
                        else a.locomotionindoors || ' - ' || f3.val end as locomotionindoors_f                        
              ,  a.hoursexercise as hoursexercise_o
              ,  case when a.hoursexercise is null then '99 - No Selection'
                        else a.hoursexercise || ' - ' || f4.val end as hoursexercise_f
              , decode(a.hoursexercise,0,0,null,null,1) as hoursexercise_sts_b              
              ,  a.daysoutdoors as daysoutdoors_o
              ,  case when a.daysoutdoors is null then '99 - No Selection'
                        else a.daysoutdoors || ' - ' || f5.val end as daysoutdoors_f
              , decode(a.daysoutdoors,0,0,1,0,null,null,1) as daysoutdoors_sts_b
              ,  decode(a.adlstatus, 8, null, a.adlstatus)  as adlstatus_o
              ,  case when a.adlstatus is null then '99 - No Selection'
                        else a.adlstatus || ' - ' || f6.description end as adlstatus_f                        
              ,  a.adlstatusselfsuff  as adlstatusselfsuff_o
              ,  case when a.adlstatusselfsuff is null then '99 - No Selection'
                        else a.adlstatusselfsuff || ' - ' || f7.val end as adlstatusselfsuff_f                        
               , a.drivingdrovecar as drivingdrovecar_b
               , a.drivinglimitstop as drivinglimitstop_b
               , a.iadltransportation as iadltransportation_b         
-- Section G: Continence
              ,  decode(a.bladdercontinence, 8, null, a.bladdercontinence)  as bladdercontinence_o
              ,  case when a.bladdercontinence is null then '99 - No Selection'
                        else a.bladdercontinence || ' - ' || g1.val end as bladdercontinence_f
              , decode(a.bladdercontinence,null,null,0,0,1) as bladdercontinence_cath_b              
              ,  decode(a.bowelcontinence, 8, null, a.bowelcontinence)  as bowelcontinence_o
              ,  case when a.bowelcontinence is null then '99 - No Selection'
                        else a.bowelcontinence || ' - ' || g2.val end as bowelcontinence_f
             , decode(a.bowelcontinence,null,null,0,0,1) as bowelcontinence_cath_b             
-- Section H: Disease diagnoses
              , h1.musculoskeletalhip_o
              , h1.musculoskeletalhip_f
              , h1.musculoskeletalhip_b as musculoskeletalhip_dx_b
              , h1.musculoskeletalotherfracture_o
              , h1.musculoskeletalotherfracture_f
              , h1.musculoskeletalotherfracture_b as musculoskeletalotherfract_dx_b
              , h1.neurologicalalzheimers_o
              , h1.neurologicalalzheimers_f
              , h1.neurologicalalzheimers_b as neurologicalalzheimers_dx_b
              , h1.neurologicaldementia_o
              , h1.neurologicaldementia_f
              , h1.neurologicaldementia_b as neurologicaldementia_dx_b
              , h1.neurologicalstroke_o
              , h1.neurologicalstroke_f
              , h1.neurologicalstroke_b as neurologicalstroke_dx_b
              , h1.cardiacheartdisease_o
              , h1.cardiacheartdisease_f
              , h1.cardiacheartdisease_b as cardiacheartdisease_dx_b
              , h1.cardiacpulmonary_o
              , h1.cardiacpulmonary_f
              , h1.cardiacpulmonary_b as cardiacpulmonary_dx_b
              , h1.cardiacfailure_o
              , h1.cardiacfailure_f
              , h1.cardiacfailure_b as
              , h1.psychiatricanxiety_o
              , h1.psychiatricanxiety_f
              , h1.psychiatricanxiety_b as psychiatricanxiety_dx_b
              , h1.psychiatricbipolar_o
              , h1.psychiatricbipolar_f
              , h1.psychiatricbipolar_b as psychiatricbipolar_dx_b
              , h1.psychiatricdepression_o
              , h1.psychiatricdepression_f
              , h1.psychiatricdepression_b as psychiatricdepression_dx_b
              , h1.psychiatricschizophrenia_o
              , h1.psychiatricschizophrenia_f
              , h1.psychiatricschizophrenia_b as psychiatricschizophrenia_dx_b
              , h1.othercancer_o
              , h1.othercancer_f
              , h1.othercancer_b as othercancer_dx_b
              , h1.otherdiabetes_o
              , h1.otherdiabetes_f
              , h1.otherdiabetes_b as otherdiabetes_dx_b
-- Section I: Health Conditions
              , i_ord.falls_o
              , i_fct.falls_f
              , decode(a.falls,0,0,null,null,1) as falls_90days_sts_b
              , i_fct.recentfalls_f
              , decode(a.recentfalls,0,0,1,1,null) as recentfalls_b
              , i_ord.fallsmedical_o
              , i_fct.fallsmedical_f
              , decode(a.fallsmedical,0,0,null,null,1) as fallsmedical_sts_b
              , case when a.fallsnoinj >0 then 1 when a.fallsnoinj is null then null else 0 end  as fallsnoinj_b
              , a.fallsnoinj as fallsnoinj_c
              , case when a.fallsminorinj >0 then 1 when a.fallsminorinj is null then null else 0 end  as fallsminorinj_b
              , a.fallsminorinj as fallsminorinj_c
              , case when a.fallsmajorinj >0 then 1 when a.fallsmajorinj is null then null else 0 end  as fallsmajorinj_b
              , a.fallsmajorinj as fallsmajorinj_c
              , i_grp.problemdizziness_o
              , i_grp.problemdizziness_f
              , i_grp.problemdizziness_b as problemdizziness_p3d_sts_b
              , i_grp.problemunsteadygait_o
              , i_grp.problemunsteadygait_f
              , i_grp.problemunsteadygait_b as problemunsteadygait_p3d_sts_b
              , i_grp.problemchestpain_o
             , i_grp.problemchestpain_f
              , i_grp.problemchestpain_b as problemchestpain_p3d_sts_b
              , i_grp.problemabnormalthought_o
              , i_grp.problemabnormalthought_f
              , i_grp.problemabnormalthought_b as problemabnormalthght_p3d_sts_b
              , i_grp.problemdelusions_o
              , i_grp.problemdelusions_f
              , i_grp.problemdelusions_b as problemdelusions_p3d_sts_b
              , i_grp.problemhallucinations_o
              , i_grp.problemhallucinations_f
              , i_grp.problemhallucinations_b as problemhallucination_p3d_sts_b
              , i_grp.problemacidreflux_o
              , i_grp.problemacidreflux_f
              , i_grp.problemacidreflux_b as problemacidreflux_p3d_sts_b
              , i_grp.problemconstipation_o
              , i_grp.problemconstipation_f
              , i_grp.problemconstipation_b as problemconstipation_p3d_sts_b
              , i_grp.problemdiarrhea_o
              , i_grp.problemdiarrhea_f
              , i_grp.problemdiarrhea_b as problemdiarrhea_p3d_sts_b
              , i_grp.problemvomiting_o
              , i_grp.problemvomiting_f
              , i_grp.problemvomiting_b as problemvomiting_p3d_sts_b
              , i_grp.problemdifficultsleep_o
              , i_grp.problemdifficultsleep_f
              , i_grp.problemdifficultsleep_b as problemdiffsleep_p3d_sts_b
              , i_grp.problemexcesssleep_o
              , i_grp.problemexcesssleep_f
              , i_grp.problemexcesssleep_b as problemexcesssleep_p3d_sts_b
              , i_ord.dyspnea_o
              , i_fct.dyspnea_f
              , i_ord.fatigue_o
              , i_fct.fatigue_f
              , decode(a.fatigue,0,0,null,null,1) as fatigue_sts_b
              , i_ord.painfrequency_o
              , i_fct.painfrequency_f
              , decode(a.painfrequency,0,0,null,null,1) as painfrequency_p3d_sts_b
              , i_ord.painintensity_o
              , i_fct.painintensity_f
              , decode(a.painintensity,0,0,null,null,1) as painintensity_sts_b
              , i_ord.painconsistency_o
              , i_fct.painconsistency_f
              , decode(a.painconsistency,0,0,null,null,1)as painconsistency_sts_b
              , decode(a.painbreakthrough,0,0,null,null,1) as painbreakthrough_b
              , i_ord.paincontrol_o
              , i_fct.paincontrol_f
--             , decode(a.paincontrol,0,0,1,0,null,null,1) as paincontrol_b
              , a.instabilitypatterns as instabilitypatterns_b
              , a.instabilityacute as instabilityacute_b
              , i_ord.selfratedhealth_o
              , i_fct.selfratedhealth_f
              , i_fct.lifestylesmokes_f
              , a.lifestylesmokessafely as lifestylesmokessafely_b
              , i_fct.lifestylechewstobacco_f
              , i_ord.lifestylealcohol_o
              , i_fct.lifestylealcohol_f
              , decode(a.lifestylealcohol,0,0,null,null,1) as lifestylealcohol_p14d_sts_b
              , a.lifestylesubstance as lifestylesubstance_b
              , a.lifestylesubcriticism as lifestylesubcriticism_b
              , a.lifestylesubguilt as lifestylesubguilt_b
              , a.lifestylesubmorning as lifestylesubmorning_b
              , a.lifestylesubsocial as lifestylesubsocial_b
-- Section J: Nutriotinal Status
              , a.weightloss as weightloss_b
              , a.dehydrated as dehydrated_b
              , a.fluidintake as fluidintake_b
              , a.fluidoutput as fluidoutput_b
              , decode(a.nutritionalintake, 9, null, a.nutritionalintake)  as nutritionalintake_o
              , case when a.nutritionalintake is null then '99 - No Selection'
                        when a.nutritionalintake = 9 then  a.nutritionalintake || ' - ' ||  j1.val
                        else a.nutritionalintake || ' - ' || trim(REGEXP_SUBSTR(j1.val,'[^-]+',1,1)) end as  nutritionalintake_f
-- Section K: Medications
              , a.medsrequiredmeds as medsrequiredmeds_b
              , a.drugallergy as drugallergy_b
-- Section L: Treatments and Procedures
              , l_bin.txbloodpressure_b
              , l_bin.txcolonoscopy_b
              , l_bin.txdental_b
              , l_bin.txeye_b
              , l_bin.txhearing_b
              , l_bin.txinfluenza_b
              , l_bin.txmammogram_b
              , l_bin.txpneumovax_b
              , l_bin.txinpatient_b
              , l_bin.txinpatient_c
              , l_bin.txemergency_b
              , l_bin.txemergency_c
              , l_bin.txphysician_b, l_bin.txphysician_c
              , l_bin.txnursing_b, l_bin.txnursing_c
              , l_bin.clinicimproper_b
              , l_bin.clinicinjury_b
              , l_bin.clinicrespiratory_b
              , l_bin.clinicwound_b
              , l_bin.clinichypo_b
              , l_bin.clinicgi_b
              , l_bin.clinicexacerbation_b
              , l_bin.clinicmyocardial_b
              , l_bin.clinicchemotherapy_b
              , l_bin.clinicscheduled_b
              , l_bin.clinicurinary_b
              , l_bin.cliniciv_b
              , l_bin.clinicthrombosis_b
              , l_bin.clinicuncontrolledpain_b
              , l_bin.clinicpsychotic_b
              , l_bin.clinicother_b
              , l_bin.clinicunknown_b
              , l_bin.erimproper_b
              , l_bin.ernausea_b
              , l_bin.erinjury_b
              , l_bin.errespiratory_b
              , l_bin.erwound_b
              , l_bin.ercardiac_b
              , l_bin.erhypo_b
              , l_bin.ergi_b
              , l_bin.erother_b
              , l_bin.erunknown_b
              , l_bin.nhtherapy_b
              , l_bin.nhrespite_b
              , l_bin.nhendoflife_b
              , l_bin.nhplacement_b
              , l_bin.nhunsafe_b
              , l_bin.nhother_b
              , l_bin.nhunknown_b
-- Section M: Social Supports
              , a.familyrelationship  as familyrelationship_b
              , a.communityrelationship as communityrelationship_b
-- Section N: Environmental Assessment
              , a.finances as finances_b
              , a.finadequatefood as finadequatefood_b
              , a.finadequateshelter as finadequateshelter_b
              , a.finadequateclothing as finadequateclothing_b
              , a.finadequatemedications as finadequatemedications_b
              , a.finadequateheating as finadequateheating_b
              , a.finadequatehealthcare as finadequatehealthcare_b
-- Additional  section:  SCALES
              , decode (s1.description, 'Independent', 0
                                                   , 'Supervision required', 1
                                                   , 'Limited impairment',  2
                                                   , 'Extensive assistance required - 1',  3
                                                   , 'Extensive assistance required - 2',  4
                                                   , 'Dependent', 5
                                                   , 'Total dependence',  6
                                                   , null) as adl_hierarchy_scale_o
              , decode (s1.description, 'Independent', '0 - Independent'
                                                   , 'Supervision required', '1 - Supervision required'
                                                   , 'Limited impairment',  '2 - Limited impairment'
                                                   , 'Extensive assistance required - 1',  '3 - Extensive assistance required - 1'
                                                   , 'Extensive assistance required - 2',  '4 - Extensive assistance required - 2'
                                                   , 'Dependent', '5 - Dependent'
                                                   , 'Total dependence',  '6 - Total dependence'
                                                   , '99 - Could not be calculated') as adl_hierarchy_scale_f
               , s2.value as body_mass_index_c
               , decode( s3.description, 'Intact', 0
                                                      , 'Borderline intact', 1
                                                      , 'Mild impairment', 2
                                                      , 'Moderate impairment', 3
                                                      , 'Moderate/severe impairment', 4
                                                      , 'Severe impairment', 5
                                                      , 'Very severe impairment', 6
                                                      , null ) as cogn_perf_scale_o
               , decode( s3.description, 'Intact', ' 0 - Intact'
                                                      , 'Borderline intact', ' 1 - Borderline intact'
                                                      , 'Mild impairment', ' 2 - Mild impairment'
                                                      , 'Moderate impairment', ' 3 - Moderate impairment'
                                                      , 'Moderate/severe impairment', ' 4 - Moderate/severe impairment'
                                                      , 'Severe impairment', ' 5 - Severe impairment'
                                                      , 'Very severe impairment', ' 6 - Very severe impairment'
                                                      , '99 - Could not be calculated' ) as cogn_perf_scale_f
                , decode( s4.description, 'Intact', 0
                                                      , 'Borderline intact', 1
                                                      , 'Mild impairment', 2
                                                      , 'Mild/moderate impairment', 3
                                                      , 'Moderate impairment', 4
                                                      , 'Moderate/severe impairment', 5
                                                      , 'Severe impairment', 6
                                                      , 'Severe/very severe impairment',7
                                                      , 'Very severe impairment', 8
                                                      , null ) as comm_scale_o
               , decode( s4.description, 'Intact', ' 0 - Intact'
                                                      , 'Borderline intact', ' 1 - Borderline intact'
                                                      , 'Mild impairment', ' 2 - Mild impairment'
                                                      , 'Mild/moderate impairment', ' 3 - Mild/moderate impairment'
                                                      , 'Moderate impairment', ' 4 - Moderate impairment'
                                                      , 'Moderate/severe impairment', ' 5 - Moderate/severe impairment'
                                                      , 'Severe impairment', '6 - Severe impairment'
                                                      , 'Severe/very severe impairment', ' 7 - Severe/very severe impairment'
                                                      , 'Very severe impairment', '8 - Very severe impairement'
                                                      , '99 - Could not be calculated' ) as comm_scale_f
               , s5.value as depression_scale_c
               , s6.value as iadl_cap_scale_c
               , s7.value as iadl_perf_scale_c
               , decode( s8.description, 'No pain', 0
                                                        , 'Less than daily pain', 1
                                                        , 'Daily pain but not severe', 2
                                                        , 'Daily severe pain', 3
                                                        , 'Daily excruciating pain', 4
                                                        , null ) as pain_scale_o
               , decode( s8.description, 'No pain', ' 0 - No pain'
                                                        , 'Less than daily pain', ' 1 - Less than daily pain'
                                                        , 'Daily pain but not severe', ' 2 - Daily pain but not severe'
                                                        , 'Daily severe pain', ' 3 - Daily severe pain'
                                                        , 'Daily excruciating pain', '4 - Daily excruciating pain'
                                                        , '99 - Could not be calculated' ) as pain_scale_f            
FROM dw_owner.uas_communityhealth a
    LEFT JOIN dw_owner.uas_pat_assessments a1 on (a.record_id = a1.record_id)
    -- Section A: Intake history
    LEFT JOIN uas_sec_a_bin_tbl a_bin ON (a.record_id = a_bin.record_id)    
    LEFT JOIN uas_sec_a_fct_tbl a_fct ON (a.record_id = a_fct.record_id)                                                 
    -- Section B: Cognition
    LEFT JOIN dw_owner.dim_u_cognitive_skills b1 ON (coalesce(to_char(a.cognitiveskills), 'XX')  = coalesce(b1.id, 'XX'))
    LEFT JOIN dw_owner.dim_u_impaired_decision b2 ON (coalesce(to_char(a.impaireddecision), 'XX')  = coalesce(b2.id, 'XX'))                  
    -- Section C: Communication and Vision 
    LEFT JOIN uas_sec_c1_tbl  c1 ON (a.record_id = c1.record_id) 
    -- Section D: Mood and behavior
    LEFT JOIN uas_sec_d1_tbl d1 ON (a.record_id = d1.record_id)
    LEFT JOIN uas_sec_d2_tbl d2 ON (a.record_id = d2.record_id)
    -- Section E: Psychosocial well-being 
    LEFT JOIN uas_sec_e1_tbl e1 ON (a.record_id = e1.record_id)
    LEFT JOIN dw_owner.dim_u_social_change_activities e2 ON (coalesce(to_char(a.socialchangeactivities), 'XX')  = coalesce(e2.id, 'XX')) 
    LEFT JOIN dw_owner.dim_uas_time_alone e3 ON (coalesce(to_char(a.timealone), 'XX')  = coalesce(e3.id, 'XX')) 
    -- Section F: Functional Status
    LEFT JOIN uas_sec_f1_tbl f1 ON (a.record_id = f1.record_id)
    LEFT JOIN uas_sec_f2_tbl f2 ON (a.record_id = f2.record_id)
    LEFT JOIN dw_owner.dim_uas_locomotion_indoors f3 ON (coalesce(to_char(a.locomotionindoors), 'XX')  = coalesce(f3.id, 'XX'))
    LEFT JOIN dw_owner.dim_uas_hours_exercise f4 ON (coalesce(to_char(a.hoursexercise), 'XX')  = coalesce(f4.id, 'XX')) 
    LEFT JOIN dw_owner.dim_uas_days_outdoors f5 ON (coalesce(to_char(a.daysoutdoors), 'XX')  = coalesce(f5.id, 'XX'))
    LEFT JOIN dw_owner.dim_u_adl_status f6 ON (coalesce(to_char(a.adlstatus), 'XX')  = coalesce(f6.id, 'XX')) 
    LEFT JOIN dw_owner.dim_uas_adl_status_self_suff f7 ON (coalesce(to_char(a.adlstatusselfsuff), 'XX')  = coalesce(f7.id, 'XX')) 
    -- Section G: Continence
    LEFT JOIN dw_owner.dim_uas_bladder_continence_ca g1 ON (coalesce(to_char(a.bladdercontinence), 'XX')  = coalesce(g1.id, 'XX')) 
    LEFT JOIN dw_owner.dim_uas_bowel_continence_ca g2 ON (coalesce(to_char(a.bowelcontinence), 'XX')  = coalesce(g2.id, 'XX')) 
    -- Section H: Disease diagnoses
    LEFT JOIN uas_sec_h1_tbl h1 ON (a.record_id = h1.record_id)
    -- Section I: Health Conditions
    LEFT JOIN uas_sec_i_grp_tbl  i_grp ON (a.record_id = i_grp.record_id)
    LEFT JOIN uas_sec_i_ord_tbl  i_ord ON (a.record_id = i_ord.record_id)
    LEFT JOIN uas_sec_i_fct_tbl   i_fct ON (a.record_id = i_fct.record_id)
    -- Section J: Nutriotinal Status
    LEFT JOIN dw_owner.dim_uas_nutritional_intake_ca j1 ON (coalesce(to_char(a.nutritionalintake), 'XX')  = coalesce(j1.id, 'XX')) 
    -- Section K: Medications
    -- Section L: Treatments and Procedures
    LEFT JOIN uas_sec_l_bin_tbl l_bin ON (a.record_id = l_bin.record_id)
    -- Section M: Social Supports
    -- Section N: Environmental Assessment
    -- Additional  section:  SCALES  
    LEFT JOIN dw_owner.uas_scale s1 ON  (a.record_id = s1.record_id AND s1.name = 'ADL Hierarchy Scale')
    LEFT JOIN dw_owner.uas_scale s2 ON  (a.record_id = s2.record_id AND s2.name = 'Body Mass Index Scale')
    LEFT JOIN dw_owner.uas_scale s3 ON  (a.record_id = s3.record_id AND s3.name = 'Cognitive Performance Scale')
    LEFT JOIN dw_owner.uas_scale s4 ON  (a.record_id = s4.record_id AND s4.name = 'Communication Scale')
    LEFT JOIN dw_owner.uas_scale s5 ON  (a.record_id = s5.record_id AND s5.name = 'Depression Rating Scale')
    LEFT JOIN dw_owner.uas_scale s6 ON  (a.record_id = s6.record_id AND s6.name = 'IADL Capacity Scale')
    LEFT JOIN dw_owner.uas_scale s7 ON  (a.record_id = s7.record_id AND s7.name = 'IADL Performance Scale')
    LEFT JOIN dw_owner.uas_scale s8 ON  (a.record_id = s8.record_id AND s8.name = 'Pain Scale')
)                             
SELECT * FROM UAS_STD;