CREATE OR REPLACE VIEW V_CARE_MAN_MONTHLY_CALL_SUMM AS 
WITH  CM AS (        
        SELECT
             CASE WHEN DL_LOB_ID = 2 THEN 'MLTC' ELSE 'MAP' END AS LOB
            --, CCM_Title
            , CCM_FIRST_NAME, CCM_LAST_NAME
            , CM_FIRST_NAME, CM_LAST_NAME /* comment out to get overall metric */
            , MONTH_ID
            , COUNT(*) AS N_MEMBERS
            , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NOT NULL THEN 1 ELSE 0 END) AS CONTACTED_N
            , SUM(SUCCESSFUL_IND) AS CONTACTED_SUCCESSFUL_N
            , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END) AS CONTACTED_UNSUCCESSFUL_N
            , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END) AS NOTCONTACTED_N
            , SUM(SUCCESSFUL_IND)/COUNT(*) AS CONTACTED_SUCCESSFUL_PRCNT
            , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END)/COUNT(*) AS CONTACTED_UNSUCCESSFUL_PRCNT
            , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS NOTCONTACTED_PRCNT
        FROM FACT_CARE_MANAGER_MONTHLY_CALL
        GROUP BY CASE WHEN DL_LOB_ID = 2 THEN 'MLTC' ELSE 'MAP' END
            --, CM_Title
            , CCM_FIRST_NAME, CCM_LAST_NAME
            , CM_FIRST_NAME, CM_LAST_NAME -- comment out to get overall metric 
            , MONTH_ID
        UNION 
        SELECT 'MLTC + MAP' LOB
            --, CCM_Title
            , CCM_FIRST_NAME, CCM_LAST_NAME
            , CM_FIRST_NAME, CM_LAST_NAME /* comment out to get overall metric */
            , MONTH_ID
            , COUNT(*) AS N_MEMBERS
            , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NOT NULL THEN 1 ELSE 0 END) AS CONTACTED_N
            , SUM(SUCCESSFUL_IND) AS CONTACTED_SUCCESSFUL_N
            , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END) AS CONTACTED_UNSUCCESSFUL_N
            , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END) AS NOTCONTACTED_N
            , SUM(SUCCESSFUL_IND)/COUNT(*) AS CONTACTED_SUCCESSFUL_PRCNT
            , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END)/COUNT(*) AS CONTACTED_UNSUCCESSFUL_PRCNT
            , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS NOTCONTACTED_PRCNT
        FROM FACT_CARE_MANAGER_MONTHLY_CALL
        GROUP BY 
            --CM_Title
            CCM_FIRST_NAME, CCM_LAST_NAME
            , CM_FIRST_NAME, CM_LAST_NAME -- comment out to get overall metric 
            ,MONTH_ID
        UNION 
        -- sum 
        SELECT  'Overall' AS LOB
                --, CCM_Title
                , CCM_FIRST_NAME, CCM_LAST_NAME
                , CM_FIRST_NAME, CM_LAST_NAME                
                , NULL AS MONTH_I
                , COUNT(*) AS N_MEMBERS
                , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NOT NULL THEN 1 ELSE 0 END) AS CONTACTED_N
                , SUM(SUCCESSFUL_IND) AS CONTACTED_SUCCESSFUL_N
                , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END) AS CONTACTED_UNSUCCESSFUL_N
                , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END) AS NOTCONTACTED_N
                , SUM(SUCCESSFUL_IND)/COUNT(*) AS CONTACTED_SUCCESSFUL_PRCNT
                , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END)/COUNT(*) AS CONTACTED_UNSUCCESSFUL_PRCNT
                , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS NOTCONTACTED_PRCNT
        FROM FACT_CARE_MANAGER_MONTHLY_CALL
        GROUP BY -- CCM_Title,
                 CCM_FIRST_NAME, CCM_LAST_NAME
                 , CM_FIRST_NAME, CM_LAST_NAME -- comment out to get overall metric 
       )             
--2) Summary by team/care coordinator manager
, CCM AS (             
        SELECT CASE WHEN DL_LOB_ID = 2 THEN 'MLTC' ELSE 'MAP' END AS LOB
            --, CCM_Title
            , CCM_FIRST_NAME, CCM_LAST_NAME /* comment out to get overall metric */
            , MONTH_ID
            , COUNT(*) AS N_MEMBERS
            , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NOT NULL THEN 1 ELSE 0 END) AS CONTACTED_N
            , SUM(SUCCESSFUL_IND) AS CONTACTED_SUCCESSFUL_N
            , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END) AS CONTACTED_UNSUCCESSFUL_N
            , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END) AS NOTCONTACTED_N
            , SUM(SUCCESSFUL_IND)/COUNT(*) AS CONTACTED_SUCCESSFUL_PRCNT
            , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END)/COUNT(*) AS CONTACTED_UNSUCCESSFUL_PRCNT
            , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS NOTCONTACTED_PRCNT
        FROM FACT_CARE_MANAGER_MONTHLY_CALL
        GROUP BY CASE WHEN DL_LOB_ID = 2 THEN 'MLTC' ELSE 'MAP' END
            --, CCM_Title
            , CCM_FIRST_NAME, CCM_LAST_NAME -- comment out to get overall metric 
            , MONTH_ID
        UNION 
        SELECT 'MLTC + MAP' LOB
            --, CCM_Title
            , CCM_FIRST_NAME, CCM_LAST_NAME /* comment out to get overall metric */
            , MONTH_ID
            , COUNT(*) AS N_MEMBERS
            , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NOT NULL THEN 1 ELSE 0 END) AS CONTACTED_N
            , SUM(SUCCESSFUL_IND) AS CONTACTED_SUCCESSFUL_N
            , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END) AS CONTACTED_UNSUCCESSFUL_N
            , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END) AS NOTCONTACTED_N
            , SUM(SUCCESSFUL_IND)/COUNT(*) AS CONTACTED_SUCCESSFUL_PRCNT
            , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END)/COUNT(*) AS CONTACTED_UNSUCCESSFUL_PRCNT
            , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS NOTCONTACTED_PRCNT
        FROM FACT_CARE_MANAGER_MONTHLY_CALL
        GROUP BY 
            --CM_Title
            CCM_FIRST_NAME, CCM_LAST_NAME -- comment out to get overall metric 
            ,MONTH_ID
        UNION 
        -- sum 
        SELECT  'Overall' AS LOB
                --, CCM_Title
                , CCM_FIRST_NAME, CCM_LAST_NAME                
                , NULL AS MONTH_I
                , COUNT(*) AS N_MEMBERS
                , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NOT NULL THEN 1 ELSE 0 END) AS CONTACTED_N
                , SUM(SUCCESSFUL_IND) AS CONTACTED_SUCCESSFUL_N
                , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END) AS CONTACTED_UNSUCCESSFUL_N
                , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END) AS NOTCONTACTED_N
                , SUM(SUCCESSFUL_IND)/COUNT(*) AS CONTACTED_SUCCESSFUL_PRCNT
                , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END)/COUNT(*) AS CONTACTED_UNSUCCESSFUL_PRCNT
                , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS NOTCONTACTED_PRCNT
        FROM FACT_CARE_MANAGER_MONTHLY_CALL
        GROUP BY -- CCM_Title,
                 CCM_FIRST_NAME, CCM_LAST_NAME -- comment out to get overall metric 
       )             
--3) Summarize at LOB-County-Month-level
, SUMM AS (
SELECT CASE WHEN DL_LOB_ID = 2 THEN 'MLTC' ELSE 'MAP' END AS LOB
--    , county /* comment out to get overall metric */
    , MONTH_ID
    , COUNT(*) AS N_MEMBERS
    , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NOT NULL THEN 1 ELSE 0 END) AS CONTACTED_N
    , SUM(SUCCESSFUL_IND) AS CONTACTED_SUCCESSFUL_N
    , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END) AS CONTACTED_UNSUCCESSFUL_N
    , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END) AS NOTCONTACTED_N
    , SUM(SUCCESSFUL_IND)/COUNT(*) AS CONTACTED_SUCCESSFUL_PRCNT
    , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END)/COUNT(*) AS CONTACTED_UNSUCCESSFUL_PRCNT
    , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS NOTCONTACTED_PRCNT
FROM FACT_CARE_MANAGER_MONTHLY_CALL
GROUP BY CASE WHEN DL_LOB_ID = 2 THEN 'MLTC' ELSE 'MAP' END
--    , county -- comment out to get overall metric 
    , MONTH_ID
--order by dl_lob_id
--    , county -- comment out to get overall metric 
--    , month_id
UNION 
SELECT 'MLTC + MAP' AS LOB
--    , county /* comment out to get overall metric */
    , MONTH_ID
    , COUNT(*) AS N_MEMBERS
    , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NOT NULL THEN 1 ELSE 0 END) AS CONTACTED_N
    , SUM(SUCCESSFUL_IND) AS CONTACTED_SUCCESSFUL_N
    , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END) AS CONTACTED_UNSUCCESSFUL_N
    , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END) AS NOTCONTACTED_N
    , SUM(SUCCESSFUL_IND)/COUNT(*) AS CONTACTED_SUCCESSFUL_PRCNT
    , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END)/COUNT(*) AS CONTACTED_UNSUCCESSFUL_PRCNT
    , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS NOTCONTACTED_PRCNT
FROM FACT_CARE_MANAGER_MONTHLY_CALL
GROUP BY 
--    , county -- comment out to get overall metric 
    MONTH_ID
--order by dl_lob_id
--    , county -- comment out to get overall metric 
--    , month_id
UNION 
-- sum 
SELECT  'Overall' AS LOB
        , NULL AS MONTH_I
        , COUNT(*) AS N_MEMBERS
        , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NOT NULL THEN 1 ELSE 0 END) AS CONTACTED_N
        , SUM(SUCCESSFUL_IND) AS CONTACTED_SUCCESSFUL_N
        , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END) AS CONTACTED_UNSUCCESSFUL_N
        , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END) AS NOTCONTACTED_N
        , SUM(SUCCESSFUL_IND)/COUNT(*) AS CONTACTED_SUCCESSFUL_PRCNT
        , SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END)/COUNT(*) AS CONTACTED_UNSUCCESSFUL_PRCNT
        , SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END)/COUNT(*) AS NOTCONTACTED_PRCNT
FROM FACT_CARE_MANAGER_MONTHLY_CALL
--group by county -- comment out to get overall metric 
--order by county -- comment out to get overall metric 
) 
SELECT * FROM SUMM


LU_SQL
