DROP VIEW V_FACT_CARE_MAN_MONTHLY_CALL

CREATE OR REPLACE VIEW V_FACT_CARE_MAN_MONTHLY_CALL AS
SELECT 
    DL_LOB_ID,
    CASE WHEN DL_LOB_ID = 2 THEN 'MLTC' 
          WHEN DL_LOB_ID = 5 THEN 'MAP' END AS DL_LOB,
    COUNTY, /* comment out to get overall metric */
    MONTH_ID,
    COUNT(*) AS TOTAL_MEMBERS,
    SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NOT NULL THEN 1 ELSE 0 END) AS MEMBERS_CONTACTED,
    SUM(SUCCESSFUL_IND) AS MEMBERS_CONTACTED_SUCCESSFUL,
    SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END) AS MEMBERS_CONTACTED_UNSUCCESSFUL,
    SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END) AS MEMBERS_NOTCONTACTED,
    ROUND(SUM(SUCCESSFUL_IND)/COUNT(*) * 100,2) AS MEMBERS_CONTACTED_SUC_PRCNT,
    ROUND(SUM(CASE WHEN SUCCESSFUL_IND=0 THEN 1 ELSE 0 END)/COUNT(*)  * 100,2) AS MEMBERS_CONTACTED_UNSUC_PRCNT,
    ROUND(SUM(CASE WHEN SCRIPT_RUN_LOG_ID IS NULL THEN 1 ELSE 0 END)/COUNT(*) * 100,2) AS MEMBERS_NOTCONTACTED_PRCNT
FROM 
    FACT_CARE_MANAGER_MONTHLY_CALL
WHERE
    MONTH_ID >= 201701
GROUP BY
    DL_LOB_ID,
    COUNTY, /* comment out to get overall metric */
    MONTH_ID
ORDER BY
    DL_LOB_ID,
    COUNTY, /* comment out to get overall metric */
    MONTH_ID;
