DROP VIEW MSTRSTG.V_FACT_MEMBER_MONTH_EXP;

CREATE OR REPLACE FORCE VIEW MSTRSTG.V_FACT_MEMBER_MONTH_EXP
AS
    SELECT DATA_SOURCE,
           a.MRN MRN,
           MONTH_ID,
           PROGRAM,
           BOROUGH,
           NULL patient_id,
           COUNTY_CODE,
           STAFF_ID,
           MEDICAID_NUM,
           MEDICARE_NUM,
           SUBSCRIBER_ID,
           BENEFIT_REGION,
           UAS_DATE,
           UAS_NFLOC_SCORE,
           DC_REASON,
           DISENROLL_DISP,
           FLAG,
           CASE_NBR,
           STATE_CODE,
           ENROLLMENT_DATE,
           DISENROLLMENT_DATE,
           ENROLLED_FLAG,
           DISENROLLED_FLAG,
           c.lob_name LINE_OF_BUSINESS,
           PROVIDER_ID,
           PROVIDER_NAME,
           MONTH,
           SSN,
           LAST_NAME,
           FIRST_NAME,
           DATE_OF_BIRTH,
           SEX,
           COUNTY,
           HIGHEST_CASE_NUMBER,
           LOB_ID,
           UAS_RECORD_ID,
           REFERRAL_DATE,
           MANDATORY_ENROLLMENT,
           DISENROLL_RSN_DESC,
           PRODUCT_ID,
           PRODUCT_NAME,
           PLAN_ID,
           PLAN_DESC,
           DL_MEMBER_SK,
           MEMBER_ID,
           DL_PMPM_ENR_SK,
           DL_ENROLL_ID,
           DL_ENRL_SK,
           DL_LOB_ID,
           DL_PLAN_SK,
           PROV_SK_ID,
           CM_SK_ID,
           ASSESSMENT_SK_ID,
           b.DL_LOB_GRP_ID
    FROM   MSTRSTG.fact_member_month a,
           MSTRSTG.D_LOB_GROUP_MAPPING b,
           MSTRSTG.d_line_of_business c
    WHERE      a.dl_lob_id = b.dl_lob_id
           AND b.DL_LOB_GRP_ID = c.DL_LOB_GROUP_ID;

GRANT SELECT ON MSTRSTG.V_FACT_MEMBER_MONTH_EXP TO CHOICEBI WITH GRANT OPTION;