DROP VIEW V_HHA_HOURS_RISK_SCORES;

CREATE OR REPLACE VIEW V_HHA_HOURS_RISK_SCORES
(
    MONTH_ID,
    LOB,
    REGION,
    COUNTY,
    N_MBRS,
    RISK_SCORE,
    ORDER_AUTH_HRS,
    PAID_HRS,
    N_MBRS_NEW_ENROLLEES1,
    RISK_SCORE_NEW_ENROLLEES1,
    ORDER_AUTH_HRS_NEW_ENROLLEES1,
    PAID_HRS_NEW_ENROLLEES1,
    N_MBRS_ALL_OTHERS,
    RISK_SCORE_ALL_OTHERS1,
    ORDER_AUTH_HRS_ALL_OTHERS1,
    PAID_HRS_ALL_OTHERS1,
    N_MBRS_NEW_ENROLLEES3,
    RISK_SCORE_NEW_ENROLLEES3,
    ORDER_AUTH_HRS_NEW_ENROLLEES3,
    PAID_HRS_NEW_ENROLLEES3,
    N_MBRS_ALL_OTHERS3,
    RISK_SCORE_ALL_OTHERS3,
    ORDER_AUTH_HRS_ALL_OTHERS3,
    PAID_HRS_ALL_OTHERS3,
    N_MBRS_DISENROLLEES1,
    RISK_SCORE_DISENROLLEES1,
    ORDER_AUTH_HRS_DISENROLLEES1,
    PAID_HRS_DISENROLLEES1,
    N_MBRS_DISENROLLEES3,
    RISK_SCORE_DISENROLLEES3,
    ORDER_AUTH_HRS_DISENROLLEES3,
    PAID_HRS_DISENROLLEES3
) AS
    WITH group_criteria AS
             (SELECT DISTINCT month_id,
                              region,
                              lob,
                              county
              FROM   v_hha_zuno2_enroll_non_ltp
              UNION
              SELECT DISTINCT month_id,
                              region,
                              lob,
                              county
              FROM   v_hha_zuno2_disenroll_non_ltp
    )
    SELECT /*+ use_hash(a b c) */
           --    b.*, c.*
         A.MONTH_ID,
         A.LOB,
         A.REGION,
         A.COUNTY, --
         NVL(B.N_MBRS,0) N_MBRS,
         NVL(B.RISK_SCORE,0) RISK_SCORE,
         NVL(B.ORDER_AUTH_HRS,0) ORDER_AUTH_HRS,
         NVL(B.PAID_HRS,0) PAID_HRS,
         NVL(B.N_MBRS_NEW_ENROLLEES1,0) N_MBRS_NEW_ENROLLEES1,
         NVL(B.RISK_SCORE_NEW_ENROLLEES1,0) RISK_SCORE_NEW_ENROLLEES1,
         NVL(B.ORDER_AUTH_HRS_NEW_ENROLLEES1,0) ORDER_AUTH_HRS_NEW_ENROLLEES1,
         NVL(B.PAID_HRS_NEW_ENROLLEES1,0) PAID_HRS_NEW_ENROLLEES1,
         NVL(B.N_MBRS_ALL_OTHERS,0) N_MBRS_ALL_OTHERS,
         NVL(B.RISK_SCORE_ALL_OTHERS1,0) RISK_SCORE_ALL_OTHERS1,
         NVL(B.ORDER_AUTH_HRS_ALL_OTHERS1,0) ORDER_AUTH_HRS_ALL_OTHERS1,
         NVL(B.PAID_HRS_ALL_OTHERS1,0) PAID_HRS_ALL_OTHERS1,
         NVL(B.N_MBRS_NEW_ENROLLEES3,0) N_MBRS_NEW_ENROLLEES3,
         NVL(B.RISK_SCORE_NEW_ENROLLEES3,0) RISK_SCORE_NEW_ENROLLEES3,
         NVL(B.ORDER_AUTH_HRS_NEW_ENROLLEES3,0) ORDER_AUTH_HRS_NEW_ENROLLEES3,
         NVL(B.PAID_HRS_NEW_ENROLLEES3,0) PAID_HRS_NEW_ENROLLEES3,
         NVL(B.N_MBRS_ALL_OTHERS3,0) N_MBRS_ALL_OTHERS3,
         NVL(B.RISK_SCORE_ALL_OTHERS3,0) RISK_SCORE_ALL_OTHERS3,
         NVL(B.ORDER_AUTH_HRS_ALL_OTHERS3,0) ORDER_AUTH_HRS_ALL_OTHERS3,
         NVL(B.PAID_HRS_ALL_OTHERS3,0) PAID_HRS_ALL_OTHERS3, 
         NVL(C.N_MBRS_DISENROLLEES1, 0) N_MBRS_DISENROLLEES1,
         NVL(C.RISK_SCORE_DISENROLLEES1, 0) RISK_SCORE_DISENROLLEES1,
         NVL(C.ORDER_AUTH_HRS_DISENROLLEES1, 0) ORDER_AUTH_HRS_DISENROLLEES1,
         NVL(C.PAID_HRS_DISENROLLEES1, 0) PAID_HRS_DISENROLLEES1,
         NVL(C.N_MBRS_DISENROLLEES3, 0) N_MBRS_DISENROLLEES3,
         NVL(C.RISK_SCORE_DISENROLLEES3, 0) RISK_SCORE_DISENROLLEES3,
         NVL(C.ORDER_AUTH_HRS_DISENROLLEES3, 0) ORDER_AUTH_HRS_DISENROLLEES3,
         NVL(C.PAID_HRS_DISENROLLEES3, 0) PAID_HRS_DISENROLLEES3
    FROM group_criteria a
         LEFT JOIN v_hha_zuno2_enroll_non_ltp b ON (a.month_id = b.month_id AND nvl(a.REGION,'NA') = nvl(b.REGION,'NA') AND a.county = b.county AND a.lob = b.lob)
         LEFT JOIN v_hha_zuno2_disenroll_non_ltp c ON (a.month_id = c.month_id AND nvl(a.REGION,'NA') = nvl(C.REGION,'NA') AND a.county = c.county AND a.lob = c.lob);


GRANT SELECT ON V_HHA_HOURS_RISK_SCORES TO LINKADM;

GRANT SELECT ON V_HHA_HOURS_RISK_SCORES TO ROC_RO;
