DROP VIEW V_HHA_ZUNO2_UHC_MEMBERS;

CREATE OR REPLACE VIEW V_HHA_ZUNO2_UHC_MEMBERS
(
    LOB,
    SUBSCRIBER_ID,
    MEMBER_ID,
    CARRIER_NAME,
    ENROLLMENT_START_DT
) AS
    SELECT   E.LOB,
             SUBSCRIBER_ID,
             E.MEMBER_ID,
             CARRIER_NAME,
             ENROLLMENT_START_DT
    FROM     CHOICE.DIM_MEMBER_ENROLLMENT@DLAKE E, CHOICE.DIM_MEMBER_CARRIER@DLAKE C
    WHERE    E.DIM_MEMBER_CARRIER_SK = C.DIM_MEMBER_CARRIER_SK AND E.DL_ACTIVE_REC_IND = 'Y' AND E.ELIGIBILITY_IND = 'Y' AND CARRIER_NAME = 'UNITED HEALTHCARE OF NY INC MLTCPC' AND TO_CHAR( ENROLLMENT_START_DT, 'yyyymm')
             > '201812'
    
    
