DROP VIEW CHOICEBI.V_QUALITY_MEASURE_THRESHOLD;

CREATE OR REPLACE FORCE VIEW CHOICEBI.V_QUALITY_MEASURE_THRESHOLD
AS
    SELECT B.YEAR_ID,
           A.MONTH_ID,
           A.MONTH_DESC,
           A.MONTH_OF_YEAR,
           B.MSR_ID,
           B.MSR_TOKEN,
           B.QUAL_CATEGORY_ID,
           QUAL_CATEGORY_DESC,
           nvl(TARGET,0)  TARGET,
           NVL(PERCENTILE_50TH,0) PERCENTILE_50TH,
           nvl(PERCENTILE_75TH,0) PERCENTILE_75TH,
           nvl(PERCENTILE_90TH,0) PERCENTILE_90TH,
           nvl(IS_FINAL,0) IS_FINAL 
    FROM   MSTRSTG.LU_MONTH A
           JOIN DIM_QUALITY_MEASURE_CAT_MAPING B ON (A.YEAR_ID = B.YEAR_ID)
           JOIN DIM_QUALITY_MEASURE_CATEGORY D
               ON (b.QUAL_CATEGORY_ID = D.QUAL_CATEGORY_ID)
           LEFT JOIN DIM_QUALITY_MEASURE_THRESHOLD C
               ON (    B.YEAR_ID = C.YEAR_ID
                   AND B.MSR_ID = C.MSR_ID);


GRANT SELECT ON CHOICEBI.V_QUALITY_MEASURE_THRESHOLD TO MSTRSTG;



select * from V_QUALITY_MEASURE_THRESHOLD