DROP VIEW VW_UM_AUTH_DECISION_COMBI;

CREATE OR REPLACE VIEW VW_UM_AUTH_DECISION_COMBI
(
    DECISION_ID,
    DECISION_NO,
    AUTH_NO,
    PATIENT_ID,
    UNIQUE_ID,
    AUTH_NOTI_DATE,
    SERVICE_FROM_DATE,
    SERVICE_TO_DATE
) AS
    SELECT DECISION_ID,
           DECISION_NO,
           b.AUTH_NO,
           b.PATIENT_ID,
           c.UNIQUE_ID,
           TRUNC(b.AUTH_NOTI_DATE) AUTH_NOTI_DATE,
           TRUNC(SERVICE_FROM_DATE) SERVICE_FROM_DATE,
           TRUNC(SERVICE_TO_DATE) SERVICE_TO_DATE
    FROM   CMGC.UM_AUTH b
           LEFT OUTER JOIN CMGC.UM_DECISION a ON (a.AUTH_NO = b.AUTH_NO)
           JOIN CMGC.PATIENT_DETAILS c ON (b.PATIENT_ID = c.PATIENT_ID)


GRANT SELECT ON VW_UM_AUTH_DECISION_COMBI TO MSTRSTG;


CON - I77253718


lu_sql
