DROP VIEW VW_UM_AUTH_APPROVED_1ST_PREV;

CREATE OR REPLACE VIEW VW_UM_AUTH_APPROVED_1ST_PREV
(
    PATIENT_ID,
    AUTH_TYPE_ID,
    DECISION_ID,
    REPLIED_DATE,
    CURRENT_APPROVED,
    RANK_PAT_AUTH_TYP,
    RANK_PAT_AUTH_TYP_PREV,
    PREV_APPROVED_AMT,
    FIRST_APPROVED_AMT
) AS
    SELECT   PATIENT_ID,
             AUTH_TYPE_ID,
             DECISION_ID,
             REPLIED_DATE,
             CURRENT_APPROVED,
             RANK() OVER (PARTITION BY PATIENT_ID, AUTH_TYPE_ID ORDER BY MIN(REPLIED_DATE) ASC NULLS LAST) RANK_PAT_AUTH_TYP,
             RANK() OVER (PARTITION BY PATIENT_ID, AUTH_TYPE_ID ORDER BY MIN(REPLIED_DATE) ASC NULLS LAST) - 1.0 RANK_PAT_AUTH_TYP_PREV,
             LAG( CURRENT_APPROVED, 1, 0) OVER (PARTITION BY PATIENT_ID, AUTH_TYPE_ID ORDER BY REPLIED_DATE) PREV_APPROVED_AMT,
             MIN(CURRENT_APPROVED) KEEP (DENSE_RANK FIRST ORDER BY REPLIED_DATE) OVER (PARTITION BY PATIENT_ID, AUTH_TYPE_ID) FIRST_APPROVED_AMT
    FROM     CMGC.UM_AUTH a, CMGC.UM_DECISION b
    WHERE    A.AUTH_NO = b.AUTH_NO
    GROUP BY PATIENT_ID,
             AUTH_TYPE_ID,
             DECISION_ID,
             REPLIED_DATE,
             CURRENT_APPROVED



GRANT SELECT ON VW_UM_AUTH_APPROVED_1ST_PREV TO MSTRSTG
